### ISSUE TITLE
Postgres connection error in Heroku

### ISSUE THREAD

**Issue by pthall** [FreshRSS/FreshRSS#3009] opened 2020-05-27 17:04 UTC
Hi, I could use some help debugging this connection error.

The error at setup for either the CLI or web install is consistently

> Blast! Verify your database information. : Access to database is denied for `[username omitted]`: SQLSTATE[08006] [7] FATAL: permission denied for database "postgres" DETAIL: User does not have CONNECT privilege.

psql command with the same database connection details works. I've also added a `pgtest.php` file with
```
<?php
    $connection = pg_connect (getenv("DATABASE_URL"));
    if($connection) {
       echo 'connected';
    } else {
        echo 'there has been an error connecting';
    } 
?>
```
When I load the page it is successful.

Step 2 of the install is all ok - modules are loaded.

If I understand FreshRSS uses PDO and not the pgsql extension. I have `pdo_pgsql` and `pgsql` modules loaded.

This test `pdotest.php` also returns connected
```
<?php
    $db = parse_url(getenv("DATABASE_URL"));

    $pdo = new PDO("pgsql:" . sprintf(
        "host=%s;port=%s;user=%s;password=%s;dbname=%s",
        $db["host"],
        $db["port"],
        $db["user"],
        $db["pass"],
        ltrim($db["path"], "/")
    ));

    if($pdo) {
       echo 'connected';
    } else {
        echo 'there has been an error connecting';
    }
?>
```

If it helps I can also share access to `phpinfo.php` and whatever else will help project developers. 
Thank you for any information on what may be wrong.

**Comment by Alkarex** [comment] 2020-05-28 21:38
Hello,
Which version of FreshRSS are you trying?

~~It looks wrong to use the `postgres` database. It should be a project-specific one such as `freshrss`. You can either create it or give the freshrss user the right to autocreate the database~~

```sql
CREATE DATABASE "freshrss" ENCODING 'UTF8';
```

Here is where the connection string is built in FreshRSS:
https://github.com/FreshRSS/FreshRSS/blob/cf135073499856abb009fb9e6f297344745adf41/lib/Minz/ModelPdo.php#L74-L82

To see the generated connection string and related parameters, you can insert a debug line just before:

https://github.com/FreshRSS/FreshRSS/blob/cf135073499856abb009fb9e6f297344745adf41/lib/Minz/ModelPdo.php#L121

such as

```php
syslog(LOG_DEBUG, ' DSN: ' . json_encode([$dsn, $username, $passwd, $options]));
```

or

```php
echo ' DSN: ' . json_encode([$dsn, $username, $passwd, $options]), "\n";
```

**Comment by Alkarex** [comment] 2020-05-28 21:44
Ah, sorry, that might be something else. You are not trying to use the `postgres` database, are you?

**Comment by Alkarex** [comment] 2020-05-28 22:09
Could you please try to replace the following line:

https://github.com/FreshRSS/FreshRSS/blob/cf135073499856abb009fb9e6f297344745adf41/app/Models/DatabaseDAO.php#L24

by

```php
		} catch (Exception $e) {
```

**Comment by Alkarex** [comment] 2020-05-29 06:36
I think I might have found the reason during the night :-P Patch coming

**Comment by Alkarex** [comment] 2020-05-29 06:45
@pthall Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/3013

**Comment by Alkarex** [comment] 2020-05-29 21:09
I am at the moment trying to play with PostgreSQL rights to reproduce your bug but without success so far. Could you try to comment out all those 15 lines?

https://github.com/FreshRSS/FreshRSS/blob/19b94b648bf9e8dbc79ccc1765a295660a85e1f8/lib/lib_install.php#L90-L104

**Comment by Alkarex** [comment] 2020-05-29 21:12
I think I have a better fix. New version coming

**Comment by pthall** [comment] 2020-05-29 21:24
This worked :)

> I am at the moment trying to play with PostgreSQL rights to reproduce your bug but without success so far. Could you try to comment out all those 15 lines?
> 
> https://github.com/FreshRSS/FreshRSS/blob/19b94b648bf9e8dbc79ccc1765a295660a85e1f8/lib/lib_install.php#L90-L104

**Comment by Alkarex** [comment] 2020-05-29 21:35
@pthall Please try again with this (proper) fix https://github.com/FreshRSS/FreshRSS/pull/3013

**Comment by pthall** [comment] 2020-05-29 21:49
#3013 with your revised patch is working for me

**Comment by Alkarex** [comment] 2020-05-29 21:56
Thanks for the feedback. Merged in /master branch. Will be in FreshRSS 1.16.1

**Closed as completed** 2020-05-29 21:55 UTC
