### ISSUE TITLE
docker: offer a DEV and LATEST tag for docker images

### ISSUE THREAD

**Issue by Germs2004** [FreshRSS/FreshRSS#3109] opened 2020-07-13 21:24 UTC
Created ticket as requested in #3104

Currently, the "latest" tag in the FreshRSS dockerhub image will download the latest development branch of code, which means users would be running the not-fully-tested code.  I suggest renaming that to "dev" tag for users who want to use alpha or daily builds, and let the "latest" tag download the latest tested release.

This would be a bit more uniform from what I see among other docker projects, and would make it easier for users to always run the latest tested release by using the "latest" tag.

**Comment by Alkarex** [comment] 2020-12-28 12:35
Will do https://github.com/FreshRSS/FreshRSS/discussions/3296
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/3039

**Closed as completed by Alkarex** 2020-12-28 12:35 UTC
Labels: Docker 🐋
