### ISSUE TITLE
The actual version of the extension is different from what is displayed on the admin page

### ISSUE THREAD

**Issue by imkuang** [FreshRSS/FreshRSS#3065] opened 2020-06-19 08:53 UTC
These days I have noticed that there are some updates to the extensions in [FreshRSS/Extensions](https://github.com/FreshRSS/Extensions), and the Image Proxy extension has been upgraded to version 0.5, you can check the [metadata.json](https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/metadata.json) for this information.

So I reinstalled it, but I found that the version displayed on the admin page is still 0.4, as shown below
![WjsE.png](https://img.xirikm.net/images/WjsE.png)

When I enable it, I can see the current version is 0.5 on its management interface.
![WP1z.png](https://img.xirikm.net/images/WP1z.png)

I don’t know how the program gets the versions of each extension, but now the version of Image Proxy is obviously wrong. Although this is not a serious problem, it is better to fix it if possible.

**Comment by Frenzie** [comment] 2020-06-19 09:23
Closing as a duplicate of #3064. As I said there, it'll be fixed by FreshRSS/Extensions#83.

**Closed as completed by Frenzie** 2020-06-19 09:23 UTC
