### ISSUE TITLE
Default views shortcuts are conflicting with sharing shortcuts

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#2215] opened 2019-01-11 17:43 UTC
Hi, I just realized the shortcuts introduced by https://github.com/FreshRSS/FreshRSS/pull/1755 are the same than the "sharing" shortcuts. When I press "1", it triggers the first share option and it changes the view at the same time…

View shortcuts can be changed but the default values are confusing…

**Comment by Alkarex** [comment] 2019-01-15 21:59
Something for @aledeg or @Frenzie maybe?

**Comment by Frenzie** [comment] 2019-01-15 22:17
Oh, since I don't use the sharing functionality except for the occasional test I never noticed. Which functionality were you trying to use btw?

**Comment by aledeg** [comment] 2019-01-16 08:48
I use those all the time and I've never experienced that behavior.
I can reproduce it though only when an article is selected.

**Comment by Alkarex** [comment] 2019-02-05 22:59
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/2234/commits/248e412f1cedddf7110c21b62318194f0b231964 as part of https://github.com/FreshRSS/FreshRSS/pull/2234 (warning: major rewrite, not thoroughly tested yet).
Tests welcome

**Closed as completed by Alkarex** 2019-02-05 22:59 UTC
Labels: Good first issue 1️⃣
