### ISSUE TITLE
Misalignment of unread badges of feeds

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4723] opened 2022-10-13 18:19 UTC
![image](https://user-images.githubusercontent.com/7189936/195675059-786736aa-5849-444f-b4aa-06bf4e24e957.png)

Doing it on categories also

On origine-compact, edge up-to-date

**Comment by Alkarex** [comment] 2022-10-23 22:38
Could you please try again @Alwaysin ? There has been a few patches merged and I cannot reproduce the problem, or I am not looking at the right place

**Comment by Alwaysin** [comment] 2022-10-24 08:44
@Alkarex I still have the problem on updated edge branch, Windows 11 / Chrome 106:

![image](https://user-images.githubusercontent.com/7189936/197485565-50d17257-cfdb-4356-b538-8a6eab9093f7.png)

EDIT: Firefox does the same. Tried two other themes with the same problem.

**Comment by Alkarex** [comment] 2022-10-24 09:02
I cannot see the problem. Is it because is it right-aligned instead of left-aligned?

**Comment by math-GH** [comment] 2022-10-24 10:30
I see it and can confirm this issue

(from the screenshot above, see:)
![grafik](https://user-images.githubusercontent.com/1645099/197506387-ef0a2931-d901-4b7f-8adb-ed874c10fa78.png)

**Comment by Alwaysin** [comment] 2022-10-24 10:33
> I cannot see the problem. Is it because is it right-aligned instead of left-aligned?

It is "down-aligned" instead of just centered on the same line that the text. There is some padding on the top but none on the bottom

The brown thingy from Chrome developers tools illustrates this:
<img width="224" alt="ApplicationFrameHost_2022-10-24_12-33-12" src="https://user-images.githubusercontent.com/7189936/197506871-7669f18a-4a10-4829-a34b-6655bb3d88e1.png">

Or with a line:

![image](https://user-images.githubusercontent.com/7189936/197507853-5e059d25-caf6-40a1-a519-973c7c795b8f.png)

**Comment by Alkarex** [comment] 2022-10-24 11:14
Ah, all right, I could not see it in the screenshot because the text was removed :-P

**Comment by Alwaysin** [comment] 2022-10-24 13:50
Even without the text it is visible with the borders, you can see it sticks to the bottom ;-p
But I agree it wasn't the clearest screenshot ^^

**Closed as completed** 2022-10-29 20:24 UTC
Labels: Theme 🖌, Bug (confirmed) 🐞
