### ISSUE TITLE
Feature Request: Global Filters

### ISSUE THREAD

**Issue by jamieshaw** [FreshRSS/FreshRSS#2788] opened 2020-01-31 14:04 UTC
Nice and simple one – a global 'Mark as read' filter.

So I can add rules like `intitle:'deals' OR author:'deals'` to all feeds, rather than individually per feed.

**Comment by aledeg** [comment] 2022-11-13 11:00
Duplicate of #690

**Comment by Alkarex** [comment] 2023-12-14 16:11
Implemented at last in https://github.com/FreshRSS/FreshRSS/issues/4999
Feedback welcome

**Closed as completed** 2023-12-15 22:04 UTC
Labels: Article filter, Feature Request
