### ISSUE TITLE
[BUG] Thumbnails don't show in the feed listing when Jetpack is enabled in Wordpress

### ISSUE THREAD

**Issue by keynet** [FreshRSS/FreshRSS#5749] opened 2023-10-26 10:45 UTC
**Describe the bug**
If Jetpack (photon) cache is enabled in Wordpress, the image shows correctly in the reading view, but not in the listing of articles "square thumbnail".  The image URL has a different form to the original form.
Even if you scale the image with a function, the behaviour is the same when Jetpack is enabled.

Example URL No Jetpack - OK
`<img width="640" height="480" src="https://www.example.org/wp-content/uploads/2023/10/IMG_7913.jpg
`
Jetpack enabled - Not OK:
`<img width="640" height="480" src="https://i0.wp.com/www.example.org/wp-content/uploads/2023/10/IMG_7913.jpg?fit=640%2C480&amp;ssl=1
`

**To Reproduce**
Enable Jetpack

**Expected behavior**
Jetpack or not, result should be the same
- FreshRSS version: 1.21.0
- PHP version: PHP 7.4.3
- Installation type: On Cpanel, self hosted

**Workarounds**
You could say "don't use Jetpack cache", but Jetpack cache does other things like supporting JP galleries that fall apart without it.
Jetpack can be disabled on a page, image or post, but not apparently on a feed.

**Comment by Frenzie** [comment] 2023-10-26 11:29
> You could say "don't use Jetpack cache", but Jetpack cache does other things like supporting JP galleries that fall apart without it.

Well, I would say it's a bug report *for Jetpack*. ;-)

**Comment by Frenzie** [comment] 2023-10-26 11:34
But could you add a little more detail about what exactly the problem is? Maybe with a screenshot for illustration?

**Comment by keynet** [comment] 2023-10-26 11:56
The problem is that in FreshRSS listing the thumbnail doesn't show.

![Capturess](https://github.com/FreshRSS/FreshRSS/assets/5302023/20683ade-3b01-4979-b7f9-2adcc84755d0)



It's a bug for FreshRSS because the image shows in one view and not another.

![Capture,jk](https://github.com/FreshRSS/FreshRSS/assets/5302023/09d17c6b-ba83-4e39-8856-b9162378d795)

**Comment by Frenzie** [comment] 2023-10-26 12:12
Is the feed something that could be shared?

**Comment by keynet** [comment] 2023-10-26 12:26
Sure, this is the anonymous work-in-progress project. Feed images are scaled, though that makes no difference to the ability to see them in the listing as thumbnails
https://hammersmithsociety.org.uk/freshrss/

**Comment by Alkarex** [comment] 2023-10-26 13:59
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/5750
Would you be able to test?
(test feed: https://www.hammersmithsociety.org.uk/feed/ )

**Comment by keynet** [comment] 2023-10-26 14:04
Yes will do - thanks for such a quick fix!

**Comment by keynet** [comment] 2023-10-26 14:23
Great, thanks, appears fixed.

**Comment by Alkarex** [comment] 2023-10-26 14:34
👍🏻 Merged in edge

**Closed as completed** 2023-10-26 14:33 UTC
Labels: Bug (confirmed) 🐞
