### ISSUE TITLE
Some titles returned by the API contain weird characters

### ISSUE THREAD

**Issue by christophehenry** [FreshRSS/FreshRSS#2803] opened 2020-02-21 14:28 UTC
Exemples on FreshRSS Android:

![Screenshot_1582294702](https://user-images.githubusercontent.com/22097904/75041745-81b69480-54bd-11ea-9a89-6349428209c2.png)

What is returned by the API:

```json
{
  "subscriptions": [
    {
      "id": "feed/44",
      "title": "Heu？reka",
      "categories": [
        {
          "id": "user/-/label/Vids",
          "label": "Vids"
        }
      ],
      "url": "https://www.youtube.com/feeds/videos.xml?channel_id=UC7sXGI8p8PvKosLWagkK9wQ",
      "htmlUrl": "http://www.youtube.com/channel/UC7sXGI8p8PvKosLWagkK9wQ",
      "iconUrl": "******"
    },
    {
      "id": "feed/197",
      "title": "https:／／www.jesuisundev.com／",
      "categories": [
        {
          "id": "user/-/label/Misc",
          "label": "Misc"
        }
      ],
      "url": "https://www.jesuisundev.com/feed/",
      "htmlUrl": "https://www.jesuisundev.com/",
      "iconUrl": "******"
    },
  ]
}
```
What is displayed by the front:

![Screenshot_20200221_154853](https://user-images.githubusercontent.com/22097904/75044208-8c732880-54c1-11ea-9b78-f7618eacd174.png)
![Screenshot_20200221_154823](https://user-images.githubusercontent.com/22097904/75044211-8f6e1900-54c1-11ea-9b1d-274d3b77015e.png)

I suspect an overly eager string escaper.

**Comment by Frenzie** [comment] 2020-02-21 14:32
Duplicate of #2770?

**Comment by christophehenry** [comment] 2020-02-21 14:49
Ah, I see. This happens only when usong the API or the web client has some kind of reverse replacement?
I'm perfectly ok with just reverse-replace the caracters in FreshRSS Android.

**Comment by Alkarex** [comment] 2020-02-29 21:14
@christophehenry Yes, reversing the replacement on your side is the only robust option I see for now, if the full-width version is not good enough for your case.
See the full list on https://github.com/FreshRSS/FreshRSS/issues/2770#issuecomment-575208803

**Closed as completed by Alkarex** 2020-02-29 21:14 UTC
Labels: API :handshake:
