### ISSUE TITLE
[BUG] XML entities in Article CSS selector are not unescaped 

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#4815] opened 2022-11-04 20:07 UTC
**Describe the bug**
The css selector for fetching full articles is returned with HTML escaping intact, which leads to selectors like `[itemprop=&quot;articleBody&quot;]` being passed to CssXPath. The problem seems to be that characters that would be represented as XML entities in the OPML attribute are also being represented as such when being passed around. Other characters have the same problem, e.g. `main &gt; div` and `a[href*='foo&amp;bar']`. The CSS selector for element removal has the same issue.

**To Reproduce**
1. Make sure you can debug the CSS query being passed to CssXPath (with `syslog` or something)
2. Add a CSS Selector with a character that would be escaped in an XML attribute, like `[id="main"]` or `main > article`
3. Click the preview button

**Expected behavior**
Double quotes should behave the same as single quotes in CSS attribute selectors.

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 106.0.1
- FreshRSS version: edge (ca6c934)
- Database version: PostgreSQL 13.8
- PHP version: PHP 7.4
- Installation type: VPS running Debian 11.5 (no Docker)

**Comment by Alkarex** [comment] 2022-11-06 16:39
Probable duplicate of https://github.com/FreshRSS/FreshRSS/issues/4705
Could you please try our edge branch?

**Comment by mrnoname1000** [comment] 2022-11-06 19:09
I should already be up to date on edge and I still have the issue. After saving it appears to be decoded in the UI, but in the backend it's still quoted.

**Comment by Alkarex** [comment] 2022-11-06 19:28
Can you try to save the filter again from the UI?

**Comment by mrnoname1000** [comment] 2022-11-06 19:46
After saving again it still appears fine in the UI, but the issue persists. Also the issue occurs even without submitting, so I think #4705 is a separate issue.

**Comment by Alkarex** [comment] 2022-11-06 21:43
@mrnoname1000 Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/4823

**Comment by mrnoname1000** [comment] 2022-11-06 22:23
That seems to have fixed the issue but only for the filter selector, the article selector still has the issue.

**Comment by Alkarex** [comment] 2022-11-06 23:05
I had forgotten to also fix the preview function. Please try again.

**Comment by mrnoname1000** [comment] 2022-11-07 04:14
I tested with the preview function and both fields work as expected! I haven't tested a feed refresh yet but the preview and submit definitely work.

**Closed as completed** 2022-11-07 07:34 UTC
Labels: Bug (confirmed) 🐞
