### ISSUE TITLE
Please add better sorting options when adding new feeds

### ISSUE THREAD

**Issue by lonseidman** [FreshRSS/FreshRSS#5529] opened 2023-07-15 12:40 UTC
I realize this issue will be closed as soon as I open it, but I think it's worth putting this back on the front burner even for a short time.

I am a new FreshRSS user. I've spent the better part of this week playing with all of the options out there for self-hosted RSS feeds and FreshRSS is the one I keep coming back to. While I subscribe to Bazqux for my day-to-day feed reading I wanted something I could use to consolidate my YouTube subscriptions into a topic-based system where I and not the YouTube algorithm decide what gets put in front of me.

The problem I'm having is the same one that's been raised by many others: adding a new feed to the mix brings all of the articles from that feed to the top of the list regardless of the date they were posted. It seems as though this is by design but this is not a good user experience and not what any of the alternative readers are doing with new feeds.

I have, with mixed success, used some MySQL code to reorder the database but it's a pain to have to do that every time I add a new group of feeds. And my code is not always able to do this reliably.

It would be great to give the user the choice about how to sort new feeds into the database. Some may like this behavior but I think there's an equal number who don't.

**Comment by Frenzie** [comment] 2023-07-15 12:57
> I realize this issue will be closed as soon as I open it

Yes, but because it's a duplicate of #2596 among others, not because of the subject matter. ;-)

> It seems as though this is by design but this is not a good user experience and not what any of the alternative readers are doing with new feeds.

GOG Galaxy somehow can't sort games by date purchased, only by date released. It's horrifically unusable for the purpose. :-P

Anyway, I don't think anyone's opposed to a new sorting mode being added. There's just also no one who seems to be interested in putting in the work of adding such a thing.

I do feel the need to point out that QuiteRSS (which I used for a while after the death of Opera/Presto) offers both published and received sorting options and so do most other readers I've tried.

**Closed as completed by Frenzie** 2023-07-15 12:57 UTC
Labels: Duplicate ‼

**Comment by Frenzie** [comment] 2023-07-15 13:00
And more confusingly a literal duplicate of https://github.com/FreshRSS/Extensions/issues/161?

**Comment by math-GH** [comment] 2023-07-16 12:36
PRs are welcome to improve it :)

**Comment by Alkarex** [comment] 2024-12-27 16:19
https://github.com/FreshRSS/FreshRSS/pull/7149
