### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by PierrickBrun** [FreshRSS/FreshRSS#2033] opened 2018-09-26 20:54 UTC
I think it would be easyd to add a Manifest file allowing to make a Progressive Web App out of FreshRSS.

For reference : https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Installable_PWAs

On android it would be a good alternative to using EasyRSS while not being very time consuming. I think the website works well on mobile but it would be better to have it as a separated app.

**Comment by Alkarex** [comment] 2018-09-27 17:46
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/1963
Yes, it could be good. But note that it is not enough just to add a manifest to get something useful such as offline mode, which requires some more work :-)

**Closed as completed by Alkarex** 2018-09-27 17:46 UTC
