### ISSUE TITLE
https://www.freshrss.org/ - fonts not loaded

### ISSUE THREAD

**Issue by cweiske** [FreshRSS/FreshRSS#1970] opened 2018-08-06 11:09 UTC
The https://www.freshrss.org/ site misses icons in the top menu because the fonts could not be loaded:

> Access to Font at 'https://freshrss.org/theme/fonts/icomoon.woff?-8e97i1' from origin 'https://www.freshrss.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.freshrss.org' is therefore not allowed access.

Same for `SourceSansPro.ttf` and `icomoon.tts?-8e97i1`.

**Comment by Alkarex** [comment] 2018-08-23 18:40
This is something for @marienfressinaud 

![image](https://user-images.githubusercontent.com/1008324/44545148-91142080-a714-11e8-80de-1dd2d3cc1d23.png)

@cweiske If you are motivated enough, please move the bug report to where it should be https://github.com/FreshRSS/freshrss.org/issues

**Comment by marienfressinaud** [comment] 2018-08-28 07:35
I'll take a look, thanks! (btw, it works fine on https://freshrss.org, except for the AlternativeTo widget)

**Comment by marienfressinaud** [comment] 2018-09-03 18:17
Hey there! The issue is now fixed :) I opened the CORS rules and removed the AlternativeTo widget (API is no longer maintained).

Also, the cloud.docker.com was no longer building the FreshRSS images because I enforced security rules few weeks ago and forgot to grant access to repositories for Docker. It is now fixed too :+1:

**Closed as completed by marienfressinaud** 2018-09-03 18:17 UTC
