### ISSUE TITLE
[Bug] Database deadlock detected and minorDbMaintenance question

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#6592] opened 2024-06-24 16:34 UTC
### Describe the bug

I've started to monitor more closely the errors happening on my servers, and I've noticed a recurring error (from 1 to 5 times per day):

```
Jun 24 07:18:47 rufus FreshRSS[1657425]: [<redacted>] [Mon, 24 Jun 2024 07:18:47 +0200] [error] --- SQL error FreshRSS_EntryDAO::listWhereRaw["40P01",7,"ERROR:  deadlock detected
LINE 3: ...N (SELECT e.id FROM \"<redacted>_entry\" e INNER JOIN \"<redacted>_...
                                                             ^
DETAIL:  Process 2829552 waits for AccessShareLock on relation 117495229 of database 17952; blocked by process 2829553.
Process 2829553 waits for AccessExclusiveLock on relation 117495254 of database 17952; blocked by process 2829552.
HINT:  See server log for query details."]
```

Looking at the logs from PostgreSQL, I was able to find that two methods are always involved:

- [`EntryDAO::listWhereRaw`](https://github.com/FreshRSS/FreshRSS/blob/7a9a24a0d0f2e5cc674995ce3174116803acde09/app/Models/EntryDAO.php#L1157)
- and [`DatabaseDAO::minorDbMaintenance`](https://github.com/FreshRSS/FreshRSS/blob/7a9a24a0d0f2e5cc674995ce3174116803acde09/app/Models/DatabaseDAO.php#L230)

Note the error happens for only one user (on a total of 500 users).

### To Reproduce

I don't know :shrug: 

### Expected behavior

No error in the logs? :)

### FreshRSS version

1.24.0

### Environment information

- Database version: PostgreSQL 15
- PHP version: PHP 8.2
- Installation type: Git
- Web server type: Nginx
- Device: N/A
- OS: Debian 12
- Browser: N/A

### Additional context

From what I can tell, [the SQL requests](https://github.com/FreshRSS/FreshRSS/blob/7a9a24a0d0f2e5cc674995ce3174116803acde09/app/SQL/install.sql.pgsql.php#L105-L134) from `minorDbMaintenance` are executed in [a lot of situations](https://github.com/search?q=repo%3AFreshRSS/FreshRSS%20minorDbMaintenance&type=code), and I'm wondering why. `ALTER TABLE` should be called only once in order to change the tables, and not each time we refresh the feeds (especially since there is a migration system :P)

I would recommend to change this system, which should hopefully resolve this issue!

**Comment by Alkarex** [comment] 2024-06-24 17:17
Quick answer already, and I will develop later: could you try to comment out the minorDbMaintenance code and confirm that there is no other error? 
It could indeed hide something else. This code is supposed to be near instantaneous when the updates have been done

**Comment by marienfressinaud** [comment] 2024-06-24 17:27
I've just deployed a patch to comment out the `minorDbMaintenance` code and to add some logs in `EntryDAO::listWhereRaw` in order to see if there is a pattern in the parameters that could help to understand the problem a bit more.

**Comment by marienfressinaud** [comment] 2024-06-28 14:23
I can confirm that the error no longer happens with the code of `minorDbMaintenance` commented :)

**Comment by Alkarex** [comment] 2024-08-03 20:43
@marienfressinaud Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/6692
It performs a basic feature detection to decide whether to apply the minor SQL updates or not.

> I can confirm that the error no longer happens with the code of `minorDbMaintenance` commented :)

After a few more weeks, can you still confirm? (I am still curious of whether this is the sole problem)

> especially since there is a migration system

Coming back to your suggestion, I am not a fan of the migration system (and I have avoided it) because it does not address my main concerns, such as:

* What happens when a user restores a database backup, or other forms of export / import (e.g. move the SQLite file)
* What happens if the migration does not have enough time to complete before the script times out (CLI cron typically does not have this problem)
* What happens for (test) users jumping back and forth between different versions / branches
* Avoid as much as possible tests slowing down the main operations for which the user is waiting (in particular the main HTTP request to load FreshRSS) and try to put them instead in cron / background operations
* (And we have a bigger problem with SQLite, which does not support many types of updates)

I can better like feature detection and/or reactions on errors, but some improvements are indeed possible.

**Comment by Alkarex** [comment] 2024-08-04 17:42
Merged in edge. Feedback welcome

**Closed as completed** 2024-08-04 17:42 UTC
Labels: Bug (unconfirmed)

**Comment by marienfressinaud** [comment] 2024-08-11 15:14
> Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/6692

I've just updated my server, I'll let you know in few days if the error still occurs or not.

> After a few more weeks, can you still confirm? (I am still curious of whether this is the sole problem)

I confirm that I never had the problem again :)

> Coming back to your suggestion, I am not a fan of the migration system (and I have avoided it) because it does not address my main concerns, such as: […]

I understand :+1:

**Comment by marienfressinaud** [comment] 2024-08-15 09:40
4 days later, still no error, I think we can consider it's fixed. Thanks!

**Comment by Alkarex** [comment] 2024-08-15 19:40
@marienfressinaud Could you please pull the latest `edge`, which includes a fix for a DB transaction regression fix? https://github.com/FreshRSS/FreshRSS/pull/6713
