### ISSUE TITLE
[BUG] ITems showing up that don't show up in RSS source

### ISSUE THREAD

**Issue by quartzbear** [FreshRSS/FreshRSS#5257] opened 2023-04-04 08:41 UTC
**Describe the bug**
Freshrss showing items that don't show up in the original feed (ads from twitter, I think).

**To Reproduce**
1. Add anyone of these feed to Freshrss -options [1](https://rsshub.app/twitter/keyword/(GIVEAWAY%20OR%20giveaway%20OR%20sweeps%20OR%20sweepstakes%20OR%20enter%20OR%20win)%20(from:penguinusa%20OR%20from:PenguinBooks%20OR%20from:doubledaybooks%20OR%20from:HarperCollins%20OR%20from:penguinrandom%20OR%20from:harperbooks%20OR%20from:penguinpress%20OR%20from:riverheadbooks%20OR%20from:littlebrown%20OR%20from:mulhollandbooks%20OR%20from:AAKnopf%20OR%20from:HachetteUS%20OR%20from:harperbooks%20OR%20from:AlgonquinBooks%20OR%20from:VikingBooks%20OR%20from:randomhouse%20OR%20from:PantheonBooks%20OR%20from:ScribnerBooks%20OR%20from:wwnorton%20OR%20from:PenguinTeen%20OR%20from:AceRocBooks)), [2 ](https://rsshub.app/twitter/keyword/(GIVEAWAY%20OR%20giveaway%20OR%20sweeps%20OR%20sweepstakes%20OR%20enter)%20(from:RebellionPub%20OR%20from:torbooks%20OR%20from:dawbooks%20OR%20from:locusmag%20OR%20from:Pyr_Books%20OR%20from:angryrobotbooks%20OR%20from:BaenBooks%20OR%20from:ApexBookCompany%20OR%20from:TorDotComPub%20OR%20from:TorNig))and [3](https://rsshub.app/twitter/keyword/(GIVEAWAY%20OR%20giveaway%20OR%20sweeps%20OR%20sweepstakes%20OR%20enter%20OR%20win)%20(from:eccobooks)%20OR%20from:fsgbooks%20OR%20from:PicadorUSA%20OR%20from:simonschuster%20OR%20from:SimonBooks%20OR%20from:AtriaBooks%20OR%20from:simonteen%20OR%20from:GraywolfPress%20OR%20from:GrandCentralPub%20OR%20from:DisneyBooks%20OR%20from:ShelfAwareness)).
2. Scroll through the feed.
3. You will encounter non-recent posts that don't show up in the top of the RSS feed ( I think they are ads that get boosted to the top somehow, even when not recent). Items by "metapcs", "swift" etc.

**Expected behavior**
Feed in fetchrss to match source.

**Screenshots**
For examle, this ad shows up in the top of the Freshrs feeds, by "meta pcs"
![image](https://user-images.githubusercontent.com/33700415/229735991-9429383b-e9c5-4f2a-83da-be6c564cad7f.png)
![image](https://user-images.githubusercontent.com/33700415/229736161-190d0537-ef94-485b-8419-0d5b80cc2c4f.png)
but not in the source itself:
![image](https://user-images.githubusercontent.com/33700415/229736504-a1348787-52b9-400a-a8d8-e4540ef6a6ad.png)

**Environment information (please complete the following information):**
- Device: Laptop,Acer SFX14-41G
- OS: Windows 11 Home 22H2
- Browser: Firefox 111.0.1 (64-bit)
- FreshRSS version: 1.21.0 
- Database version: [I don't know how to check.
- PHP version: I don't know how to check.
- Installation type: Docker

**Comment by math-GH** [comment] 2023-04-07 20:58
I will follow your `feed 1` and will try to reproduce it.

**Comment by math-GH** [comment] 2023-04-07 22:50
Just for the record: There is an error in the log:

`Feed has invalid GUIDs: https://rsshub.app/twitter/keyword/(GIVEAWAY%20OR%20giveaway%20OR%20sweeps%20OR%20sweepstakes%20OR%20enter%20OR%20win)%20(from:penguinusa%20OR%20from:PenguinBooks%20OR%20from:doubledaybooks%20OR%20from:HarperCollins%20OR%20from:penguinrandom%20OR%20from:harperbooks%20OR%20from:penguinpress%20OR%20from:riverheadbooks%20OR%20from:littlebrown%20OR%20from:mulhollandbooks%20OR%20from:AAKnopf%20OR%20from:HachetteUS%20OR%20from:harperbooks%20OR%20from:AlgonquinBooks%20OR%20from:VikingBooks%20OR%20from:randomhouse `

Ping @Alkarex : It is an Atom feed and the validator does not have an issue with the missed GUID.

**Comment by math-GH** [comment] 2023-04-08 22:10
There is a general issue with the GUID of the feed 1. It is valid and invalid each hour:

![grafik](https://user-images.githubusercontent.com/1645099/230744480-40c8c01e-bf1e-4c4e-853d-0fb60874a0c4.png)

I can confirm that there is some strange with the feed. This feed pops up time by time:
![grafik](https://user-images.githubusercontent.com/1645099/230744536-4f58349c-370d-4042-a673-860c8168b522.png)

This article from Januar 4th appears in the feed and disappears. Some minute it appeared, now it disappeared in the feed.

For me, it looks like an issue with rsshub.app

**Comment by Alkarex** [comment] 2023-04-08 22:47
Handling of wrong feeds will be improved with https://github.com/FreshRSS/FreshRSS/pull/4487, which is not merged yet, because I have an idea of storing the unicity in the articles' attributes to better handle changes of unicity types.

**Comment by quartzbear** [comment] 2023-04-09 04:52
Thanks for looking in to it

**Closed as completed** 2024-10-14 07:34 UTC
Labels: Feed problem :newspaper_roll:, Bug (unconfirmed)
