### ISSUE TITLE
Can the system natively support AI summary functionality?

### ISSUE THREAD

**Issue by Whichbfj28** [FreshRSS/FreshRSS#6629] opened 2024-07-17 03:27 UTC
Conveniently summarize the content of each RSS and display it at the top of the article

**Comment by Alkarex** [comment] 2024-07-17 16:47
Hello,
Duplicate of https://github.com/FreshRSS/Extensions/issues/240#issuecomment-2134923440

**Closed as completed by Alkarex** 2024-07-17 16:47 UTC
Labels: Extension :electric_plug:
