### ISSUE TITLE
[Bug] CSS selector to remove elements is not removing elements properly

### ISSUE THREAD

**Issue by Tywele** [FreshRSS/FreshRSS#7014] opened 2024-11-21 08:37 UTC
### Describe the bug

I have a CSS selector in the config field to remove a certain element from an article and it's not being removed.

### To Reproduce

1. Using this feed: `https://www.queer.de/rss/newsticker2.0.komplett.xml`
2. Add the article CSS selectors: `.artikel>p, .artikel>blockquote, .artikel>.bildkasten`
3. Add the CSS selectors to remove elements: `p[data-sanitized-class="leistenbanner"]` or `.artikel>p[data-sanitized-class="leistenbanner"]` or `.artikel>.leistenbanner` or `.leistenbanner` (none of them work)
4. See the element still being fetched in the article

### Expected behavior

The element should not appear in the fetched article

### FreshRSS version

1.25.0-dev

### Environment information

Installation type: Docker

### Additional context

Screenshot of website with uBlock Origin disabled to see the element I want to remove
![Screenshot of website with uBlock Origin disabled to see the element I want to remove](https://github.com/user-attachments/assets/d558b65a-55dd-4d46-a716-87a5a49aa997)

Screenshot of the article in my FreshRSS feed to see that the element is still in the article
![Screenshot of the article in my FreshRSS feed to see that the element is still in the article](https://github.com/user-attachments/assets/4d4bb870-b38b-4f1f-a74b-c9473a4bbb18)

**Comment by Alkarex** [comment] 2024-11-21 09:20
Could you please export the feed settings as OPML as the bottom of the feed settings?

**Comment by Tywele** [comment] 2024-11-21 09:30
https://drive.proton.me/urls/XHQVXHZ5CG#o20KuHA6q6kv

Github didn't let me attach an XML file to a comment so here is Proton Drive link to the file.

**Comment by Frenzie** [comment] 2024-11-21 11:10
You can always zip it or simply add .txt at the end.

Edit: or for something relatively small, just paste it.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml xmlns:frss="https://freshrss.org/opml" version="2.0">
  <head>
    <title>FreshRSS</title>
    <dateCreated>Thu, 21 Nov 2024 10:28:05 +0100</dateCreated>
  </head>
  <body>
    <outline text="Queer.de - Das Magazin für die LGBTI-Community" type="rss" xmlUrl="https://www.queer.de/rss/newsticker2.0.komplett.xml" htmlUrl="https://www.queer.de/" description="Das Info-Portal der Community: Nachrichten, Hintergründe, Kultur und Unterhaltung für Schwule, Lesben, Bisexuelle und trans Personen" frss:filtersActionRead="#Kunst+&amp;amp;+Kultur+-+Ausstellungen&#10;#Life+&amp;amp;+Style+-+Body+&amp;amp;+Fashion&#10;#Buch+-+Sachbücher&#10;#Buch+-+Hörbücher&#10;#Buch+-+Literatur&#10;#Szene+-+Deutschland&#10;intitle:Jobs:&#10;#Kunst+&amp;amp;+Kultur+-+Bühne&#10;#Boulevard+-+Europa&#10;#Film+&amp;amp;+TV+-+Serien&#10;#Film+&amp;amp;+TV+-+Reality+&amp;amp;+Casting&#10;#Film+&amp;amp;+TV+-+Dramen&#10;#Film+&amp;amp;+TV+-+Aktuell&#10;#Film+&amp;amp;+TV+-+Dokumentationen&#10;#Film+&amp;amp;+TV+-+Komödien&#10;#Boulevard+-+Deutschland&#10;#Boulevard+-+International&#10;#Musik+-+Aktuell&#10;#Buch+-+Biografien&#10;#Gewinnspiel" frss:cssFullContent=".artikel&gt;p, .artikel&gt;blockquote, .artikel&gt;.bildkasten" frss:cssFullContentFilter="p[data-sanitized-class=&quot;leistenbanner&quot;]"/>
  </body>
</opml>
```

**Comment by math-GH** [comment] 2024-11-21 21:07
I can reproduce it.

Reloading the feed does not fix it.

**Comment by math-GH** [comment] 2024-11-21 21:14
`iframe` works

**Comment by Alkarex** [comment] 2024-11-30 12:45
@Tywele Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/7037
Try with `p.leistenbanner`
Tests welcome

Note that th `data-sanitized-` prefix is added later, so it should not be used for the CSS selectors

**Comment by Tywele** [comment] 2024-11-30 15:00
![Screenshot_20241130-155831.png](https://github.com/user-attachments/assets/d4f8b2fa-785f-4d93-8593-9a5950a83ceb)

The hint about sanitized CSS classes should be removed then if you can't use them there. That's why I tried them.

Will try the fix.

Edit: I might have been a bit too quick saying that I will try the fix. Because I thought the fix would be in `freshrss:edge` already and I would only have to update. How can I pull your PR specifically to test it?

**Comment by Alkarex** [comment] 2024-11-30 16:10
> The hint about sanitized CSS classes should be removed then if you can't use them there. That's why I tried them.

Let me address that in another issue / PR. On the road at the moment, but we might have a discrepancy between filtering on the content provided by the RSS feed and filtering on the content scraped from the Web site.

> How can I pull your PR specifically to test it?

To test this branch:

```yml
  freshrss:
    image: freshrss/freshrss:7037
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-css-selector-remove
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by Tywele** [comment] 2024-11-30 20:12
I can confirm that it's fixed with #7037

**Closed as completed** 2024-11-30 20:17 UTC
Labels: Bug (confirmed) 🐞

**Comment by Alkarex** [comment] 2024-11-30 20:19
https://github.com/FreshRSS/FreshRSS/issues/7039

**Comment by Alkarex** [comment] 2024-12-07 11:57
> The hint about sanitized CSS classes should be removed then if you can't use them there. That's why I tried them.

Modified in https://github.com/FreshRSS/FreshRSS/pull/7073, which allows using the same CSS filters for content coming from RSS feeds and from Web scraping

So now it should be `p[data-sanitized-class="leistenbanner"]`. Could you please test, @Tywele ?

**Comment by Tywele** [comment] 2024-12-10 10:55
I couldn't test it yet but recently the Article CSS selector doesn't seem to retrieve the whole article anymore. Here is the exported feed: 

```
<opml version="2.0">
<head>
<title>FreshRSS</title>
<dateCreated>Tue, 10 Dec 2024 11:54:26 +0100</dateCreated>
</head>
<body>
<outline text="Queer.de - Das Magazin für die LGBTI-Community" type="rss" xmlUrl="https://www.queer.de/rss/newsticker2.0.komplett.xml" htmlUrl="https://www.queer.de/" description="Das Info-Portal der Community: Nachrichten, Hintergründe, Kultur und Unterhaltung für Schwule, Lesben, Bisexuelle und trans Personen" frss:filtersActionRead="#Kunst+&amp;+Kultur+-+Ausstellungen #Life+&amp;+Style+-+Body+&amp;+Fashion #Buch+-+Sachbücher #Buch+-+Hörbücher #Buch+-+Literatur #Szene+-+Deutschland intitle:Jobs: #Kunst+&amp;+Kultur+-+Bühne #Boulevard+-+Europa #Film+&amp;+TV+-+Serien #Film+&amp;+TV+-+Reality+&amp;+Casting #Film+&amp;+TV+-+Dramen #Film+&amp;+TV+-+Aktuell #Film+&amp;+TV+-+Dokumentationen #Film+&amp;+TV+-+Komödien #Boulevard+-+Deutschland #Boulevard+-+International #Musik+-+Aktuell #Buch+-+Biografien #Gewinnspiel" frss:cssFullContent=".content" frss:cssFullContentFilter=".leistenbanner, .artikelextrakopf, #zaehler, .noprint, .megabuttons"/>
</body>
</opml>
```

Either `.content` or `.artikel` should retrieve the full article content but they don't

**Comment by Alkarex** [comment] 2024-12-10 13:07
@Tywele Due to https://github.com/FreshRSS/FreshRSS/pull/7073, which now sanitizes the content first, the syntax to match classes should be `div[data-sanitized-class~="artikel"]`

Try something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml xmlns:frss="https://freshrss.org/opml" version="2.0">
	<head>
		<title>FreshRSS</title>
		<dateCreated>Tue, 10 Dec 2024 14:02:03 +0100</dateCreated>
	</head>
	<body>
		<outline text="Queer.de - Das Magazin für die LGBTI-Community" type="rss"
			xmlUrl="https://www.queer.de/rss/newsticker2.0.komplett.xml"
			htmlUrl="https://www.queer.de/"
			frss:filtersActionRead="#Kunst+&amp;amp;+Kultur+-+Ausstellungen&#10;#Life+&amp;amp;+Style+-+Body+&amp;amp;+Fashion&#10;#Buch+-+Sachbücher&#10;#Buch+-+Hörbücher&#10;#Buch+-+Literatur&#10;#Szene+-+Deutschland&#10;intitle:Jobs:&#10;#Kunst+&amp;amp;+Kultur+-+Bühne&#10;#Boulevard+-+Europa&#10;#Film+&amp;amp;+TV+-+Serien&#10;#Film+&amp;amp;+TV+-+Reality+&amp;amp;+Casting&#10;#Film+&amp;amp;+TV+-+Dramen&#10;#Film+&amp;amp;+TV+-+Aktuell&#10;#Film+&amp;amp;+TV+-+Dokumentationen&#10;#Film+&amp;amp;+TV+-+Komödien&#10;#Boulevard+-+Deutschland&#10;#Boulevard+-+International&#10;#Musik+-+Aktuell&#10;#Buch+-+Biografien&#10;#Gewinnspiel"
			frss:cssFullContent="div[data-sanitized-class~=&quot;artikel&quot;]&gt;p, div[data-sanitized-class~=&quot;artikel&quot;]&gt;blockquote, div[data-sanitized-class~=&quot;bildkasten&quot;]"
			frss:cssFullContentFilter="p[data-sanitized-class=&quot;leistenbanner&quot;]"/>
	</body>
</opml>
```

**Comment by Tywele** [comment] 2024-12-10 13:09
So I have to rewrite all my CSS selectors for all my feeds?! I thought both methods are now possible.

**Comment by Alkarex** [comment] 2024-12-10 13:14
We could maybe think of a compatibility approach to allow the simpler syntax

**Comment by Tywele** [comment] 2024-12-10 13:15
Also with the new syntax Umlauts are not properly retrieved
![grafik](https://github.com/user-attachments/assets/3be4826e-01ec-4885-a3a9-12a056fe9cfc)

Edit: I saw you apparently fixed that already

**Comment by Tywele** [comment] 2024-12-10 13:16
> We could maybe think of a compatibility approach to allow the simpler syntax

It's especially confusing since the hint below the input fields still suggest both methods are possible 
![grafik](https://github.com/user-attachments/assets/0b47f649-a5cc-43fe-847f-4c461b42ef80)

And the `data-sanitized-class` syntax is making everything hard to read in the field. Not to mention breaking every config from before.

**Comment by Alkarex** [comment] 2024-12-10 13:21
> Also with the new syntax Umlauts are not properly retrieved

This is supposed to be already fixed in https://github.com/FreshRSS/FreshRSS/pull/7081

**Comment by Tywele** [comment] 2024-12-10 13:23
I just saw. My installation only updates once a day automatically.

**Comment by Alkarex** [comment] 2024-12-10 13:50
> It's especially confusing since the hint below the input fields still suggest both methods are possible

Help message fixed in https://github.com/FreshRSS/FreshRSS/pull/7082

The dots were never meant to be used there. But let's come back to trying to support selectors such as `.menu`. Could you please open a new issue for that?

**Comment by Tywele** [comment] 2024-12-10 14:02
#7084 I opened an issue
