### ISSUE TITLE
[BUG] create user seems to be broken

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#4386] opened 2022-05-23 05:02 UTC
**Describe the bug**

When adding a user to my FreshRSS instance the webbrowser goes to an endless loop.

**To Reproduce**

1. Go to 'Manage Users'
2. Add a username and a password
3. Click on create

**Expected behavior**

User should be created.

**Screenshots**

No screenshot for an endless loop, but look here for a cli error.

```
sudo -u www-data php create-user.php --user kevin --password xxx
FreshRSS creating user “kevin”…
PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /srv/www/freshrss.deimeke.ruhr/app/Models/FeedDAO.php:311
Stack trace:
#0 /srv/www/freshrss.deimeke.ruhr/app/Services/ImportService.php(59): FreshRSS_FeedDAO->listFeeds()
#1 /srv/www/freshrss.deimeke.ruhr/app/Services/ImportService.php(46): FreshRSS_Import_Service->addOpmlElements()
#2 /srv/www/freshrss.deimeke.ruhr/app/Controllers/importExportController.php(99): FreshRSS_Import_Service->importOpml()
#3 /srv/www/freshrss.deimeke.ruhr/app/Controllers/userController.php(260): FreshRSS_importExport_Controller->importFile()
#4 /srv/www/freshrss.deimeke.ruhr/cli/create-user.php(24): FreshRSS_user_Controller::createUser()
#5 {main}
  thrown in /srv/www/freshrss.deimeke.ruhr/app/Models/FeedDAO.php on line 311

```

**Environment information (please complete the following information):**

- OS: Ubuntu 20.04
- FreshRSS version: most recent git version
- Database version: MariaDB 10.3.34
- PHP version: PHP 7.4.3
- Installation type: Git

**Additional context**

- empty -

**Comment by Alkarex** [comment] 2022-05-23 08:43
Thanks for the bug report. Fixed in https://github.com/FreshRSS/FreshRSS/pull/4387
Tests welcome.
Regression due to https://github.com/FreshRSS/FreshRSS/pull/4347

**Comment by Alkarex** [comment] 2022-05-23 08:46
Merged in our edge branch. Tests welcome

**Closed as completed** 2022-05-23 08:45 UTC
Labels: Important :fire:

**Comment by ddeimeke** [comment] 2022-05-23 08:49
Works for me! Thank you @Alkarex

**Comment by Alkarex** [comment] 2022-05-23 08:50
Thanks for the feedback!
