### ISSUE TITLE
`&amp;` gets converted to `FULLWIDTH AMPERSAND`

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#2966] opened 2020-05-11 20:15 UTC
I was scrolling through my feeds an noticed, that one entry hat a very weird & sign:
"Balloninternet: Project Loon kooperiert mit AT＆T"

This &-sign is a "FULLWIDTH AMPERSAND" and in hex is`0xef 0xbc 0x86`.

The original article had an html `&amp;`. In my oppinion this html ampersand should be converted to a normal ascii char and not a unicode one.

Currently i am using "Fira Sans" as font which displays the "FULLWIDTH AMPERSAND" very ugly. Thats why I noticed that.

**Comment by Frenzie** [comment] 2020-05-11 21:36
Duplicate of #2770.

**Comment by Alkarex** [comment] 2020-05-11 21:39
Yes, this is unfortunately the best option I have found to least problematic option I have found to be compatible with most clients https://github.com/FreshRSS/FreshRSS/issues/2770#issuecomment-575208803
Indeed, for some fields, it was not clear whether the content should be HTML-encoded or not, and clients therefore sometime perform HTML-decoding, sometimes not.

**Closed as completed by Alkarex** 2020-05-11 21:39 UTC
