### ISSUE TITLE
[Bug] Adding feeds is broken (MariaDB / MySQL)

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6897] opened 2024-10-15 12:14 UTC
### Describe the bug

I cannot add a feed anymore.

I tried to add https://mastodon.social/tags/freshrss.rss but got this success (!!) and error message
![grafik](https://github.com/user-attachments/assets/26abef2b-2dd2-4a81-b8c3-2967a1a67a96)

No log messages

### To Reproduce

1. add https://mastodon.social/tags/freshrss.rss
2. see error message

### Expected behavior

the feed is imported

### FreshRSS version

1.23.3-dev (latest)

### Environment information

- Database version: Mysql 5.7
- PHP version: PHP 8.1
- Installation type: self hosted
-Web server type: Apache

### Additional context

it works on demo.freshrss.org (it is not the latest 1.23.3-dev)

**Comment by Frenzie** [comment] 2024-10-15 12:54
Confirmed. (I thought the report said it was that specific feed but it's all feeds.)

**Comment by Alkarex** [comment] 2024-10-15 13:36
Hum, I cannot immediately reproduce any error.
@Frenzie are you also with MySQL?

@math-GH Any other errors in the logs?

**Comment by Frenzie** [comment] 2024-10-15 13:40
MariaDB 10.1.48, yes.

**Comment by Frenzie** [comment] 2024-10-15 13:43
No errors in the logs.

**Comment by Alkarex** [comment] 2024-10-15 14:04
Ok, I can reproduce with MariaDB (not with SQLite nor PostgreSQL)

**Comment by Alkarex** [comment] 2024-10-15 14:08
Seems to be a regression due to https://github.com/FreshRSS/FreshRSS/pull/4487

**Comment by Alkarex** [comment] 2024-10-15 14:16
Ah, and only with PHP 8.1 apparently - I cannot reproduce any problem with PHP 8.2

**Comment by WillPresley** [comment] 2024-10-15 14:26
> Ah, and only with PHP 8.1 apparently - I cannot reproduce any problem with PHP 8.2

For what it's worth, I am having the same issue with PHP 8.3.12 on Debian 12.7

**Comment by Alkarex** [comment] 2024-10-15 14:29
Thanks @WillPresley ; with which DB?

**Comment by WillPresley** [comment] 2024-10-15 14:32
> Thanks @WillPresley ; with which DB?

MySQL v8.0.40

**Comment by Frenzie** [comment] 2024-10-15 14:32
Forgot to say, PHP 8.1.6, but given the above that seems much less relevant than MariaDB/MySQL. ^_^

**Comment by Alkarex** [comment] 2024-10-15 14:53
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/6900
Tests welcome

**Comment by WillPresley** [comment] 2024-10-15 15:12
> Should be fixed with #6900 Tests welcome

Pulled down the PR and adding a feed is back to working again for me! PHP 8.3.12/MySQL 8.0.20/Debian 12.7

**Comment by Alkarex** [comment] 2024-10-15 15:15
Excellent, thanks for the feedback 👍🏻

**Closed as completed** 2024-10-15 15:14 UTC
Labels: Critical :skull_and_crossbones:, Bug (confirmed) 🐞

**Comment by Frenzie** [comment] 2024-10-15 17:03
Confirmed working here as well. :+1:
