### ISSUE TITLE
[Bug] Some User Query searches in mark-as-read not being marked as read

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6949] opened 2024-10-27 23:09 UTC
### Describe the bug

Sometime between 24a4fcb5c3a001ee9810d7140f107160472fc1d5 (merge of https://github.com/FreshRSS/FreshRSS/pull/6886) and 6c58b90518c30a165db1ee8ea34e0f3d12c6c898 (merge of https://github.com/FreshRSS/FreshRSS/pull/6936), `search:` being used as part of per-feed mark-as-read stopped working consistently.

After updating and converting all escaped parentheses in all regex patterns to be unescaped (for the relevant PR), some, but not all, of the `search:` are not being applied from the per-feed mark-as-read.  This is verifiable as a mark-as-read bug because a few days later the exact mark-as-read pattern can be copy-pasted into the manual search box for the feed and unread entries published after the update are found matching the pattern (SQLite backend is used so the syntax is the same, and every line of the mark-as-read feed is manually ended with ` OR` specifically so it can be easily copy-pasted).   

This can be narrowed down to a few specific User Queries, but there appears to be nothing unique about the patterns that work vs the ones that don't.

Patterns that work properly list no unread Entries in the manual search but do list read Entries.  Patterns that don't work list unread Entries in the manual search.  

### To Reproduce

1. Define some User Queries to match a common set of terms
2. List `search:` for those User Queries in the per-feed mark-as-read
3. As a matter of convenience end every line in the mark-as-read with ` OR` so it can by copy-pasted into the manual search box to run the equivalent.
4. Note the date and time the mark-as-read was updated for the feed
5. Wait a few days
6. Copy the mark-as-read filter pattern for the feed
7. Open the manual search for just unread entries on the one feed
8. Paste in the mark-as-read filter pattern
9. Notice there are a number of unread entries matching the mark-as-read pattern that have been added since the mark-as-read pattern was updated (error)

### Expected behavior

The pattern in the per-feed mark-as-read marks the matching entries as read.  Copy-pasting the mark-as-read filter to the manual search of the feed should find no new unread entries from after the mark-as-read filter was updated. 

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: SQLite
- PHP version: 8.3.10
- Installation type: Docker
- Web server type: whatever is built into the Alpine Dockerfile.
- Device: PC or Android Pixel Fold
- OS: N/A (OpenSUSE MicroOS)
- Browser: Firefox 131.0.2

### Additional context

Some of the `search:` seem to work and others don't.  I can't see anything unique between the ones that do and don't work.

Notably, the exact copy-paste of the mark-as-read filter into the manual search is finding unread entries in the feed that were posted well after the mark-as-read filter was setup (days later in fact).

Here's the full mark-as-read pattern for one of the feeds having a problem:
```
search:'Meets Visit' OR
search:'Art' OR
search:'Death' OR
search:'Entertainment' OR
search:'In Review' OR
search:'History' OR
search:'Interview' OR
search:'Opinion' OR
search:'Podcast' OR
search:'Sports' OR
search:'Timeline' OR
search:'You' OR
search:'Financial' OR
search:'Common AP'
```
Of these, the following are actually marking entries as read:
```
search:'Meets Visit' OR
search:'Death' OR
search:'Entertainment' OR
search:'In Review' OR
search:'Interview' OR
search:'Opinion' OR
search:'Podcast' OR
search:'Timeline' OR
search:'You' OR
search:'Common AP'
```
While these are not:
```
search:'Art OR
search:'History' OR
search:'Sports' OR
search:'Financial' OR
```
---

The patterns that aren't working to mark as read, but do work when used directly are:
`search:'Art'`:
```
intitle:/(?<!\b(to) )(?<!\b(for|the) )(?<!\b(help) )\bart(ist(s|ic))\b/i OR #/\bart(ist(s|ic)?|s)?\b/i OR intitle:'AP Photos' OR intitle:'photo collection' OR intitle:'photos of the week' OR intitle:'photo book' OR intitle:'photos:' OR #/(?<!vis-)photo(s|graph)/i OR intitle:/\bin pictures\b/i OR intitle:/^In Images\b/i OR inurl:/\/arts?\//i
```

`search:'History'`:
```
intitle:/today in history/i OR intitle:/\bon this day\b/i OR intitle:/\byears? on\b/i OR intitle:/\byear in review\b/i OR intitle:/\breview of the year\b/i
```

`search:'Sports'`:
```
( intitle:/\b(N[.]?(F|H)[.]?L[.]?|N[.]?B[.]?A[.]?|M[.]?L[.]?B[.]?|N[.]?C[.]?A[.]?A[.]?)\b(?! legend )/i !intitle:/\b(judge|case|indicted|indictment)\b/i ) OR intitle:/(Europa|Premier) League/i OR inurl:'/sports/' OR #/\bsports?\b/i OR #/(Europa|Premier) League/i OR inurl:'/soccer/' OR inurl:'/football/' OR inurl:'/baseball/' OR inurl:'/tennis/' OR inurl:'/golf/' OR #soccer OR #football OR #baseball OR #tennis OR #golf
```

`search:'Financial'`:
```
intitle:/\b(board|chairman) of\b/i OR  intitle:/\bequity\b/i OR intitle:/\b(financ(e|ial)s?|quarters?|stocks?|bonds?|markets|futures)\b/i OR  intitle:/\b(stock|bond) market\b/i OR  #finance OR #financial OR #stock OR #bond OR #market OR #futures OR  intitle:/(first|second|third|fourth) quarters?/i OR  intitle:/\bfunding round\b/i OR  intitle:/\b(net|gross) sales/i OR  intitle:/\b(revenue|stake|valuation|valued at)\b/i OR  intitle:/\bseries [A-Z]\b/i OR  intitle:/\b(up|down|rise(s| of)|falls?) [0-9]+%/i OR  intitle:/\byear (over|on) year\b/i OR  intitle:/\bYoY\b/i OR  intitle:/\by\/y\b/i OR  intitle:/\bIPO\b/ OR  intitle:/[$€£][0-9.]+( per |\/)share\b/i OR  intitle:/\bstock buyback\b/i OR  intitle:/([$€£]|&pound;)[0-9.]+(M|B)? ((funding|series) )?round\b/i OR intitle:/\bunion/i OR #/\bunion/i
```

---

These are the patterns that are working:  
`search:'Meets Visit'`:
```
intitle:/\bme(t|ets)\b/i OR intitle:/\b(to|will) meet\b/i OR intitle:/\bvisit(s|ed)\b/i OR intitle:/\b(to|will) visit\b/i  OR intitle:/\barrives (in|at)\b/i OR  intitle:/\bwill arrive (in|at)\b/i OR intitle:/\b will head to\b/i OR intitle:/\bhead(s|ed) to\b/i
````

`search:'Death'`:
```
intitle:/\bdies($| at\b)/i or intitle:/\bdead at\b/i OR #/obituar(y|ies)/i OR #/^deaths$/i OR intitle:/\btribute to\b/i OR intitle:/remember(ed|ing)/i OR intitle:/\bRequiem\b/i OR #/\brequiem\b/i
```

`search:'Entertainment'`:
```
#/\bmovies\b/i OR #/\bentertainment\b/i OR inurl:'/style/' OR inurl:'/books/' OR inurl:'/theater/' OR inurl:'/television/' OR inurl:'/movies/'
```

`search:'In Review'`:
```
intitle:/\bago today\b/i OR intitle:/(decades?|years?|months?|quarters?) (ago|past)/i OR ( intitle:/([0-9]+|reviewing|remembering) (decades?|years?|months?|quarters?)/i !intitle:/\b(given|sentenced|condemned)\b/i ) OR intitle:/\b(on|from) 20[0-2][0-9]/i OR intitle:/\bin review\b/i OR intitle:/\bremember(s|ed|ing)\b/i OR intitle:/\breview (of )?the (month|year|week)/i OR intitle:/(^|\bon )this (day|week|month)\b/i
```

`search:'Interview'`:
```
intitle:/^Meet\b/i OR intitle:/\bopens up about\b/i OR ( intitle:/\b([A-Z][a-z]+ ){2}(?i)(explains|discusses|jokes|chats)\b/ !intitle:/\b(judge|courts?|justice|client|president|prime minister)\b/i ) OR intitle:/\bchat about\b/i
```

`search:'Opinion'`:
```
inurl:/\/opinions?\//i OR #opinion OR intitle:/\bopinion\b/i
```

`search:'Podcast'`:
```
inurl:/\/podcast(s|er)?\//i OR #podcast OR intitle:/\bpodcast(s|er)\b/i
```

`search:'Timeline'`:
```
intitle:/\btimeline\b/i
```

`search:'You'`:
```
intitle:/\byour?\b(?!(.*?((\W['"])|(["'](\W|$)))))/i
```

`search:'Common AP'`:
```
intitle:'What We Know' OR  intitle:/[?]/ OR  intitle:/^Takeaways from\b/i OR  #lifestyle OR  intitle:/^A look at\b/i OR  intitle:/\bExplainer\b/i OR intitle:/^(this|these)\b/i OR  intitle:/^(who|what|why|how)\b/i OR intitle:/^stock market today:/i OR intitle:/\bthings to know about\b/i OR intitle:/AP Decision Notes: what to expect in\b/i
```

**Comment by mtalexan** [comment] 2024-10-27 23:25
I've verified that patterns that aren't included indirectly via `search:` are always working fine in the per-feed mark-as-ready. It's exclusively patterns included via `search:` that have issues.  

It's also restricted to only certain `search:`.  The ones that work, do so consistently across all per-feed mark-as-read patterns, while the ones that don't are also consistently not working across all per-feed mark-as-read patterns they're used in.

---

Another pattern that's not working (from a different feed):
`search:'Spam'`:
```
intitle:/[0-9]+ (things|tips)\b/i OR intitle:/\b(deals|sale|save|discount)\b/i OR intitle:/\bfor a limited time/i OR  ( intitle:/\b(to|only|at|for) ([$][0-9]+|[0-9]+%)/i !intitle:/\btotal to\b/i ) OR intitle:/([$][0-9]+|[0-9]+%) (off|discount)\b/i OR intitle:/\bvs[.]?\b/i OR intitle:/\bbest\b.*\bvpn\b/i OR intitle:/\bbuy right now\b/i OR #discount OR #sale OR #sponsor OR #endorse OR #save OR #deal OR intitle:/\b(discounted|down|save|reduced) [0-9]%/i OR intitle:/\bright now\b/i OR intitle:/^(the )?best\b/i OR intitle:/\btips\b/i OR intitle:/\btop picks\b/i OR intitle:/^best\b(?! buy\b)/i OR intitle:/\bneed to know\b/i OR intitle:/\b(low(er|est|ed)|discounted|reduced|for (only)?|at|as little as|down to) [$][0-9]+/i
```

**Comment by Alkarex** [comment] 2024-10-28 22:17
> While these are not:
> 
> ```
> search:'Art OR
> search:'History' OR
> search:'Sports' OR
> search:'Financial' OR
> ```

Missing closing single quote after *Art*. Related?

**Comment by Alkarex** [comment] 2024-10-28 22:48
Could you please test https://github.com/FreshRSS/FreshRSS/pull/6950 ?

**Comment by mtalexan** [comment] 2024-10-29 02:55
> > While these are not:
> > ```
> > search:'Art OR
> > search:'History' OR
> > search:'Sports' OR
> > search:'Financial' OR
> > ```
> 
> Missing closing single quote after _Art_. Related?

Copy paste error when I was posting this. The first list is the direct copy paste, but that list with the typo was from when I was going thru one by one to see which ones found unread results even though they were in the full mark-as-read list.

**Closed as completed** 2024-10-29 07:12 UTC
Labels: Search :mag:, Bug (unconfirmed)

**Comment by mtalexan** [comment] 2024-10-29 12:49
#6950 didn't fix it. After updating to it last night, and marking everything read, this morning I had new articles added that match one of the filters but weren't marked as read.

**Comment by mtalexan** [comment] 2024-10-29 13:13
Ah ha! It looks like it might be a bug in article updates.

I happened to notice that some of the article states we're out of order in the full read+unread list for one of the feeds having problems. I checked, and my "mark unread on update" setting for the feed is set to "default" and my global setting is unchecked. But I purged the feed anyway and then re-fetched it. 
After the refetch, the articles that weren't being marked as read before are now not present at all, and all articles are in chronological order. That suggests to me that articles updates in newly loaded feeds are ignored, but also that the "mark updates as unread" isn't working properly and is always acting as "true"

**Comment by Alkarex** [comment] 2024-10-29 22:35
@mtalexan I am not sure to understand the explanation of the problem. You are referring to the option *Mark updated articles as unread*, right? I have just tested it without problem. Maybe it is a misunderstanding: this option marks as unread the articles which content has changed after they were marked as read by the user.

**Comment by mtalexan** [comment] 2024-10-29 23:29
> @mtalexan I am not sure to understand the explanation of the problem. You are referring to the option _Mark updated articles as unread_, right? I have just tested it without problem. Maybe it is a misunderstanding: this option marks as unread the articles which content has changed after they were marked as read by the user.

I'm kind of guessing at this point. I'm running your PR branch, but copy-pasting exactly what I have in the mark-as-read filter for a feed is showing things that aren't marked as read even though I had everything marked as read in all feeds when I switched to your PR.  
I noticed this morning, after updating last night to your PR (and marking everything in all feeds as read), that the dates on unread articles in a single feed were out of order and some included dates from multiple days ago. One of those articles that was very out of order was one that matched the mark-as-read filter and shouldn't have made it into the unread list.
I'm guessing the dates listed on the articles are the original published dates, but they end up sorted in the per-feed view based on when they were downloaded/updated.  

Since the dates were weird in the article list of the feed, I went into the feed settings and purged all articles, then manually refreshed it. The articles listed were properly filtered then and all in order.
A couple hours later however, one of the articles that was automatically marked as read right after the purge and reload had re-appeared as unread despite matching one of the mark-as-read filters.

And it's that's the setting I was referring to. It's set as "default" in the feed settings, and unchecked (off) in the global settings.

**Comment by mtalexan** [comment] 2024-10-29 23:34
Oh yeah, and the article that re-appeared as unread: I looked back thru all the read and unread articles in the feed and it had jumped to much higher in the list and was no longer where it used to be.

**Comment by Alkarex** [comment] 2024-10-30 10:16
> A couple hours later however, one of the articles that was automatically marked as read right after the purge and reload had re-appeared as unread despite matching one of the mark-as-read filters.

I am guessing this might be a sign of two distinct problems:
1. A problem with the feed (see https://github.com/FreshRSS/FreshRSS/discussions/6101). In particular, can you find another copy of the same article?
    * What are the unicity criteria settings for that feed?
2. A filter that is not working

Would you be able to share a minimal example of feed URL + filter, which are not working as intended?

**Comment by mtalexan** [comment] 2024-10-31 01:37
I just cloned my "production" instance to a "test" instance and removed all but 4 of the feeds from the test instance.  I also stripped down the mark-as-read filters to just a single `search:` pattern on each of the feeds, and manually marked everything as read.

The specific feed I was looking at before is one via a private RSS-hub instance so it's not something I can easily share directly.  I'm keeping that feed, a feed that's via feedburner, and a feed direct from a site, all that have been having issues.  I'll check back in the morning to see what's failed to be marked as read properly so I can narrow it down better.

**Comment by mtalexan** [comment] 2024-10-31 01:40
> A problem with the feed (see https://github.com/FreshRSS/FreshRSS/discussions/6101). In particular, can you find another copy of the same article?

No, I don't see any duplicate articles in the full feed list when I look thru.

> What are the unicity criteria settings for that feed?

All of them are set to "Standard ID (default)", I haven't touched them.

**Comment by mtalexan** [comment] 2024-10-31 01:46
From https://github.com/FreshRSS/FreshRSS/discussions/6101, it seems like none of those should affect whether the mark-as-read filter gets applied or not.  If there are problems with duplicate IDs, re-published IDs, or old articles being published, I would think either the prior state (read) would get used or the mark-as-read filters would be applied to the duplicate.  Getting articles marked as read when they shouldn't be seems like the more likely problem.

**Comment by mtalexan** [comment] 2024-11-01 18:20
Ok, I have a working example I can share directly, and it's weirder than I thought.

A User query named "Art" contains: 
```
intitle:/(?<!\b(to) )(?<!\b(for|the) )(?<!\b(help) )\bart(ist(s|ic))\b/i OR #/\bart(ist(s|ic)?|s)?\b/i OR intitle:'AP Photos' OR intitle:'photo collection' OR intitle:'photos of the week' OR intitle:'photo book' OR intitle:'photos:' OR #/(?<!vis-)photo(s|graph)/i OR intitle:/\bin pictures\b/i OR intitle:/^In Images\b/i OR inurl:/\/arts?\//i
```

A feed from RSS-Hub's public instance:  
https://rss-bridge.org/bridge01/?action=display&bridge=AssociatedPressNewsBridge&context=Standard+Topics&topic=apf-topnews&format=Atom

All default values are left alone, except add a single mark-as-read filter:
```
search:'Art'
```

If you wait a day or so, you'll see articles coming in that match the Art filter, especially articles that start with "PHOTO COLLECTION:".  These articles aren't being marked as read like the mark-as-read filter instructs, and you can find them in the unread list by doing a manual search with the term `search:'Art'` (just like it appears in the per-feed mark-as-read filter).  

If you look at both the read and unread things in the feed matching that manual search, you'll see that some things are being matched marked as read, but others aren't.  

---

I also had a test where I didn't involve the User Query.  I just had the content of that query directly in the per-feed mark-as-read filter.  It has identical results.  So it appears the `search:` usage isn't to blame, but something else is going on.  I can file this as a different bug.

**Comment by Alkarex** [comment] 2024-11-02 00:01
I believe the bug was in regex searches for tags when using parentheses. Fixed in https://github.com/FreshRSS/FreshRSS/pull/6972
Please try again
