### ISSUE TITLE
Link to the current page in issue header.

### ISSUE THREAD

**Issue by petesimonic** [FreshRSS/FreshRSS#3281] opened 2020-12-23 09:49 UTC
Hello! One of the feeds demonstrate strange behaviour. Usually header of selected from list issue links to the site from which it were taken. But this feed links to address of the page where this issue is opened (i.e. to the FreshRSS instance itself). More than that the feed have tons of duplications: around 50 for each issue. And the feed itself comes from RSS-bridged Fb page (but other pages doesn't show similar problems).

**Comment by Frenzie** [comment] 2020-12-23 10:25
Without sharing (part of) the feed's XML it's a little hard to comment. I imagine the permalink will be empty or otherwise broken, which is presumably technically invalid but also might something we could deal with slightly better.

**Comment by petesimonic** [comment] 2020-12-23 10:45
So-o, maybe it will be redirected to RSS-bridge. =)

Could you instruct me what info would you like to have. And I will be 
providing it according to abilities.

Thank you! )

**Comment by Frenzie** [comment] 2020-12-23 11:48
The feed itself, in this case it probably looks like this. The link is empty in FreshRSS and therefore refers to the page it's on.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

	<title type="text"></title>
	<id>https://[SNIP]/rss-bridge/?action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat</id>
	<icon>https://github.com/favicon.ico</icon>
	<logo>https://github.com/favicon.ico</logo>
	<updated>2020-12-23T11:43:47+00:00</updated>
	<author>
		<name>RSS-Bridge</name>
	</author>
	<link rel="alternate" type="text/html" href="https://github.com/RSS-Bridge/rss-bridge/" />
	<link rel="self" type="application/atom+xml" href="https://[SNIP]/rss-bridge/?action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat" />

	<entry>
		<title type="html">Bridge encountered an unexpected situation! (18619)</title>
		<published>2020-12-23T11:43:47+00:00</published>
		<updated>2020-12-23T11:43:47+00:00</updated>
		<id>urn:sha1:7fde4d0ce0bbc1c1e9c6fa826d21cd50af066cc5</id>
		
		
		<content type="html">&lt;section&gt;
	&lt;p class="exception-message"&gt;&lt;strong&gt;Facebook Bridge&lt;/strong&gt; was unable to receive or process the
remote website's content!&lt;br&gt;
Error message: `Call to a member function children() on null`&lt;br /&gt;
Query string: `action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat`&lt;br /&gt;
Version: `git.master.73f4bc0`&lt;/p&gt;
	&lt;div class="advice"&gt;
		&lt;ul class="advice"&gt;
			&lt;li&gt;Press Return to check your input parameters&lt;/li&gt;
			&lt;li&gt;Press F5 to retry&lt;/li&gt;
			&lt;li&gt;Check if this issue was already reported on &lt;a href="https://github.com/RSS-Bridge/rss-bridge/issues?q=is%3Aissue+is%3Aopen+Facebook+Bridge"&gt;GitHub&lt;/a&gt; (give it a thumbs-up)&lt;/li&gt;
			&lt;li&gt;Open a &lt;a href="https://github.com/RSS-Bridge/rss-bridge/issues/new?title=Facebook+Bridge+failed+with+error+0&amp;body=Error+message%3A+%60Call+to+a+member+function+children%28%29+on+null%60%0AQuery+string%3A+%60action%3Ddisplay%26bridge%3DFacebookBridge%26u%3DParlezvousFrench%26format%3DAtomFormat%60%0AVersion%3A+%60git.master.73f4bc0%60&amp;labels=Bridge-Broken&amp;assignee=teromene%2C+logmanoriginal"&gt;GitHub Issue&lt;/a&gt; if this error persists&lt;/li&gt;
		&lt;/ul&gt;
	&lt;/div&gt;
	&lt;a href="https://github.com/RSS-Bridge/rss-bridge/issues?q=is%3Aissue+is%3Aopen+Facebook+Bridge" title="Opens GitHub to search for similar issues"&gt;
		&lt;button&gt;Search GitHub Issues&lt;/button&gt;
	&lt;/a&gt;
	&lt;a href="https://github.com/RSS-Bridge/rss-bridge/issues/new?title=Facebook+Bridge+failed+with+error+0&amp;body=Error+message%3A+%60Call+to+a+member+function+children%28%29+on+null%60%0AQuery+string%3A+%60action%3Ddisplay%26bridge%3DFacebookBridge%26u%3DParlezvousFrench%26format%3DAtomFormat%60%0AVersion%3A+%60git.master.73f4bc0%60&amp;labels=Bridge-Broken&amp;assignee=teromene%2C+logmanoriginal" title="After clicking this button you can review
	the issue before submitting it"&gt;&lt;button&gt;Open GitHub Issue&lt;/button&gt;&lt;/a&gt;
	&lt;p class="maintainer"&gt;teromene, logmanoriginal&lt;/p&gt;
&lt;/section&gt;</content>
		
		
	</entry>

</feed>
```

**Comment by petesimonic** [comment] 2020-12-23 11:54
Will the address help? https://apps.sophy.life/rss-bridge/?action=display&bridge=Facebook&context=Group&g=135687967131230&limit=-1&format=Mrss

On December 23, 2020 2:48:54 PM GMT+03:00, Frans de Jonge <notifications@github.com> wrote:
>The feed itself, in this case it probably looks like this. The link is
>empty in FreshRSS and therefore refers to the page it's on.
>```xml
><?xml version="1.0" encoding="UTF-8"?>
><feed xmlns="http://www.w3.org/2005/Atom">
>
>	<title type="text"></title>
>	<id>https://[SNIP]/rss-bridge/?action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat</id>
>	<icon>https://github.com/favicon.ico</icon>
>	<logo>https://github.com/favicon.ico</logo>
>	<updated>2020-12-23T11:43:47+00:00</updated>
>	<author>
>		<name>RSS-Bridge</name>
>	</author>
>	<link rel="alternate" type="text/html"
>href="https://github.com/RSS-Bridge/rss-bridge/" />
>	<link rel="self" type="application/atom+xml"
>href="https://[SNIP]/rss-bridge/?action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat"
>/>
>
>	<entry>
>		<title type="html">Bridge encountered an unexpected situation!
>(18619)</title>
>		<published>2020-12-23T11:43:47+00:00</published>
>		<updated>2020-12-23T11:43:47+00:00</updated>
>		<id>urn:sha1:7fde4d0ce0bbc1c1e9c6fa826d21cd50af066cc5</id>
>		
>		
>		<content type="html">&lt;section&gt;
>	&lt;p class="exception-message"&gt;&lt;strong&gt;Facebook
>Bridge&lt;/strong&gt; was unable to receive or process the
>remote website's content!&lt;br&gt;
>Error message: `Call to a member function children() on null`&lt;br
>/&gt;
>Query string:
>`action=display&amp;bridge=FacebookBridge&amp;u=ParlezvousFrench&amp;format=AtomFormat`&lt;br
>/&gt;
>Version: `git.master.73f4bc0`&lt;/p&gt;
>	&lt;div class="advice"&gt;
>		&lt;ul class="advice"&gt;
>			&lt;li&gt;Press Return to check your input parameters&lt;/li&gt;
>			&lt;li&gt;Press F5 to retry&lt;/li&gt;
>			&lt;li&gt;Check if this issue was already reported on &lt;a
>href="https://github.com/RSS-Bridge/rss-bridge/issues?q=is%3Aissue+is%3Aopen+Facebook+Bridge"&gt;GitHub&lt;/a&gt;
>(give it a thumbs-up)&lt;/li&gt;
>			&lt;li&gt;Open a &lt;a
>href="https://github.com/RSS-Bridge/rss-bridge/issues/new?title=Facebook+Bridge+failed+with+error+0&amp;body=Error+message%3A+%60Call+to+a+member+function+children%28%29+on+null%60%0AQuery+string%3A+%60action%3Ddisplay%26bridge%3DFacebookBridge%26u%3DParlezvousFrench%26format%3DAtomFormat%60%0AVersion%3A+%60git.master.73f4bc0%60&amp;labels=Bridge-Broken&amp;assignee=teromene%2C+logmanoriginal"&gt;GitHub
>Issue&lt;/a&gt; if this error persists&lt;/li&gt;
>		&lt;/ul&gt;
>	&lt;/div&gt;
>	&lt;a
>href="https://github.com/RSS-Bridge/rss-bridge/issues?q=is%3Aissue+is%3Aopen+Facebook+Bridge"
>title="Opens GitHub to search for similar issues"&gt;
>		&lt;button&gt;Search GitHub Issues&lt;/button&gt;
>	&lt;/a&gt;
>	&lt;a
>href="https://github.com/RSS-Bridge/rss-bridge/issues/new?title=Facebook+Bridge+failed+with+error+0&amp;body=Error+message%3A+%60Call+to+a+member+function+children%28%29+on+null%60%0AQuery+string%3A+%60action%3Ddisplay%26bridge%3DFacebookBridge%26u%3DParlezvousFrench%26format%3DAtomFormat%60%0AVersion%3A+%60git.master.73f4bc0%60&amp;labels=Bridge-Broken&amp;assignee=teromene%2C+logmanoriginal"
>title="After clicking this button you can review
>	the issue before submitting it"&gt;&lt;button&gt;Open GitHub
>Issue&lt;/button&gt;&lt;/a&gt;
>	&lt;p class="maintainer"&gt;teromene, logmanoriginal&lt;/p&gt;
>&lt;/section&gt;</content>
>		
>		
>	</entry>
>
></feed>
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreshRSS/FreshRSS/issues/3281#issuecomment-750206431

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Frenzie** [comment] 2020-12-23 11:56
That one seems to work as intended?

**Comment by petesimonic** [comment] 2020-12-23 11:59
No, it's the one that generate tons of garbage and mislinks.

On December 23, 2020 2:56:41 PM GMT+03:00, Frans de Jonge <notifications@github.com> wrote:
>That one seems to work as intended?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreshRSS/FreshRSS/issues/3281#issuecomment-750218547

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Alkarex** [comment] 2020-12-28 12:44
At a quick glance, I cannot spot any problem on FreshRSS side. You can also try the *Atom* format from RSS Bridge

**Comment by petesimonic** [comment] 2020-12-29 07:18
Thanks for advice, I believe the source has been switched, let us watch
it's behaviour. (The switch was done as replacing the text in *feed URL*
field.)

Btw, what's the difference between these two? I always recommended RSS
over Atom just out of the naming ("it's not Fresh Atom").

**Comment by petesimonic** [comment] 2020-12-30 07:55
> Thanks for advice, I believe the source has been switched, let us watch it's behaviour. (The switch was done as replacing the text in *feed URL* field.)

Source switching didn't visibly affect behaviour. All the problems persists.

**Comment by Frenzie** [comment] 2020-12-30 09:34
> Btw, what's the difference between these two? I always recommended RSS
over Atom just out of the naming ("it's not Fresh Atom").

Atom has a few advantages, but in general it should make little difference.

**Comment by Alkarex** [comment] 2020-12-30 11:34
When it works in the Feed Validator, it should work in FreshRSS as well: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fapps.sophy.life%2Frss-bridge%2F%3Faction%3Ddisplay%26bridge%3DFacebook%26context%3DGroup%26g%3D135687967131230%26limit%3D-1%26format%3DMrss

You can also test with e.g. https://www.simplepie.org/demo/

It looks like the RSS Bridge script is not (always) functioning properly. Closing here, as I do not think it is related to FreshRSS.

**Closed as completed by Alkarex** 2020-12-30 11:34 UTC
Labels: Feed problem :newspaper_roll:
