### ISSUE TITLE
[Feature] Increasing the maximum length of item titles

### ISSUE THREAD

**Issue by Aasemoon** [FreshRSS/FreshRSS#4986] opened 2023-01-04 11:50 UTC
**Is your feature request related to a problem? Please describe.**
At the moment when the title of a feed item is longer than a certain length, it gets cut off.

**Describe the solution you’d like**
I'd like to know if there's a way to increase the maximum allowed length of an item title. Is this already somehow possible? Or would it have to be a new feature?

**Additional context**
Well, for instance within Tumblr feeds there's very often items with titles that get cut in the middle because they're too long. [They do of course show up fully in the feed source.]

**Comment by aledeg** [comment] 2023-01-04 12:38
I think it's a duplicate of #4338

**Comment by Aasemoon** [comment] 2023-01-04 13:45
@aledeg Sure I guess it can be the same issue.

**Comment by Frenzie** [comment] 2023-01-04 13:54
Agreed, a quick peek suggests the title column is `VARCHAR(255)` which seems like a reasonable enough choice but I suppose it could be larger.

**Comment by Alkarex** [comment] 2023-01-06 17:40
Let's continue in the other issue, which has some discussion https://github.com/FreshRSS/FreshRSS/issues/4338#issuecomment-1113040147
We might also decide the have different limits depending on the constraints of the underlying database (MySQL vs. PostgreSQL vs. SQLite)

**Comment by amayatsky** [comment] 2023-10-26 19:10
Well, the issue in the url length was resolved, but title length was forgotten :)
Any chance this will be re-opened or should I come back with a PR?

**Comment by Alkarex** [comment] 2023-10-26 21:50
> but title length was forgotten

For the record, the title limit goes all the way back to:

https://github.com/FreshRSS/FreshRSS/blob/8c2c5d287d5ac08aa9d0a3fb3d353ea7a18c92c3/public/install.php#L21

Contrarily to the URL limit which was due to an index limit, I do not believe there is anything special there

**Comment by Alkarex** [comment] 2023-10-26 22:53
https://github.com/FreshRSS/FreshRSS/pull/5756

**Closed as completed** 2023-10-30 19:47 UTC
Labels: Feature Request
