### ISSUE TITLE
iframe sanitizing bug with PHP 5.3.3

### ISSUE THREAD

**Issue by giorgiobeggiora** [FreshRSS/FreshRSS#1604] opened 2017-07-26 07:32 UTC
Is there a way to always show controls?
Sometime they are not visible, i think when there are just few news.
Thanks

**Comment by Alkarex** [comment] 2017-07-26 09:10
Hello @giorgiobeggiora 
Could you please upload a screenshot illustrating the problem?

**Comment by giorgiobeggiora** [comment] 2017-07-27 00:47
Here they are. Note: on the left of the 4th image the sidebar is repeated 2 times: that's an error of my screenshot software. However, the presence or absence of the controls reflect the reality in all of the screenshots.  Thanks.

![6017 daily freshrss](https://user-images.githubusercontent.com/9007227/28649516-c0f22a92-7275-11e7-9260-b2becfade9d6.jpg)
![39964 daily geek freshrss](https://user-images.githubusercontent.com/9007227/28649517-c11a1278-7275-11e7-84a7-79b044d0a018.jpg)
![78379 your rss feeds freshrss](https://user-images.githubusercontent.com/9007227/28649518-c148ed00-7275-11e7-8cab-c2242f7fddd0.jpg)
![78 378 your rss feeds freshrss](https://user-images.githubusercontent.com/9007227/28649520-c1834cd4-7275-11e7-832c-172d9f4d8fa2.jpg)
![526 dev game freshrss](https://user-images.githubusercontent.com/9007227/28649521-c188e928-7275-11e7-80e3-c28f92461087.jpg)
![1258 gdr freshrss](https://user-images.githubusercontent.com/9007227/28649522-c199aad8-7275-11e7-8478-a237e1b88c4c.jpg)

**Comment by giorgiobeggiora** [comment] 2017-07-27 14:53
the cause may be this javascript error (seems that it blocks the loading of many posts too)

<img width="831" alt="schermata 2017-07-27 alle 16 48 41" src="https://user-images.githubusercontent.com/9007227/28676695-987127aa-72eb-11e7-85f1-c28f70b250ea.png">

**Comment by Alkarex** [comment] 2017-07-27 18:36
Strange error you have there. What browser? Could you try with browser extensions disabled? Could you please try with a couple other browsers?

**Comment by giorgiobeggiora** [comment] 2017-07-28 02:21
With addons disabled, i tried with  last version of Chrome, Internet Explorer and Firefox: the error remains.

In firefox, the error message is:

TypeError: notification.find(...).html(...) is undefined

**Comment by aledeg** [comment] 2017-07-28 15:26
I have the same error sometimes. I've dig in the code and it seems that there is some entry contents that are interfering with the page tags.
Time to use a templating engine?

**Comment by Alkarex** [comment] 2017-07-28 16:49
@giorgiobeggiora @aledeg When you observe the problem, could you please send a full copy of the DOM (client-side page code)? For instance using the Firefox developer tools / inspect / copy outer HTML
![image](https://user-images.githubusercontent.com/1008324/28727518-64e3ea28-73c5-11e7-86da-de38ab3cb9fa.png)

**Comment by giorgiobeggiora** [comment] 2017-07-31 14:50
here it is, hope it helps
[freshrss-html-source.txt](https://github.com/FreshRSS/FreshRSS/files/1187902/freshrss-html-source.txt)

**Comment by Alkarex** [comment] 2017-07-31 14:55
Thanks. At a quick glance, it looks like an un-closed `iframe`. Do you use any FreshRSS extension? If not, it might be a sanitizing bug.

```html
<p>
  <iframe src="../themes/icons/grey.gif" data-original="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin">
&lt;/p&gt;
```

**Comment by Alkarex** [comment] 2017-07-31 14:59
Hum, I have just tried to register to http://www.ispazio.net/feed and I cannot reproduce the `iframe` bug. Have you made anything special for this feed, such as a rule to fetch all content?

**Comment by giorgiobeggiora** [comment] 2017-07-31 15:09
my feed url is http://feeds.feedburner.com/Ispazio and as feed option i just checked "show in main stream".

I attach some screenshots of the application settings

![schermata 2017-07-31 alle 17 05 46](https://user-images.githubusercontent.com/9007227/28784085-a50657e0-7612-11e7-9990-13ebc01b35d2.png)
![schermata 2017-07-31 alle 17 05 57](https://user-images.githubusercontent.com/9007227/28784086-a5069f98-7612-11e7-9faf-b1ad7a778080.png)

**Comment by giorgiobeggiora** [comment] 2017-07-31 15:26
the previous source code was copied using Chrome

now i'm attaching the same source but copied using Firefox, that doesn't contain "sanitized" code 

[freshrss-html-source-firefox.txt](https://github.com/FreshRSS/FreshRSS/files/1188000/freshrss-html-source-firefox.txt)

**Comment by giorgiobeggiora** [comment] 2017-07-31 15:27
PS: i'm not using any FreshRSS extension

**Comment by Alkarex** [comment] 2017-07-31 15:29
In the version from Firefox, was there an also an error?

**Comment by giorgiobeggiora** [comment] 2017-07-31 15:29
yes, it's always the same

**Comment by Alkarex** [comment] 2017-07-31 19:11
The original content in the RSS feed is:
```xml
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
```

but on your instance (cannot reproduce on mine), for some reason, the closing tag for iframe is gone:
```xml
<p><iframe src="../themes/icons/grey.gif" data-original="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin" height="480" frameborder="0" width="100%"></p>
```

Could you please tell a bit more about your system, server side? What version of FreshRSS and PHP, in particular?

**Comment by giorgiobeggiora** [comment] 2017-08-01 15:38
Some weeks ago i update from an old version to 1.7.0

I did about 5-6 updates in few minutes, then i got an error because i didn't know there was an error in the last update. So i fixed it as described in [#1577](https://github.com/FreshRSS/FreshRSS/issues/1577), then it worked.

Here is my server configuration (FreshRSS "Installation checking" page):

[Installation checking · FreshRSS.pdf](https://github.com/FreshRSS/FreshRSS/files/1191085/Installation.checking.FreshRSS.pdf)

**Comment by giorgiobeggiora** [comment] 2017-08-04 09:30
i see you added this issue to 1.8 milestone: does it mean you was able to reproduce the problem?

**Comment by Alkarex** [comment] 2017-08-04 15:48
@giorgiobeggiora I have not been able to reproduce the problem on my side, no, but is sounds like @aledeg has. I have a couple of ideas of where it might come from.

It could be something with XML sanitizing
https://github.com/simplepie/simplepie/blob/45c50e895f0657480c57069b25722dfebec1c8e0/library/SimplePie/Sanitize.php#L368-L375

Or maybe the lazy loading functionality https://github.com/FreshRSS/FreshRSS/blob/dd65cb0f9c85b261af6db85d0ea7c06b9e0bc6ec/lib/lib_rss.php#L264-L275

Could you please try to disable lazy loading in FreshRSS settings, and see whether it changes anything?

If it does not change anything, I will try to write a few tests.

**Comment by giorgiobeggiora** [comment] 2017-08-07 13:46
i unchecked _"Use "lazy load" mode to load pictures"_ but nothing changed

**Comment by Alkarex** [comment] 2017-08-07 13:47
Thanks for the feedback. I will try to prepare a few minimal tests to try to isolate the issue.

**Comment by Alkarex** [comment] 2017-08-14 21:04
@giorgiobeggiora Sorry for the delay. Here is a test. Could you please put it in your `./FreshRSS/p/i/` folder and run it? For instance with the name `iframe-test.php`. Either from command line or from your browser.

```php
<?php
header('Content-Type: text/plain; charset=UTF-8');
header('Content-Disposition: inline; filename="iframe-test.txt"');

require('../../constants.php');
require(LIB_PATH . '/lib_rss.php');

Minz_Configuration::register('system', DATA_PATH . '/config.php', FRESHRSS_PATH . '/config.default.php');
FreshRSS_Context::$system_conf = Minz_Configuration::get('system');

echo '<plaintext>', "\n";

$html1 = '<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>';
$html2 = '<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" /></p>';
$html3 = '<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></p>';

echo 'sanitizeHTML():', "\n";

echo 'sanitizeHTML 1: ', sanitizeHTML($html1), "\n";
echo 'sanitizeHTML 2: ', sanitizeHTML($html2), "\n";
echo 'sanitizeHTML 3: ', sanitizeHTML($html3), "\n";

echo "\n";

echo 'DOMDocument():', "\n";

$dom = new DOMDocument();
$dom->recover = true;
$dom->strictErrorChecking = false;

@$dom->loadHTML($html1);
echo 'HTML to XML 1: ', $dom->saveXML(), "\n";
echo 'HTML to HTML 1: ', $dom->saveHTML(), "\n";

@$dom->loadHTML($html2);
echo 'HTML to XML 2: ', $dom->saveXML(), "\n";
echo 'HTML to HTML 2: ', $dom->saveHTML(), "\n";

@$dom->loadHTML($html3);
echo 'HTML to XML 3: ', $dom->saveXML(), "\n";
echo 'HTML to HTML 3: ', $dom->saveHTML(), "\n";

@$dom->loadXML($html1);
echo 'XML to XML 1: ', $dom->saveXML(), "\n";
echo 'XML to HTML 1: ', $dom->saveHTML(), "\n";

@$dom->loadXML($html2);
echo 'XML to XML 2: ', $dom->saveXML(), "\n";
echo 'XML to HTML 2: ', $dom->saveHTML(), "\n";

@$dom->loadXML($html3);
echo 'XML to XML 3: ', $dom->saveXML(), "\n";
echo 'XML to HTML 3: ', $dom->saveHTML(), "\n";
```

Here is my output. I am interested in any difference. Would be nice if you could try too, @aledeg 

```
<plaintext>
sanitizeHTML():
sanitizeHTML 1: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>
sanitizeHTML 2: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>
sanitizeHTML 3: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>

DOMDocument():
HTML to XML 1: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 1: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

HTML to XML 2: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 2: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

HTML to XML 3: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 3: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

XML to XML 1: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 1: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

XML to XML 2: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 2: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

XML to XML 3: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 3: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
```

**Comment by giorgiobeggiora** [comment] 2017-08-16 22:46
```
<plaintext>
sanitizeHTML():
sanitizeHTML 1: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>
sanitizeHTML 2: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>
sanitizeHTML 3: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen" sandbox="allow-scripts allow-same-origin"></iframe></p>

DOMDocument():
HTML to XML 1: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 1: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

HTML to XML 2: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 2: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

HTML to XML 3: <?xml version="1.0" standalone="yes"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p></body></html>

HTML to HTML 3: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p></body></html>

XML to XML 1: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 1: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

XML to XML 2: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 2: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

<br />
<b>Warning</b>:  DOMDocument::loadXML(): Opening and ending tag mismatch: iframe line 1 and p in Entity, line: 1 in <b>/var/www/vhosts/jure.it/lab.jure.it/freshrss/p/i/iframe-test.php</b> on line <b>51</b><br />
<br />
<b>Warning</b>:  DOMDocument::loadXML(): Premature end of data in tag p line 1 in Entity, line: 1 in <b>/var/www/vhosts/jure.it/lab.jure.it/freshrss/p/i/iframe-test.php</b> on line <b>51</b><br />
XML to XML 3: <?xml version="1.0"?>
<p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"/></p>

XML to HTML 3: <p><iframe src="https://www.youtube.com/embed/VkZ2FOs6Mxg?ecver=1" width="100%" height="480" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

```

**Comment by Alkarex** [comment] 2017-08-19 09:10
Thanks for the test.
Hum, the outputs from both our systems seem to be identical. I was hoping for a difference somewhere.
If it is not too sensitive, would it be an option for me to get a temporary access to your server?
Maybe at least a FreshRSS account on your server, to that I can observe the issue by myself.

**Comment by giorgiobeggiora** [comment] 2017-08-21 00:44
i sent temporary ftp and http credentials via email (i found your email addresses in the "contacts" page of your website)

**Comment by Alkarex** [comment] 2017-08-21 09:26
Thanks @giorgiobeggiora 
While your PHP version for Web pages is 5.5.38, it looks like the PHP version called by your cron job is much older (5.3.3).
Could you try to update your command-line PHP (CLI)?
Due to https://github.com/simplepie/simplepie/blob/45c50e895f0657480c57069b25722dfebec1c8e0/library/SimplePie/Sanitize.php#L368-L375 , I am now considering increasing the minimal PHP version for FreshRSS to 5.3.6+.

**Comment by Alkarex** [comment] 2017-08-21 10:31
https://github.com/FreshRSS/FreshRSS/pull/1618

**Comment by giorgiobeggiora** [comment] 2017-08-28 23:34
i'm in vacation till friday so i can't check. So my db entries with iframes could be broken?

**Comment by Alkarex** [comment] 2017-08-28 23:35
Yes indeed @giorgiobeggiora due to the fact that they were generated with an older version of PHP

**Comment by giorgiobeggiora** [comment] 2017-09-04 00:03
i just set up a cron with a 5.6 php user and for now it seems to work correctly

to help other users, please add an alert or some kind of warning that appairs when actualize_script.php is called using an old PHP version!

Thanks.

PS: is there a way to purge all articles? I was able to delete just ones older than one month using "Settings > Archiving > Remove articles after > 1 month".

**Comment by Frenzie** [comment] 2017-09-04 06:15
Each individual feed has a <kbd>Delete all articles</kbd> button but you might have to go into the database if you want to get rid of everything all at once.

**Comment by Alkarex** [comment] 2017-09-04 06:48
@giorgiobeggiora Yes, FreshRSS will now refuse to run and display an error with PHP < 5.3.8.
https://github.com/FreshRSS/FreshRSS/pull/1618

**Closed as completed by Alkarex** 2017-09-04 06:48 UTC

**Comment by giorgiobeggiora** [comment] 2017-09-05 02:42
@Frenzie i have too many feeds, nevertheless i didn't setup a database: freshrss created a db.sqlite file in my user folder but i don't know how to access it

**Comment by Alkarex** [comment] 2017-09-05 13:43
@giorgiobeggiora You can use the "purge" button in the archiving settings (after temporarily setting some very low retention values)

**Comment by giorgiobeggiora** [comment] 2017-09-05 23:37
i did, but i have to keep at least 1 month of articles :(
