### ISSUE TITLE
[BUG] mark-as-read doesn't work reliably

### ISSUE THREAD

**Issue by posita** [FreshRSS/FreshRSS#4256] opened 2022-03-04 14:47 UTC
Client Device: MBP
Client OS: OS X 11.6.4
Server Device: Hosted (DreamHost)
Server OS: `uname -a` -> `Linux … 4.14.117-grsec-grsec+ #1 SMP Fri May 10 17:15:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux`
Browser: Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
FreshRSS version: 1.19.2
Database version: MySQL 8.0.26-0ubuntu0.20.04.2
PHP version: 7.4.15
Installation type: Fresh install with Git + web setup (single user restore via SQLite3 export/import)

I recently filed #4242, but it was closed. So I just now literally spent hours installing 1.19.2 from scratch (via Git, new DB, new web-based install, everything). The only thing I carried over from the prior installation was a `./cli/export-sqlite-for-user.php`/`./cli/import-sqlite-for-user.php` for a single user. Now that user can't reliably use mark-as-read for individual items.

I am seeing these errors:

```
[Fri, 04 Mar 2022 06:31:34 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:35 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:37 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:38 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:42 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:47 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:48 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:50 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:54 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:31:57 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:32:01 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:32:07 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:32:09 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:04 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:33:04 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:33:05 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:06 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:06 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:06 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:07 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:33:07 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 06:34:04 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:34:04 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:34:19 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:34:19 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:34:38 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:34:38 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:34:43 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:34:43 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:36:16 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 06:36:16 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 06:36:16 -0800] [error] --- SQL error updateLastSeen: HY000: 1615 Prepared statement needs to be re-prepared while updating feed 31
```

These are similar errors to what I was seeing when I filed #4242, but this isn't an upgrade. It's a brand new installation.

_Sometimes_ (usually after a manual fetch), I can mark individual items as read and it will "stick" (meaning when I refresh the page, they will stay marked as read). Other times, when I mark individual items as read, they _appear_ to be marked as read, and no error is given, but when I refresh the page, they are again marked as unread. That seems to correspond to the `SQL error markRead: Prepared statement needs to be re-prepared` errors above.

**Comment by Alkarex** [comment] 2022-03-04 16:33
Thanks for trying again and reporting.
I will try again to reproduce. Would you be willing to share your SQLite export with me? (I totally understand if you find that too personal)

**Comment by posita** [comment] 2022-03-11 14:53
I'm reluctant to share my reading list, but I do have some additional observations. While intermittent, this problem seems to be limited to a couple hours. I wonder if this is a clock difference thing. I am hosting the FreshRSS PHP app from a Linux host (Ubuntu 18.04.4 LTS) whose timezone is set to PST. My client browser is running on a machine whose timezone is set to CST. Occasionally, I will see a blue banner in the client that says new articles are available, but when I refresh, there aren't any new articles, but instead, my mark-as-read operations get reset. I'm wondering if that timezone difference has anything to do with this?

_UPDATE: Just trying to check all the boxes here. While my PHP host and my MySQL host are on different machines, it_ appears _they are in agreement regarding timezones. The following is executed from my PHP host connecting to my MySQL host using my FreshRSS credentials:_

```
$ ( set -x ; mysql --vertical -h … -u … -p … ; date ; date --utc )
Enter password:
*************************** 1. row ***************************
 @@global.time_zone: SYSTEM
@@session.time_zone: SYSTEM
              NOW(): 2022-03-11 07:03:07
    UTC_TIMESTAMP(): 2022-03-11 15:03:07
+ date
Fri Mar 11 07:03:07 PST 2022
+ date --utc
Fri Mar 11 15:03:07 UTC 2022
```

**Comment by Frenzie** [comment] 2022-03-11 15:49
The request is just which article ID to mark as read. Time isn't involved.

By the by, there's a `Mark updated articles as unread` setting.

**Comment by posita** [comment] 2022-05-02 14:16
I don't know if this is related, but it seems like feeds cannot be removed during similar time windows that they can't be reliably marked as read. When I attempt to remove a feed during a time when marking items as read doesn't "stick", I get a `Feed cannot be updated` error. Here are the coincident log entries:

```
2022-05-02 06:57:27
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:57:27
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:57:27
SQL error deleteFeed: Prepared statement needs to be re-prepared
2022-05-02 06:57:23
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:57:23
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:57:12
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:57:12
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:57:09
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:57:09
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:57:09
SQL error deleteFeed: Prepared statement needs to be re-prepared
2022-05-02 06:57:05
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:57:05
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:56:56
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:56:56
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:56:56
SQL error deleteFeed: Prepared statement needs to be re-prepared
2022-05-02 06:56:53
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:56:53
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:56:41
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:56:41
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:56:41
SQL error deleteFeed: Prepared statement needs to be re-prepared
2022-05-02 06:56:37
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:56:37
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2022-05-02 06:56:29
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-05-02 06:56:29
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
```

If I with a couple hours, and once mark-as-read seems to work again, removing feeds works without error.

**Comment by Alkarex** [comment] 2022-05-02 18:45
Could you try to comment out the content of the following function?

https://github.com/FreshRSS/FreshRSS/blob/ae097f5bd82aa24ea19cca72ac9d1594b0dcaec0/app/Models/FeedDAO.php#L589-L605

So it looks like:

```php
	public function updateTTL() {
		// $sql = 'UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value';
		// $stm = $this->pdo->prepare($sql);
		// if (!($stm && $stm->execute(array(':new_value' => FreshRSS_Feed::TTL_DEFAULT, ':old_value' => -2)))) {
		// 	$info = $stm == null ? $this->pdo->errorInfo() : $stm->errorInfo();
		// 	Minz_Log::error('SQL warning updateTTL 1: ' . $info[2] . ' ' . $sql);

		// 	$sql2 = 'ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT ' . FreshRSS_Feed::TTL_DEFAULT;	//v0.7.3
		// 	$stm = $this->pdo->query($sql2);
		// 	if ($stm === false) {
		// 		$info = $stm == null ? $this->pdo->errorInfo() : $stm->errorInfo();
		// 		Minz_Log::error('SQL error updateTTL 2: ' . $info[2] . ' ' . $sql2);
		// 	}
		// } else {
		// 	$stm->execute(array(':new_value' => -3600, ':old_value' => -1));
		// }
	}
```

**Comment by posita** [comment] 2022-05-04 12:38
I tried this with [`v1.19.2`](https://github.com/FreshRSS/FreshRSS/tree/1.19.2). The symptom still appears, but the logs are reduced:

```
2022-05-04 05:36:54
SQL error markRead: Prepared statement needs to be re-prepared
2022-05-04 05:36:52
SQL error markRead: Prepared statement needs to be re-prepared
2022-05-04 05:32:27
SQL error markRead: Prepared statement needs to be re-prepared
2022-05-04 05:30:50
SQL error markRead: Prepared statement needs to be re-prepared
2022-05-04 05:30:25
SQL error markRead: Prepared statement needs to be re-prepared
2022-05-04 05:30:12
SQL error markRead: Prepared statement needs to be re-prepared
```

**Comment by posita** [comment] 2022-05-04 12:41
I also tried this with `master` and `edge` with similar results.

**Comment by posita** [comment] 2022-05-05 14:01
Actually, this seems to have introduced another side-effect. When new items were retrieved today, items retrieved yesterday that were previously marked as read were again fetched and marked unread. It's not immediately obvious to me why that would be, but I'm guessing it has to do with this (after effectively turning `updateTTL` into a no-op):

https://github.com/FreshRSS/FreshRSS/blob/1fe66ad020ca8f0560bb9c6e311852ed77228f78/app/Models/FeedDAO.php#L349-L372

**Comment by Alkarex** [comment] 2022-06-21 08:49
Might be related to https://github.com/FreshRSS/FreshRSS/issues/4401 which has a https://github.com/FreshRSS/FreshRSS/pull/4422 to be tested

**Comment by math-GH** [comment] 2022-07-30 12:43
Is it still reproduceable in V1.20.0-dev @posita ?

**Comment by Alkarex** [comment] 2022-08-21 19:33
At least some of the issues have been fixed with https://github.com/FreshRSS/FreshRSS/pull/4422

**Closed as completed by Alkarex** 2022-08-21 19:33 UTC
Labels: Bug (unconfirmed)

**Comment by posita** [comment] 2022-08-25 01:49
Thanks all! I have not yet had a chance to test it, but I'll revisit and reopen if I can reproduce it after the upgrade.

**Comment by posita** [comment] 2023-05-12 12:40
I just noticed this happening again (similar symptoms) with 1.21.0. I believe it is a temporary condition observed shortly after a feed is fetched. ~After a retrieved item ages a few hours, it can successfully be marked as red again.~ _Actually, that's not true. Currently I cannot mark-as-read any item, regardless of when it was fetched. UPDATE: After about 45 minutes, I am again able to mark things as read._

**Comment by posita** [comment] 2023-05-13 12:42
More info: When I click on an item (either to open it in a new tab, expand it, or click it's mark-as-read icon), I see a `POST` going to `.../i/?c=entry&a=read`, which results in a `200`.

Request: `{"ajax":true,"_csrf":"...","id":["16...79"]}`
Response: `{"tags":[]}`

The unread icon (![unread](https://github.com/FreshRSS/FreshRSS/assets/222581/493e2975-3157-45cc-aa9f-309d0f69e55c)) for that item then changes to the read icon (![read](https://github.com/FreshRSS/FreshRSS/assets/222581/aabbf55b-7d07-4215-9907-d40a2e7b0d58)) for that item. But when I refresh the page, all items I just "read" revert to "unread".

**Comment by Alwaysin** [comment] 2023-05-13 14:30
I once had this problem - turns out I had no disk space left on my system.

Edit: yeah, I was just answering your last comment, I did not read the whole thread/initial issue.

**Comment by posita** [comment] 2023-05-13 18:01
> I once had this problem - turns out I had no disk space left on my system.

There is 250+GB free on the host machine (serving PHP), and I'm assuming I'm not running out of space on my service provider's MySQL instance for approx. 1 hr at roughly the same time each day.
