### ISSUE TITLE
Some Feeds had double article

### ISSUE THREAD

**Issue by LabSen** [FreshRSS/FreshRSS#3142] opened 2020-08-13 14:50 UTC
I have install FreshRSS on a Plesk Webhosting with PHP 7.4.8

With some feeds I receive the articles twice. They are loaded, I read them and after 1-2 days the feeds appear again. They were not marked as unread. The same article appears twice in the overview and refers to the same blog link.

Some example: https://christophrox.wordpress.com/

**Comment by Alkarex** [comment] 2020-08-18 12:49
Try to disable that option:
![image](https://user-images.githubusercontent.com/1008324/90514798-f400ec80-e161-11ea-9363-3486b4e95a1c.png)

**Comment by wolfpld** [comment] 2020-09-24 10:15
I have the same problem with slashdot feed. "Mark updated articles as unread" is disabled.

**Comment by Alkarex** [comment] 2020-09-24 12:26
If a feed publishes an article twice (changing the URL), then it will appear twice in FreshRSS. Please check whether this is the case.
I actually have an idea of auto-marking-as-read articles that have vanished (replaced by another title / URL) to mitigate this problem.

**Comment by wolfpld** [comment] 2020-09-24 12:35
An example pair of duplicate messages has identical URLs in my feed:

http://rss.slashdot.org/~r/Slashdot/slashdot/~3/qkXFTVo3fao/jeff-bezos-is-opening-his-first-tuition-free-bezos-academy-preschool-where-each-child-will-be-the-customer

and

http://rss.slashdot.org/~r/Slashdot/slashdot/~3/qkXFTVo3fao/jeff-bezos-is-opening-his-first-tuition-free-bezos-academy-preschool-where-each-child-will-be-the-customer

This is using the default rss feed received by FreshRSS when subsribing to slashdot.org. I'm now looking how atom feed will behave, as it has different URL scheme:

https://science.slashdot.org/story/20/09/24/0431217/chitin-could-be-used-to-build-tools-and-habitats-on-mars-study-finds?utm_source=atom1.0mainlinkanon&utm_medium=feed


One thing to note, I have originally set the automatic refresh rate to 20 minutes. This is against slashdot policy (https://slashdot.org/faq/feeds.shtml):

>  Our policy is to allow one request every 30 minutes. We'll allow a few more before you'll get banned, and we are more flexible still with proxy servers. You should still be able to access the rest of the site, just not the .rss, .rdf, and .xml pages. 

Maybe this could be the cause?

**Comment by Frenzie** [comment] 2020-09-24 13:12
Doubtful, then you just shouldn't get any updates at all (eventually).

But what's the feed address? Slashdot has several. Are you talking about <http://rss.slashdot.org/Slashdot/slashdotMain>?

**Comment by wolfpld** [comment] 2020-09-24 13:20
Yes, http://rss.slashdot.org/slashdot/slashdotMain.

**Comment by Alkarex** [comment] 2020-12-28 23:02
New filter to automatically marking as read new articles with an existing title https://github.com/FreshRSS/FreshRSS/pull/3303

**Closed as completed** 2021-09-19 08:56 UTC
