### ISSUE TITLE
[Bug] Preview of CSS selector uses the one saved and not the one entered

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#6266] opened 2024-04-05 12:10 UTC
### Describe the bug

I find it misleading that when previewing a CSS selector, it uses the one that is saved and not the one entered. When one doesn't really know what to input there and goes by trial and error, it is very cumbersome to each time save the settings and go back to the config to be able to preview the selector.

Plus, I'm not sure if "CSS selector of the elements to remove" is taken into account in the previewing, and if it is the case it probably also needs to be saved.

### To Reproduce

1. Go to a feed settings
2. Change the value of "Article CSS selector on original website"
4. Click the preview button
6. See the old value used

### Expected behavior

Using the newly entered value

### FreshRSS version

latest edge

### Environment information

- Database version: MariaDB 10.11
- PHP version: PHP 8.2
- Installation type: git
- -Web server type: Apache
- Device: Laptop
- OS: Win11
- Browser: Chrome 124

**Comment by math-GH** [comment] 2024-04-05 15:12
Duplicate of #6228

**Comment by math-GH** [comment] 2024-04-09 20:15
First look into the code:

The selector is used only for showing an error message, if the current selector is empty
https://github.com/FreshRSS/FreshRSS/blob/8280e3d88edb93211fcf2aec15a7b4c1ae4d3813/app/Controllers/feedController.php#L1114-L1119

Then everything is fetched from the database.

`selector_filter=selector-filter-token` is set in the link for the preview, but nowhere used. It looks like a stump from #4501

**Comment by Alkarex** [comment] 2024-05-02 08:24
Please try https://github.com/FreshRSS/FreshRSS/pull/6423

**Closed as completed** 2024-05-02 12:13 UTC
Labels: Good first issue 1️⃣, Bug (confirmed) 🐞

**Comment by Alwaysin** [comment] 2024-05-02 12:54
Thank you, works like a charm!
It is not supposed to take "CSS selector of the elements to remove" into account, right? Is it wortt opening an issue about it?

**Comment by mrnoname1000** [comment] 2024-05-02 13:56
The article selector works like a charm, but as @Alwaysin mentions, the removal selector is not taken into account for the preview. I would argue this is even more surprising behavior and still a bug.

I would also like to note that testing is made more difficult due to #6229 as any `>` operators are mangled, breaking most of the article selectors for my feeds.

**Comment by Alkarex** [comment] 2024-05-02 17:28
Thanks for the feedback. Please try https://github.com/FreshRSS/FreshRSS/pull/6426

**Comment by Alwaysin** [comment] 2024-05-02 20:49
It works perfect, thank you!
