### ISSUE TITLE
Dark theme: Loader.gif never disappears

### ISSUE THREAD

**Issue by Tintwo** [FreshRSS/FreshRSS#2986] opened 2020-05-19 18:02 UTC
Hello,

I recently setup FreshRSS on my server with the latest Docker image, with the version 1.16.1-dev of FreshRSS.
I notice when I'm on a page where there is at least 1 stream, the animated loading gif is always visible on the list. Inside DOM, the concerned `div` element is `id="first_load"`.
I guess the class `loading` is never changed and so the loading gif stays always.

Tested on Firefox 68.8.0 ESR and Chromium 80.0.x, on a Debian Buster, without AdBlocker.

Regards.

**Comment by Tintwo** [comment] 2020-05-19 20:09
Another thing I didn't think it was important : on the default theme everything is OK.
The problem is visible on the "Dark" Theme, by "AD" (n°4/11).

**Comment by Alkarex** [comment] 2020-05-19 20:51
Thanks for testing the master branch, @Tintwo 
Please try this fix https://github.com/FreshRSS/FreshRSS/pull/2987

**Comment by Tintwo** [comment] 2020-05-20 09:19
Hello @Alkarex ,
I just made a try with the master branch, on a new setup, and the problem still exists in the same way (both browsers), only with that theme apparently.

Note : I scrap my browser cache each time, just in case.

**Comment by Alkarex** [comment] 2020-05-20 10:02
@Tintwo Ah, it is because the fix was not merged in /master yet. But I have just done so to ease testing. Please try again :-)

**Closed as completed** 2020-05-20 10:02 UTC
Labels: UI :art:

**Comment by Tintwo** [comment] 2020-05-20 10:21
@Alkarex 
Oh ! :rofl: 
I just tested again, now it's work as expected !

Thanks for the fix, I'm waiting the docker image update ;)

[edit] Oh, docker image already available, works fine :)

**Comment by nicofrand** [comment] 2020-05-20 10:43
[**EDIT**]: there is surely a good reason why it was not done in the way I describe below, I don't want to criticize (hence this edit, to make things clear), I just would like to understand the reason so I don't miss some important things when trying to adapt my extension.

Hi!

I can see the issue on several other themes (Flat design for example), but that also creates an issue for my extension (https://framagit.org/nicofrand/xextension-threepanesview/-/issues/10).

Why isn't that spinner in the `div.stream`? I would expect the spinner to exists on first load (as the name suggests) until the the items are loaded and the loader is replaced by the items. Something like that:

**Before:**

```html
<div class="stream">
    <div class="first_load loading"></div>
</div>
```

**After:**

```html
<div class="stream">
    <div class="flux"></div>
    <div class="flux"></div>
    <div class="flux"></div>
</div>
```

**Comment by Alkarex** [comment] 2020-05-20 21:29
@nicofrand It is nice that some people are testing the master branch :-)
That is more or less the idea, but working during page load (i.e. the DOM has not fully arrived yet), and even without JavaScript (but we can for sure add a JavaScript line to remove it from the DOM). The main difficulty is Chrome, which, as opposed to Firefox which obeys CSS rules fine during page load, does not do so (as well).

For instance, a code like the following works in Firefox but not in Chrome:

```css
/* Only during load, i.e. last or second last div node */
#first_load:not(:nth-last-of-type(-n+2)) {
	display: none;
}
```

I can reproduce the bug with some themes, but only in the mobile view, right, or have you seen it in desktop view as well?

In your extension, can't it be hidden by the content loaded on top of it?

**Comment by Alkarex** [comment] 2020-05-20 22:08
Fix coming

**Comment by nicofrand** [comment] 2020-05-21 09:20
> I can reproduce the bug with some themes, but only in the mobile view, right, or have you seen it in desktop view as well?

I only tested on desktop and could reproduce with the "Flat design" theme.

> In your extension, can't it be hidden by the content loaded on top of it?

I try to not force the colors at when possible, to remain compatible with all themes, so I keep a transparent background.

I'll test your fix, thanks!
