### ISSUE TITLE
Firefox 119: Drop down menus dark theme Origine

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#5809] opened 2023-11-02 18:10 UTC
Drop-down menus arrows are not (enough) visible:
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/a2ccfa22-4172-4e08-99da-f3708eb7b8e3)

**Comment by math-GH** [comment] 2023-11-02 19:44
I know. And it is the "fault" of the browsers.....  Via CSS it is not possible to change the color easily. A complete image file is needed, but it will break the default style of the browser/operating system.

Maybe someone knows more than me...

**Comment by Frenzie** [comment] 2023-11-02 20:47
What are the steps to see the problem?

**Comment by math-GH** [comment] 2023-11-02 20:48
switch over to any dark theme.

@Alkarex used the dark mode of Origine theme.

**Comment by Frenzie** [comment] 2023-11-02 20:52
So basically something like:

1. Select dark mode auto
2. Open about:preferences and select dark

I'll take a look.

**Comment by Frenzie** [comment] 2023-11-02 20:52
Looks great to me
![image](https://github.com/FreshRSS/FreshRSS/assets/202757/cf747804-a717-4c0a-80ba-f8b345ca6a92)

Firefox 115.4.0esr

**Comment by Frenzie** [comment] 2023-11-02 20:57
In Chromia it seems to be hidden behind the chrome://flags (i.e., not finished and not ready for use) but it looks fine nonetheless.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/7814b4cc-2e14-4734-a7f6-6955e6bd56fc)

**Comment by Frenzie** [comment] 2023-11-02 20:58
So I can only repeat: what are the steps to reproduce because I'm not going to waste another five minutes on this! Heh.

**Comment by math-GH** [comment] 2023-11-02 20:58
Which operating system do you use?

**Comment by Frenzie** [comment] 2023-11-02 20:59
That's on Linux, the version that gets the least love (give or take *BSD).

**Comment by math-GH** [comment] 2023-11-02 21:02
Firefox 119 on Windows 10 (and similar: Firefox on Android):
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/dd3dcfab-5cb9-41bb-91a7-9666ca1e57b5)

Chromium 108 on Windows 10:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/a4a94109-5c3a-44e8-b096-5d5431f67177)

**Comment by Frenzie** [comment] 2023-11-02 21:08
The problem lies in Firefox 119. Sometime after 115 a regression was introduced.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/0bd52e6e-e8a2-45cd-a95b-0b3ab0a60188)

**Comment by Frenzie** [comment] 2023-11-02 21:16
Three years old but potentially still somewhat related: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1707384
https://hg.mozilla.org/integration/autoland/rev/5c194dac64e0

Fixed in nightly:
![image](https://github.com/FreshRSS/FreshRSS/assets/202757/f10d67dd-dd3f-4910-9606-bb5bf14920e1)
![image](https://github.com/FreshRSS/FreshRSS/assets/202757/18ffa84b-0016-4177-9c9c-c6d8251db326)

**Comment by Alkarex** [comment] 2023-11-02 21:42
I noticed the problem with Firefox 119 on Windows 10 - sorry for forgetting to mention. Seems to be limited to Firefox, indeed

**Closed as completed** 2023-11-02 21:43 UTC
Labels: Theme 🖌

**Comment by math-GH** [comment] 2023-11-02 22:55
> The problem lies in Firefox 119. Sometime after 115 a regression was introduced.
> 
> ![image](https://user-images.githubusercontent.com/202757/280127942-0bd52e6e-e8a2-45cd-a95b-0b3ab0a60188.png)

I can confirm, that the issue is not in Firefox 115.4.0 ESR on Windows 10.



> I noticed the problem with Firefox 119 on Windows 10 - sorry for forgetting to mention. Seems to be limited to Firefox, indeed

Thanks for opening this discussion. I was thinking about this issue too and did not have the idea that it could be an issue of the newer Firefox.

**Comment by Alkarex** [comment] 2023-11-08 18:56
Fixed for me with the freshly released Firefox 119.0.1.

**Comment by math-GH** [comment] 2023-11-08 22:56
great!
That is the fixed bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1861253
