### ISSUE TITLE
"subscribe" bookmarklet not working for me

### ISSUE THREAD

**Issue by gpion** [FreshRSS/FreshRSS#2609] opened 2019-10-27 19:24 UTC
Hello,
the "subscribe" bookmarklet do not work for me (and never did as long as I remember)
It always fails with the following error:

```
Error 404 - Not found
You are looking for a page which doesn’t exist
← Go back to your RSS feeds
```

Clicking on the "go back" link I'm getting redirectrd to a login form (URL: http://<my.site.com>/FreshRSS/p/i/?c=auth&a=login) which fails after entering valid user password:
```
Error 403 - Forbidden
You don’t have permission to access this page
← Go back to your RSS feeds
```

**Comment by Frenzie** [comment] 2019-10-27 19:37
It seems to work for me, except the bookmark URL seems to be using an IP by default instead of the relevant hostname. I'm not sure if that's a server/FreshRSS configuration issue or something in the code.

**Comment by gpion** [comment] 2019-10-27 19:41
> the bookmark URL seems to be using an IP by default instead of the relevant hostname

Thanks, but this doesn't help as you may guess.

**Comment by Frenzie** [comment] 2019-10-27 19:45
Well, I mean it works for me after I replace the IP with the proper address. If you were seeing the same thing it wouldn't be weird to be logged in on the domain and not on the IP. :-)

Which browser is that with, and which version of FreshRSS?

**Comment by gpion** [comment] 2019-10-27 19:51
Ok, found the root cause: in mt "config.php", the "base_url" value was not empty (it look like by default it should according to some other similar post found). It's value was: "http://<my.site.com>/FreshRSS/p" (seem legit to me though)
After having modified it to en empty value, it works fine now.

**Comment by Alkarex** [comment] 2019-10-27 20:06
@gpion It is better to have a `base_url` set (required for some features), but it needs to be correct :-)
Don't forget the trailing slash

**Comment by Frenzie** [comment] 2019-10-27 20:10
Ah, that explains my bookmarklet. [Edit: confirmed fixed with updated `base_url`.] A few years ago when I first set up my VPN it was only connected through an IP before I set up a domain name, and that IP has changed (once) since.

I've never noticed any adverse side effects though.

**Comment by Frenzie** [comment] 2019-10-27 20:11
Btw, perhaps it could also be something like http vs https?

**Comment by gpion** [comment] 2019-10-27 20:19
> @gpion It is better to have a `base_url` set (required for some features), but it needs to be correct :-)
> Don't forget the trailing slash

Thanks, but what is the correct value for my setup (installed in "/FreshRSS" relative to the httpd base dir) (BTW I did'nt had a trailing slash)

**EDIT**
Appending the slash and using https seem OK (I refreshed the _"subscription tools"_ page to get the new generated bookmarklet and tested again)

**Closed as completed** 2019-10-27 21:51 UTC
Labels: Documentation :books:
