### ISSUE TITLE
PubSubHubbub support?

### ISSUE THREAD

**Issue by julien51** [FreshRSS/FreshRSS#791] opened 2015-02-10 15:05 UTC
Adding PubSubHubbub would reduce the need for polling, while still propagate updates in realtime. It's free, open, decentralized and easy to implement! (and you can/should still failover to regular polling).

Check this [PubSubHubbub Getting started](http://blog.superfeedr.com/howto-pubsubhubbub/) tutorial for more details!

**Comment by aledeg** [comment] 2015-02-10 15:16
Duplicate of #312

**Closed as completed by aledeg** 2015-02-10 15:16 UTC

**Comment by julien51** [comment] 2015-02-10 15:22
Oups! (désolé...)
