### ISSUE TITLE
Migrate database to new or existing user account

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2289] opened 2019-03-21 14:30 UTC
I think, it is quite usual need. Is it possible to do it with FreshRSS?

**Comment by Alkarex** [comment] 2019-03-28 14:54
Currently, we have some built-in import/export of feed list, labels, etc. which are often sufficient.
In addition, I plan to add a feature to export/import via an SQLite file (even when using MySQL or PostgreSQL).

**Comment by squromiv** [comment] 2019-03-28 15:11
This issue is similar to #852.
As I have understood, the easiest way to do this today:
*export feeds from "account1"; 
*create new "account2"
*import feeds "to account2"; edit config.php files

>when using MySQL or PostgreSQL
>
What is the best choice for FreshRSS? I searched for this topic and unfortunately found nothing.

**Comment by aledeg** [comment] 2019-03-28 15:24
> What is the best choice for FreshRSS? I searched for this topic and unfortunately found nothing.

All supported databases are equally supported. The best choice depends on your server and usage.
If you have one user with few feeds, Sqlite would work fine for you. If you have many users with lots of feeds, MySQL and PostgresSQL are recommended.
If you can install either MySQL or PostgresSQL, it's up to you since they both are well suited to handle FRSS.

**Comment by Alkarex** [comment] 2019-03-28 15:57
MySQL is more common and more tested with FreshRSS, but PostgreSQL should be fine as well (and any problem will be addressed).
PostgreSQL has better full text indexing options (not automatically added by FreshRSS, but easy to add manually). 
SQLite is much lighter, and also well tested. There is one SQLite file per user, so it scales fine with many users. However, as @aledeg explains, MySQL or PostgreSQL scale better for users with many feeds and/or articles.

**Comment by marienfressinaud** [comment] 2020-01-16 17:37
This issue was fixed in https://github.com/FreshRSS/FreshRSS/issues/2567 and is a duplicate of https://github.com/FreshRSS/FreshRSS/issues/961 (just a bit of documentation is missing)

**Closed as completed by marienfressinaud** 2020-01-16 17:37 UTC
