### ISSUE TITLE
Problem about item update date and time

### ISSUE THREAD

**Issue by maobaoqi** [FreshRSS/FreshRSS#2153] opened 2018-11-28 09:10 UTC
Hi, I find a problem about freshrss item date and time, which is different from real time.
I update some items serverl times and the issue also exists.
![snipaste_20181128_170201](https://user-images.githubusercontent.com/3353791/49140878-51229200-f330-11e8-8612-e0939bcb97b9.png)
For example: now real time is 2018.11.28, but freshrss item show 2018.11.27.

**Comment by Alkarex** [comment] 2018-11-28 09:43
Hello,
The date/time on the column on the right-hand side is the date declared by the feed, not the time at which the article was received by FreshRSS. I hope this answers your question?
I am actually considering making an option to switch between the declared date and the received date.

**Comment by maobaoqi** [comment] 2018-11-28 12:48
So that's it! loolking forward to the further function, thanks!

**Comment by Alkarex** [comment] 2018-12-01 12:40
@maobaoqi Would you personally better like to have the received date in the column on the right-hand side, instead of the publication date?

**Comment by maobaoqi** [comment] 2018-12-03 08:18
I would like to know the page publication date.

**Comment by xobs** [comment] 2019-01-16 01:41
I'm experiencing similar issues.

For example, this entry:

```xml
 <item> <title>Top stories from The Straits Times on Wednesday, Jan 16</title>
 <link>http://www.straitstimes.com/singapore/top-stories-from-the-straits-times-on-wednesday-jan-16</link>
 <description>January 16, 2019 7:15 AM&lt;br /&gt;&lt;br /&gt;Good morning! Here are our top stories to kick-start your Wednesday, Jan 16.

 </description>
 <guid isPermaLink="false">http://www.straitstimes.com/singapore/top-stories-from-the-straits-times-on-wednesday-jan-16</guid>
 <pubDate>Wed, 16 Jan 2019 07:15:00 +0800</pubDate>
 <source url="https://www.straitstimes.com/news/singapore/rss.xml/20190116">The Straits Times</source>
</item>
```

However, the date is showing up incorrectly on the right-hand side:

![image](https://user-images.githubusercontent.com/238325/51221069-cf83d380-1972-11e9-97fa-a3b2f8b194fc.png)

The server's timezone is set correctly:

```sh
/var/www/FreshRSS # date
Wed Jan 16 09:41:02 +08 2019
/var/www/FreshRSS #
```

And this matches my system's timezone as well.

**Comment by Alkarex** [comment] 2019-01-16 07:33
Hello @xobs ,
Could you please try to run the following command?

```sh
php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
```

**Comment by xobs** [comment] 2019-01-16 07:36
Hi @Alkarex ,

It looks like PHP is ignoring the system and setting the timezone to UTC:

```sh
/var/www/FreshRSS # php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
UTC
2019-01-16T07:34:31+00:00
/var/www/FreshRSS #
```

I'm using the Docker image, with /etc/localtime mounted to my system's localtime.

**Comment by Alkarex** [comment] 2019-01-16 07:38
I will make a new option to define per-user timezone. Other suggestions welcome.

**Comment by xobs** [comment] 2019-01-16 07:42
That could work.

I'm not familiar with PHP, but the Docker image doesn't ship with tzdata installed.  Is it possible to just use /etc/localtime as the zoneinfo file?

**Comment by Alkarex** [comment] 2019-01-16 07:45
Yes, we could do something at Docker level too. See e.g. our draft of Ubuntu-based image alternative, which accepts a `ENV` for timezone https://github.com/FreshRSS/FreshRSS/blob/e0dc24cff48503626456821f856715ae58bf3099/Docker/Dockerfile-Ubuntu
https://github.com/FreshRSS/FreshRSS/pull/2205

**Comment by xobs** [comment] 2019-01-16 07:48
The `TZ` variable doesn't seem to affect the timezone:

```sh
/var/www/FreshRSS # TZ=Asia/Singapore php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
UTC
2019-01-16T07:47:58+00:00
/var/www/FreshRSS #
```

Even if I install the `tzdata` package, PHP ignores that variable.

You're probably right in that a per-user configuration is the best way to do it.

**Comment by Alkarex** [comment] 2019-01-16 07:52
Apparently, PHP is not using the system parameters since PHP 5.4 http://php.net/manual/function.date-default-timezone-get.php

**Comment by xobs** [comment] 2019-01-16 07:53
Ah, it seems as though by default, php ignores the system timezone and requires that you configure it yourself.

Debian fixes this bug by having php use the system timezone.  That's why the Ubuntu version works, but the Alpine version does not, and why you can modify the timezone with `TZ` on Ubuntu.

**Comment by Alkarex** [comment] 2019-01-16 21:17
Fix for Alpine-based Docker image in https://github.com/FreshRSS/FreshRSS/pull/2218

```
$ date
Wed 16 Jan 22:15:42 CET 2019

$ sudo docker run -it -e TZ=Europe/Paris --rm freshrss/freshrss:alpine php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
Result: success
Europe/Paris
2019-01-16T22:16:08+01:00

$ sudo docker run -it -e TZ=Europe/Paris --rm freshrss/freshrss:ubuntu php -r 'echo date_default_timezone_get(), "\n", date("c"), "\n";'
Result: success
Europe/Paris
2019-01-16T22:16:46+01:00
```

P.S.: The tags `:alpine` and `:ubuntu` are not yet available, but the tag `:dev` should work as well.

**Comment by xobs** [comment] 2019-01-17 00:39
Confirmed that :dev solves the issue.

**Comment by Alkarex** [comment] 2019-01-17 07:57
Closing here if the main problem is solved. User-specific enhancements, will be done in https://github.com/FreshRSS/FreshRSS/issues/853

**Closed as completed by Alkarex** 2019-01-17 07:57 UTC
