### ISSUE TITLE
[BUG] Article selector preview uses saved selectors instead of submitted ones

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#6228] opened 2024-03-23 18:35 UTC
**Describe the bug**
When previewing article selectors, FreshRSS submits a request to the server with the currently inputted selectors, but the server is ignoring the submitted selectors and instead uses the ones saved in the DB.

**To Reproduce**
1. Type a CSS article selector (and optionally a delete selector) for a feed and submit
2. Change selector without submitting
3. Click the preview button
4. The preview uses the selector(s) submitted in step 1

**Expected behavior**
The preview should use the selector that is currently inputted in the UI.

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 124.0
- FreshRSS version: 1.23.2-dev 1c0b8a7
- Database version: PostgreSQL 16.2
- PHP version: 8.2.7
- Installation type: Docker self hosted

**Comment by math-GH** [comment] 2024-04-09 20:24
Thanks for the report.

Duplicate of #6266

Let's close this one to keep the focus on one ticket

**Closed as completed by math-GH** 2024-04-09 20:24 UTC
Labels: Good first issue 1️⃣, help wanted, Duplicate ‼, Bug (confirmed) 🐞
