### ISSUE TITLE
FreshRSS version 1.14.1 throwing Fatal error on PHP 5.3-PHP5.5

### ISSUE THREAD

**Issue by prbt2016** [FreshRSS/FreshRSS#2364] opened 2019-04-08 06:38 UTC
Hello,
I  tried to manually install FreshRSS version 1.14.1 on Centos 6.4 Linux, PHP 5.3.29, Apache 2.2.34 and MYSQL 5.5. However i get the following error i.e Fatal error: Arrays are not allowed as constants in /{{path}}/{{to}}/{{freshrssdir}}/lib/lib_rss.php on line 559. 

This is because on line 552-559 of lib_rss.php is defined as const SHORTCUT_KEYS = array({{array_elements}}); , this syntax is supported since PHP 5.6 and is throwing fatal error on PHP 5.3-PHP 5.5. Are the PHP requirements changed?. Since here https://github.com/FreshRSS/FreshRSS it mentions min PHP requirement to be PHP 5.3.8+. Could you please check and fix this as soon as possible?.

**Comment by Alkarex** [comment] 2019-04-08 07:03
Hello,
Could you please try our /dev branch instead?
A fix for PHP < 5.6 has just landed https://github.com/FreshRSS/FreshRSS/pull/2360

Duplicate of https://github.com/FreshRSS/FreshRSS/issues/2359

**Closed as completed** 2019-04-08 07:04 UTC

**Comment by Alkarex** [comment] 2019-04-08 21:32
FreshRSS 1.14.2 has just been released
