### ISSUE TITLE
Responsive layout: access configuration from mobile

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#976] opened 2015-09-10 07:05 UTC
In responsive layout is not displayed configuration button and site name/logo.

**Comment by Alwaysin** [comment] 2015-09-10 10:02
Duplicate of #45 (but in French).

Anyway, +1, much wanted here :)

**Comment by Alkarex** [comment] 2017-06-08 06:26
Now this is the main ticket. See https://github.com/FreshRSS/FreshRSS/issues/45 for background discussion in French.

**Comment by marienfressinaud** [comment] 2020-05-01 07:12
I'm closing this ticket in favour of #1876 which contains more discussions.

**Closed as completed by marienfressinaud** 2020-05-01 07:12 UTC
Labels: UI :art:
