### ISSUE TITLE
[BUG] URL not respected in "iconUrl" property

### ISSUE THREAD

**Issue by martinrotter** [FreshRSS/FreshRSS#3633] opened 2021-05-21 07:42 UTC
This is similar to #3628.

I have VirtualBox + docker image with FreshRSS and it gets random local network address `192.168.2.x` from DHCP. Sometimes it is `192.168.2.169` sometimes `192.168.2.168` etc.

When calling greader API endpoint `reader/api/0/subscription/list?output=json`, then resulting "iconUrl" properties do not respect server's real address. For example:

```json
    {
      "id": "feed/135",
      "title": "Антон Иоков",
      "categories": [
        {
          "id": "user/-/label/Personal Blogs",
          "label": "Personal Blogs"
        }
      ],
      "url": "http://blog.antoniokov.com/rss/",
      "htmlUrl": "http://blog.antoniokov.com/",
      "iconUrl": "http://192.168.2.169/f.php?20d4c5e4"
    }
```

This causes serious bugs in RSS Guard because it tries to download feed icons during feed tree syncing and each request times out because "http://192.168.2.169/f.php?20d4c5e4" is no reachable. It should be "http://192.168.2.168:PORT/f.php?20d4c5e4" (when #3628 if fixed too).

**Comment by aledeg** [comment] 2021-05-21 10:51
Could you provide the values of all the headers? My guess is there might be a problem while extracting them from the request.

**Comment by martinrotter** [comment] 2021-05-21 11:21
[freshtest.txt](https://github.com/FreshRSS/FreshRSS/files/6522139/freshtest.txt)

**Comment by martinrotter** [comment] 2021-05-21 11:26
Root of the problem is: 
![image](https://user-images.githubusercontent.com/1255302/119130439-84919380-ba38-11eb-90c6-f0d0ec3a82ef.png)

Config contains base address value which was probably deducted during installation (docker) but as I said, my freshrss server usually gets random DHCP addresses every time and freshrss instance does not seem to handle it well.

**Comment by martinrotter** [comment] 2021-05-21 11:30
If I remove value of "base_url" and restart server then I get this in response:

```json
    {
      "id": "feed/1",
      "title": "FreshRSS releases",
      "categories": [
        {
          "id": "user/-/label/Uncategorized",
          "label": "Uncategorized"
        }
      ],
      "url": "https://github.com/FreshRSS/FreshRSS/releases.atom",
      "htmlUrl": "https://github.com/FreshRSS/FreshRSS/",
      "iconUrl": "http://192.168.2.168/api/greader.php/reader/api/0/f.php?aab4347e"
    }
```


So URL is correct but still no port as specified in #3628.

**Comment by martinrotter** [comment] 2021-05-21 11:48
My recommendation would to not return full URL but relative URL instead which is perfectly valid and sane approach, for example:

`"iconUrl": "/api/greader.php/reader/api/0/f.php?aab4347e"`

https://datatracker.ietf.org/doc/html/rfc3986#section-4

**Comment by Alkarex** [comment] 2021-05-26 19:28
Regarding the port, same as https://github.com/FreshRSS/FreshRSS/issues/3628#issuecomment-849008239 I cannot reproduce the problem.

If you want to always have an autodetection of the base URL, just set `'base_url' => '',` in `./data/config.php` (this is in general not advisable, though, as it will break some features).

Having an address that changes would typically break external clients anyway. This can be fixed by dynamic DNS, or a proper reverse proxy configuration, or by using a link-local IPv6 (which is stable), or by using a fixed IPv4, or several other solutions.

Regarding a root-relative URL is not what is used in that API and changing it would break other clients.
See e.g. https://www.inoreader.com/developers/subscription-list

https://github.com/readrops/Readrops/blob/1852a0bd9af9e07c57da29b4b92a5f868c0f0a58/app/src/main/java/com/readrops/app/utils/feedscolors/FeedColors.kt#L12

https://github.com/readrops/Readrops/blob/d6f98b0d085f92852cc07988b5d6771abdff858d/db/src/main/java/com/readrops/db/entities/Feed.java#L44

**Closed as completed by Alkarex** 2021-05-26 19:28 UTC
Labels: API :handshake:
