### ISSUE TITLE
[Feature] Sub Category for Category

### ISSUE THREAD

**Issue by beevme** [FreshRSS/FreshRSS#4804] opened 2022-11-01 17:15 UTC
Hi, If it's not available, please add a sub category feature for category. 

**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you’d like**
For Example, something like this:

[Category] YouTube
> [Sub-Cat] Tech
>> Feed
>> Feed

> [Sub-Cat] News
>> Feed
>> Feed

[Category] Reddit 
> [Sub-Cat] Tech
>> Feed
>> Feed

> [Sub-Cat] News
>> Feed
>> Feed

**Comment by aledeg** [comment] 2022-11-01 17:44
Duplicate of #3833

**Closed as completed** 2022-11-01 21:21 UTC
Labels: Vote to close, Duplicate ‼
