### ISSUE TITLE
[BUG] Clicking next to article makes it collapse

### ISSUE THREAD

**Issue by alexounet2** [FreshRSS/FreshRSS#4713] opened 2022-10-11 10:16 UTC
Issue:
When clicking next to an open article (and also when selecting text and releasing the mouse button in this area), the article collapses. I'm reporting this as a bug since there is no visual feedback ("click"-cursor) for this, unlike on the article header.

1. Open article
2. Click on the margin of the content < div> (see screenshot)
3. Article collapses as if its header was clicked

Expected behavior:
Nothing should happen.

![image](https://user-images.githubusercontent.com/31563741/195062506-3790639d-817b-4df2-a343-fd31d2747cb7.png)

Environment information (please complete the following information):
- Device: PC with a large enough screen
- OS: any (tested on Windows 10 and EndeavourOS)
- Browser: any (tested on Chrome 106 and Firefox 105)
- FreshRSS version: 1.20.0
- PHP version: 7.4.30

Suggested solution:
Make only the < li> "item title" clickable for the collapsing behaviour and not the whole < div> "flux active current" as I guess it is the case now.

PS: thanks for your great work, FreshRSS is an awesome piece of software!

**Comment by math-GH** [comment] 2022-10-11 11:44
It is not a bug, it is a feature.

You can disable it in the configuration -> Reading 
![grafik](https://user-images.githubusercontent.com/1645099/195081140-5fb62679-3d6d-4f68-908a-1d97a16fede4.png)

(IMHO I do not like this feature. It is enabled by default)

**Comment by alexounet2** [comment] 2022-10-11 12:04
Thanks for pointing this out!

**Comment by Alwaysin** [comment] 2022-10-11 12:55
> (IMHO I do not like this feature. It is enabled by default)

I second this. This + mark articles as read while scrolling, I find it very "unhealthy" and believe people actually leave because of this. It is not sane defaults to see the aricles disappear just wandering about discovering the tool.

EDIT: math, I know this has nothing to do here (:D) but its just a reaction to what you've said! I don't know if it's best to open a discussion about this, I think I've already read something about it, t surely is somewhere around here.

**Comment by math-GH** [comment] 2022-10-11 12:59
Let's keep open this ticket for a short discussion.

**Comment by math-GH** [comment] 2022-10-11 13:00
ping @Alkarex @Frenzie @aledeg

**Comment by Frenzie** [comment] 2022-10-11 14:56
I'm strongly in favor of not doing that.

Edit: also see https://github.com/FreshRSS/FreshRSS/pull/1539#issuecomment-304470676

**Comment by Alkarex** [comment] 2022-10-11 15:20
I do not really mind, but otherwise edging on the side of having this option disabled by default.

**Comment by aledeg** [comment] 2022-10-15 11:29
> I'm strongly in favor of not doing that.
> 
> Edit: also see [#1539 (comment)](https://github.com/FreshRSS/FreshRSS/pull/1539#issuecomment-304470676)

What do you mean by "that"? Changing the default value of the parameter?

**Comment by Alwaysin** [comment] 2022-10-15 12:14
I also didn't get the comment. It looks from the comment linked that he has the same opinon than us: not having the "Clicking outside of article text area closes the article" checked by default.
I'd like to emphasize again the fact that I find it healthier to have the setting "mark articles as read while scrolling" as not checked by default either.

**Comment by Frenzie** [comment] 2022-10-15 13:16
> What do you mean by "that"? Changing the default value of the parameter?

That as in "When clicking next to an open article (and also when selecting text and releasing the mouse button in this area), the article collapses." Unexpectedly marking things as read/closing/etc. just because you happened to click outside of some invisible zone is awful.

**Comment by aledeg** [comment] 2022-10-15 14:40
Ok, so we can change the default value as it seems that everyone agrees :)

**Closed as completed** 2022-10-16 10:42 UTC
Labels: UI :art:, Discussion
