### ISSUE TITLE
Import previous save on new install fails

### ISSUE THREAD

**Issue by typhoe** [FreshRSS/FreshRSS#2517] opened 2019-09-09 15:04 UTC
Hi,

I'm using FreshRSS (git 1.14.4-dev) on a debian LXC container.

Wanting to reinstall my container to debian 10 (from 9), I created a full export freshrss_MYUSER_YYYY-MM-DD_export.zip.
Then, installed and configured FreshRSS on the new debian 10 container (PHP 7.3 and PostgreSQL 11).
And finally, tried restoring the save in FreshRSS...

got an error -> HTTP ERROR 500

Here is the error log from apache2:
root@freshrss:~# tail -f /var/log/apache2/freshrss_error.log 
`[Mon Sep 09 16:54:41.556692 2019] [php7:error] [pid 495] [client 192.168.1.201:50740] PHP Fatal error:  Uncaught Error: Call to a member function id() on null in /srv/FreshRSS/app/Controllers/importExportController.php:312\nStack trace:\n#0 /srv/FreshRSS/app/Controllers/importExportController.php(246): FreshRSS_importExport_Controller->addFeedOpml(Array, 'Actus Info')\n#1 /srv/FreshRSS/app/Controllers/importExportController.php(378): FreshRSS_importExport_Controller->addOpmlElements(Array, 'Actus Info')\n#2 /srv/FreshRSS/app/Controllers/importExportController.php(261): FreshRSS_importExport_Controller->addCategoryOpml(Array, NULL, false)\n#3 /srv/FreshRSS/app/Controllers/importExportController.php(219): FreshRSS_importExport_Controller->addOpmlElements(Array)\n#4 /srv/FreshRSS/app/Controllers/importExportController.php(84): FreshRSS_importExport_Controller->importOpml('<?xml version="...')\n#5 /srv/FreshRSS/app/Controllers/importExportController.php(155): FreshRSS_importExport_Controller->importFile('freshrss_typhoe...', '/tmp/phpoxYRGJ')\n#6 /srv/FreshRSS/lib/Minz/Dispatcher.php(118): FreshRSS_importExport_Controller- in /srv/FreshRSS/app/Controllers/importExportController.php on line 312`

**Comment by typhoe** [comment] 2019-09-09 15:08
Same functionality (restore of a zip save) works perfectly on the same install on Debian 9 (just tested right now)

**Comment by Alkarex** [comment] 2019-09-16 20:16
Hello,
I will try to have a look.
For the record, we have just landed a new DB export/import feature in the /dev branch https://github.com/FreshRSS/FreshRSS/pull/2496

**Comment by Alkarex** [comment] 2019-09-16 20:17
Could it be that you did not use the same lang in your source and target installations?

**Comment by Alkarex** [comment] 2019-09-16 20:21
While waiting for a proper fix, could you please try this quick fix?

Replace that line 312:

https://github.com/FreshRSS/FreshRSS/blob/80590daeb3627e5712be15fdc4bd98f0e2c40ea5/app/Controllers/importExportController.php#L312
by:

```php
$feed->_category($cat == null ? FreshRSS_CategoryDAO::DEFAULTCATEGORYID : $cat->id());
```

**Comment by typhoe** [comment] 2019-09-17 14:23
Thanks for answering.

I'm using the same language in both source and target.

The proposed fix doesn't seem to work.

The code changed:
```php
root@freshrss:~# sed -n '310,315p' /srv/FreshRSS/app/Controllers/importExportController.php   
                        // Create a Feed object and add it in DB  
                        $feed = new FreshRSS_Feed($url);  
                        //$feed->_category($cat->id());  
                        $feed->_category($cat == null ? FreshRSS_CategoryDAO::DEFAULTCATEGORYID : $cat->id());  
                        $feed->_name($name);  
                        $feed->_website($website);  
```
The import error log (before code changed, then after code changed)
```php
root@freshrss:~# tail /var/log/apache2/freshrss_error.log                                                                                                                                                            
[Tue Sep 17 16:00:21.657519 2019] [php7:warn] [pid 232] [client 192.168.1.201:33084] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/Controllers/indexController.php on line 49           
[Tue Sep 17 16:00:21.658819 2019] [php7:warn] [pid 232] [client 192.168.1.201:33084] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/layout/aside_feed.phtml on line 49                   
[Tue Sep 17 16:00:21.660002 2019] [php7:warn] [pid 232] [client 192.168.1.201:33084] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/FreshRSS/app/Controllers/indexC
ontroller.php on line 63
[Tue Sep 17 16:02:21.866536 2019] [php7:warn] [pid 228] [client 192.168.1.201:37474] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/views/javascript/nbUnreadsPerFeed.phtml on line 11
[Tue Sep 17 16:03:30.891338 2019] [php7:error] [pid 233] [client 192.168.1.201:40028] PHP Fatal error:  Uncaught Error: Call to a member function id() on null in /srv/FreshRSS/app/Controllers/importExportControlle
r.php:312\nStack trace:\n#0 /srv/FreshRSS/app/Controllers/importExportController.php(246): FreshRSS_importExport_Controller->addFeedOpml(Array, 'Actus Info')\n#1 /srv/FreshRSS/app/Controllers/importExportControlle
r.php(378): FreshRSS_importExport_Controller->addOpmlElements(Array, 'Actus Info')\n#2 /srv/FreshRSS/app/Controllers/importExportController.php(261): FreshRSS_importExport_Controller->addCategoryOpml(Array, NULL, 
false)\n#3 /srv/FreshRSS/app/Controllers/importExportController.php(219): FreshRSS_importExport_Controller->addOpmlElements(Array)\n#4 /srv/FreshRSS/app/Controllers/importExportController.php(84): FreshRSS_importE
xport_Controller->importOpml('<?xml version="...')\n#5 /srv/FreshRSS/app/Controllers/importExportController.php(155): FreshRSS_importExport_Controller->importFile('freshrss_typhoe...', '/tmp/phpnFPAWX')\n#6 /srv/F
reshRSS/lib/Minz/Dispatcher.php(118): FreshRSS_importExport_Controller- in /srv/FreshRSS/app/Controllers/importExportController.php on line 312
[Tue Sep 17 16:04:12.579437 2019] [php7:warn] [pid 229] [client 192.168.1.201:41550] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/Controllers/indexController.php on line 49
[Tue Sep 17 16:04:12.579567 2019] [php7:warn] [pid 229] [client 192.168.1.201:41550] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/layout/aside_feed.phtml on line 49
[Tue Sep 17 16:04:12.580047 2019] [php7:warn] [pid 229] [client 192.168.1.201:41550] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/FreshRSS/app/Controllers/indexC
ontroller.php on line 63
[Tue Sep 17 16:06:13.326646 2019] [php7:warn] [pid 232] [client 192.168.1.201:46050] PHP Warning:  Invalid argument supplied for foreach() in /srv/FreshRSS/app/views/javascript/nbUnreadsPerFeed.phtml on line 11
[Tue Sep 17 16:07:44.853440 2019] [php7:error] [pid 228] [client 192.168.1.201:49394] PHP Fatal error:  Uncaught Error: Call to a member function id() on null in /srv/FreshRSS/app/Controllers/importExportControlle
r.php:341\nStack trace:\n#0 /srv/FreshRSS/app/Controllers/importExportController.php(246): FreshRSS_importExport_Controller->addFeedOpml(Array, 'Actus Info')\n#1 /srv/FreshRSS/app/Controllers/importExportControlle
r.php(379): FreshRSS_importExport_Controller->addOpmlElements(Array, 'Actus Info')\n#2 /srv/FreshRSS/app/Controllers/importExportController.php(261): FreshRSS_importExport_Controller->addCategoryOpml(Array, NULL, 
false)\n#3 /srv/FreshRSS/app/Controllers/importExportController.php(219): FreshRSS_importExport_Controller->addOpmlElements(Array)\n#4 /srv/FreshRSS/app/Controllers/importExportController.php(84): FreshRSS_importE
xport_Controller->importOpml('<?xml version="...')\n#5 /srv/FreshRSS/app/Controllers/importExportController.php(155): FreshRSS_importExport_Controller->importFile('freshrss_typhoe...', '/tmp/phpIO1vDg')\n#6 /srv/F
reshRSS/lib/Minz/Dispatcher.php(118): FreshRSS_importExport_Controller- in /srv/FreshRSS/app/Controllers/importExportController.php on line 341
```
Just in case, here is my method of migrating the server:
Save of the postgreSQL DB (and export my user save with the web UI)
```bash
ssh $Server "systemctl stop apache2 ;sleep 3 ;cd /srv && pg_dump -U freshrss freshrss > /srv/freshrss_$(date +%Y%m%d).pgsql && tar zcvf /tmp/freshrss_$(date +%Y%m%d).tgz freshrss_*.pgsql FreshRSS git_update.sh && rm -f /srv/freshrss_$(date +%Y%m%d).pgsql"
```
Restore the PostgreSQL DB (and only then try the import of my save in the web UI)
```bash
ssh $Server "cd /srv/ && tar zxvf /tmp/${Server}_*.tgz && pg_dump -U freshrss freshrss < /srv/freshrss_$(date +%Y%m%d).pgsql"
```

**Comment by Alkarex** [comment] 2019-10-07 18:28
@typhoe I believe your lasts command is supposed to use `pg_restore` and not `pg_dump`. The errors you get are a sign of various errors in the database. If you like, I can look at your dump.
I suggest you try the new export/import through SQLite https://github.com/FreshRSS/FreshRSS/blob/dev/cli/README.md

**Comment by Alkarex** [comment] 2019-10-07 19:31
I have made a few tests but cannot reproduce. Closing for now because my guess is that there is a database corruption independent of FreshRSS, but feel free to provide more info or examples of dumps so I can investigate more.

**Closed as completed by Alkarex** 2019-10-07 19:31 UTC
