### ISSUE TITLE
[BUG] 1.23.0 breaks the feed list (not all unread are listed, just the first)

### ISSUE THREAD

**Issue by cmwg71** [FreshRSS/FreshRSS#6003] opened 2023-12-30 11:51 UTC
**Describe the bug**
With update to 1.23.0 feeds only show the frist unread message, even though there are more than just the one - this is across all feeds.

**To Reproduce**
Just use 1.23.0 and update feeds, they will show unread number and if you click on the feed itself, it will list only 1

**Expected behavior**
Obv. as bevor 1.23.0 with worked properly and all unread messages in a feed where listed.

**Screenshots**

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 11
- Browser: Brave
- FreshRSS version: 1.23.0
- Database version: MariaDB 10.5.21
- PHP version: PHP 8.1.26
- Installation type: root server with plesk

**Comment by Alkarex** [comment] 2023-12-30 12:11
Hello,
Could you try our `edge` version? A couple of related bugs have already been fixed

**Comment by cmwg71** [comment] 2023-12-30 12:53
hi there,
sadly same result on current edge. I guess it is a crhome engine issue then.

**Comment by Alkarex** [comment] 2023-12-30 12:56
No, it is very unlikely it has anything to do with your Web browser.
Please check your Web server logs, and your FreshRSS logs

**Comment by cmwg71** [comment] 2023-12-30 13:17
there does not seem to be any entry into FreshRSS log (from the UI), is there another log (and where) for it? 

checking webserver log next

**Comment by cmwg71** [comment] 2023-12-30 13:20
well the webserver does seem to get an error that could fit

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in [/var/www/vhosts/grams-it.com/feed.grams-it.com/app/views/index/normal.phtml](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Fapp%2Fviews%2Findex&subscriptionId=1&file=normal.phtml&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4):89\nStack trace:\n#0 [/var/www/vhosts/grams-it.com/feed.grams-it.com/app/views/index/normal.phtml](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Fapp%2Fviews%2Findex&subscriptionId=1&file=normal.phtml&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(89): array_slice()\n#1 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=View.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(93): include('...')\n#2 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=View.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(115): Minz_View->includeFile()\n#3 [/var/www/vhosts/grams-it.com/feed.grams-it.com/app/layout/layout.phtml](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Fapp%2Flayout&subscriptionId=1&file=layout.phtml&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(73): Minz_View->render()\n#4 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=View.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(93): include('...')\n#5 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=View.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(106): Minz_View->includeFile()\n#6 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=View.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(73): Minz_View->buildLayout()\n#7 [/var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/Dispatcher.php](https://grams-it.com:8443/smb/file-manager/code-editor?currentDir=%2Ffeed.grams-it.com%2Fvar%2Fwww%2Fvhosts%2Fgrams-it.com%2Ffeed.grams-it.com%2Flib%2FMinz&subscriptionId=1&file=Dispatcher.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F4)(59): Minz_View->build()\n#8 /var/www/vhosts/grams-it.com/fee...'

checking if i can get the full text of it

**Comment by cmwg71** [comment] 2023-12-30 13:22
sadly it is also cut off in the text file

[Sat Dec 30 14:16:28.544424 2023] [proxy_fcgi:error] [pid 2449626:tid 140717741561600] [client 178.201.246.29:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in /var/www/vhosts/grams-it.com/feed.grams-it.com/app/views/index/normal.phtml:89\nStack trace:\n#0 /var/www/vhosts/grams-it.com/feed.grams-it.com/app/views/index/normal.phtml(89): array_slice()\n#1 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php(93): include('...')\n#2 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php(115): Minz_View->includeFile()\n#3 /var/www/vhosts/grams-it.com/feed.grams-it.com/app/layout/layout.phtml(73): Minz_View->render()\n#4 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php(93): include('...')\n#5 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php(106): Minz_View->includeFile()\n#6 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/View.php(73): Minz_View->buildLayout()\n#7 /var/www/vhosts/grams-it.com/feed.grams-it.com/lib/Minz/Dispatcher.php(59): Minz_View->build()\n#8 /var/www/vhosts/grams-it.com/fee...'

**Comment by cmwg71** [comment] 2023-12-30 13:22
hope that gives you the info you need

**Comment by Alkarex** [comment] 2023-12-30 13:33
Are you sure this is the latest `edge` version?

This seems to be a duplicate of:
* https://github.com/FreshRSS/FreshRSS/issues/5975#issuecomment-1869318313
* https://github.com/FreshRSS/FreshRSS/issues/5981#issuecomment-1870635113

and was fixed in:
* https://github.com/FreshRSS/FreshRSS/pull/5978

**Comment by cmwg71** [comment] 2023-12-30 13:51
According to my Edge: Version 120.0.2210.91

**Comment by cmwg71** [comment] 2023-12-30 13:54
just tested on android 14 chrome browser - same issue

**Comment by cmwg71** [comment] 2023-12-30 14:01
and tested on Linux Mint 22.1 with current Brave browser also same issue.

**Comment by Alkarex** [comment] 2023-12-30 16:00
I meant FreshRSS's `edge` version :-)
It is not related to the Web browser at all.

**Comment by Alkarex** [comment] 2023-12-30 16:01
Version 1.23.1 of FreshRSS will be released shortly

**Closed as completed** 2023-12-30 16:01 UTC

**Comment by cmwg71** [comment] 2023-12-30 16:25
thanks for the quick and great work you are doing!

**Comment by Alkarex** [comment] 2023-12-30 16:31
https://github.com/FreshRSS/FreshRSS/releases/tag/1.23.1
