### ISSUE TITLE
SQL error updateFeed: database is locked for feed

### ISSUE THREAD

**Issue by widowild1** [FreshRSS/FreshRSS#5008] opened 2023-01-12 16:42 UTC
Hello,

I have this type of message, I don't understand why it blocks like that, I receive my last RSS feeds, but I have only errors in the logs.

My installation is under docker in production mode.

Currently I have about 11000 articles received.

`il y a 16 minutes	WebSub lease ends at 2023-01-12T15:33:09+01:00 and needs renewal: https://www.blogger.com/feeds/5208201180469430173/posts/default?redirect=false
⚠️	il y a 16 minutes	Error while WebSub unsubscribing from https://synology.blogspot.com/feeds/posts/default?redirect=false
❌	il y a 19 minutes	SQL error updateCachedValue: database is locked
❌	il y a 19 minutes	SQL error commitNewEntries: ["HY000",5,"database is locked"]
⚠️	il y a 19 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	il y a 19 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	il y a 19 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	il y a 19 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	il y a 19 minutes	SQL error updateFeed: database is locked for feed 645
❌	il y a 19 minutes	SQL error updateCachedValue: database is locked
⚠️	il y a 19 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	il y a 19 minutes	SQL error updateLastSeen: HY000: 5 database is locked while updating feed 645
❌	il y a 19 minutes	SQL error addEntry: HY000: 5 database is locked while adding entry in feed 645 with title: Projet DDosia : des volontaires mènent des attaques DDoS au nom de NoName(057)16
❌	il y a 19 minutes	SQL error addEntry: HY000: 5 database is locked while adding entry in feed 645 with title: Attaques DDoS, la réponse des cybercriminels aux événements sociopolitiques
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=47004 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=47002 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46996 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46993 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46989 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46987 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46984 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46982 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46980 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46976 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46974 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46972 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46970 in feed 645
❌	il y a 19 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46963 in feed 645
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46956 in feed 645
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46954 in feed 645
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46952 in feed 645
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.undernews.fr/?p=46949 in feed 645
⚠️	il y a 20 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	il y a 20 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	il y a 20 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	il y a 20 minutes	SQL error updateFeed: database is locked for feed 640
❌	il y a 20 minutes	SQL error updateCachedValue: database is locked
⚠️	il y a 20 minutes	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	il y a 20 minutes	SQL error updateLastSeen: HY000: 5 database is locked while updating feed 640
❌	il y a 20 minutes	SQL error addEntry: HY000: 5 database is locked while adding entry in feed 640 with title: RGPD : Les destinataires des données personnelles doivent être identifiés
❌	il y a 20 minutes	SQL error addEntry: HY000: 5 database is locked while adding entry in feed 640 with title: Des données sensibles du personnel de l'Académie de Lille publiées
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-violation-de-donnees-pas-de-preuve-de-piratage-selon-twitter-89183.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-frederic-bardeau-president-de-simplon--nous-allons-creer-des-formations-a-bac-5-89076.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-un-bug-informatique-bloque-les-vols-aux-etats-unis-89177.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-intel-officialise-ses-xeon-sapphire-rapids-avec-accelerateurs-activables-89174.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-sekoia-marie-le-xdr-au-renseignement-cyber-89169.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-la-valise-d-expleo-teste-la-resilience-cyber-des-voitures-89158.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-patch-tuesday-microsoft-demarre-2023-avec-98-correctifs-89168.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-yousign-promeut-alban-sayag-au-poste-de-ceo-89164.html in feed 640
❌	il y a 20 minutes	SQL error updateEntry: HY000: 5 database is locked while updating entry with GUID https://www.lemondeinformatique.fr/actualites/lire-les-premiers-pas-de-chatgpt-dans-la-cyber-malveillance-89163.html in feed 640
`

**Comment by Emporea** [comment] 2023-09-01 13:05
I have the same problem.

Freshrss_db ( my mariadb docker container ) has a lot of cpu usage in 24hours.

My database is about 2gb in size cause i dont want to delete any article.

This is some example log data.




Log Level | Timestamp | Log Message
-- | -- | --
  | 2023-09-01 14:42:18 | SQL error addEntry: HY000: 1205 Lock wait timeout exceeded; try  restarting transaction while adding entry in feed 42 with title: Nikki  Haley calls Senate 'most privileged nursing home in the country,’ says  McConnell freeze-up was 'sad'
  | 2023-09-01 14:40:15 | cURL error 22: The requested URL returned error: 502  [https://www.morgenpost.de/?service=Rss&amp;bot-access=true]
  | 2023-09-01 14:33:25 | FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET  `lastUpdate`=?, error=? WHERE id=? : ["HY000",1205,"Lock wait timeout  exceeded; try restarting transaction"]
  | 2023-09-01 14:23:26 | FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET  `lastUpdate`=?, error=? WHERE id=? : ["HY000",1205,"Lock wait timeout  exceeded; try restarting transaction"]
  | 2023-09-01 14:08:34 | SQL error updateCachedValue: Lock wait timeout exceeded; try restarting transaction
  | 2023-09-01 13:38:33 | FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET  `lastUpdate`=?, error=? WHERE id=? : ["HY000",1205,"Lock wait timeout  exceeded; try restarting transaction"]
  | 2023-09-01 13:18:24 | FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET  `lastUpdate`=?, error=? WHERE id=? : ["HY000",1205,"Lock wait timeout  exceeded; try restarting transaction"]
  | 2023-09-01 13:14:22 | SQL error addEntry: HY000: 1205 Lock wait timeout exceeded; try  restarting transaction while adding entry in feed 25 with title:  Ex-Ministerpräsident Albig wird Lobbyist für Tabakkonzern Philip Morris
  | 2023-09-01 13:13:32 | SQL error addEntry: HY000: 1205 Lock wait timeout exceeded; try  restarting transaction while adding entry in feed 25 with title:  Faktenfinder: Spahns zweifelhafte Zahlen zum Bürgergeld


My innodb_lock_wait_timeout is 50. should i increase it?
What could be the cause of this problem and do i suffer dataloss? How can I be sure that no articles get dropped?

**Comment by Alkarex** [comment] 2023-09-01 13:08
I am investigating some paths, which may lead to database locks. One of them should be patched in https://github.com/FreshRSS/FreshRSS/pull/5625

**Comment by Emporea** [comment] 2023-09-01 13:10
This is what mariadb tells me is going on when the cpu usage is high from the mariadb container.

```
MariaDB [(none)]> SHOW PROCESSLIST;
+------+----------+-------------------+----------+---------+------+---------------------------------+------------------------------------------------------------------------------------------------------+----------+
| Id   | User     | Host              | db       | Command | Time | State                           | Info                                                                                                 | Progress |
+------+----------+-------------------+----------+---------+------+---------------------------------+------------------------------------------------------------------------------------------------------+----------+
| 1163 | freshrss | xxx | freshrss | Query   |    8 | Waiting for table metadata lock | ALTER TABLE `freshrss_empo_entrytmp` MODIFY `guid` VARCHAR(760) CHARACTER SET latin1 COLLATE latin1_ |    0.000 |
| 1164 | freshrss | xxx | freshrss | Execute |   24 | Sending data                    | UPDATE `freshrss_empo_feed` SET `cache_nbEntries`=(SELECT COUNT(e1.id) FROM `freshrss_empo_entry` e1 |    0.000 |
| 1165 | freshrss | localhost         | NULL     | Query   |    0 | starting                        | SHOW PROCESSLIST                                                                                     |    0.000 |
+------+----------+-------------------+----------+---------+------+---------------------------------+------------------------------------------------------------------------------------------------------+----------+
3 rows in set (0.000 sec)
```

**Comment by Emporea** [comment] 2023-09-01 17:53
Thanks for the quick reply.
Will there be any changes to know of?

Will it still be valid to just call the actualize_script.php?

**Comment by Emporea** [comment] 2023-09-01 19:53
I would really like to shut down the container of freshrss_db. The cpu usage is so high, and the I/O Bandwith is pretty high. I dont want to host any malicious software or crypto-mining by accident. Its just very suspicious and i dont understand why its doing this.

**Comment by Alkarex** [comment] 2023-09-01 20:07
Yes, you can still call `actualize_script.php`

**Comment by Alkarex** [comment] 2023-09-06 19:58
Could you please try again with the latest edge version of FreshRSS?

**Comment by Emporea** [comment] 2023-09-07 04:21
Thank you. I installed the `edge` version via docker just now. Before it was `latest`. Its hard to tell yet.
I have not gotten these errors in the last 4 days or so.

`SQL error addEntry: HY000: 1205 Lock wait timeout exceeded; try restarting transaction while adding entry...`

Also

`FreshRSS_FeedDAO::updateLastUpdate error: UPDATE _feed SET lastUpdate=?, error=? WHERE id=? : ["HY000",1205,"Lock wait timeout exceeded; try restarting transaction"]`

But I also updated mariadb from 10.5 to 10.6, this might not have any effect, but who knows.

I run the actualize script every 30 minutes.


Secondly, the site still crashes and I get `504 Gateway Time-out` errors when I "Mark all as read" (no matter if 1 new article or 30,000), manually purge through all the feeds (I want to keep all of them so its just a database and freshrss stresstest button for me ^^) or optimise the database. ( `1 266 243 articles (2.05 GiB) ` ).

I am waiting for the database cpu and disk usage to go down, then I can get back to the freshrss web ui without 504.

I will stay on :edge for a while and try to observe the problems this issue was originally created for over the next few days or so.
Sorry for mixing up different issues.

**Comment by Alkarex** [comment] 2023-09-07 08:38
Hum *Mark all as read* should not take that long. Which button for * Mark all as read*, more precisely?

**Comment by Alkarex** [comment] 2023-09-07 08:54
Can you try to manually run and time the following query?

```sql
UPDATE `freshrss_empo_feed` f LEFT OUTER JOIN (
	SELECT e.id_feed, COUNT(*) AS nbUnreads
	FROM `freshrss_empo_entry` e
	WHERE e.is_read = 0
	GROUP BY e.id_feed
) x ON x.id_feed = f.id
SET f.`cache_nbUnreads` = COALESCE(x.nbUnreads, 0);
```

**Comment by Alkarex** [comment] 2023-09-07 09:08
And compare with the execution time of the query with use for PostgreSQL / SQLite:

```sql
UPDATE freshrss_empo_feed
SET `cache_nbUnreads`=(
	SELECT COUNT(*) AS nbUnreads FROM freshrss_empo_entry e
	WHERE e.id_feed=freshrss_empo_feed.id AND e.is_read=0);
```

**Comment by Emporea** [comment] 2023-09-07 10:09
Will test later.

But,` FROM alex_entry e` ?
Will that work?

**Comment by Emporea** [comment] 2023-09-07 10:15
In blue is the button i use for marking all as read.

I just did that and got these logs.



  | 2023-09-07 12:13:05 | SQL error FreshRSS_EntryDAO::markReadEntries["HY000",1205,"Lock wait timeout exceeded; try restarting transaction"]
-- | -- | --

![IMG_20230907_121311](https://github.com/FreshRSS/FreshRSS/assets/21969523/4ad415c2-b6f8-44f0-8083-cf6bcfdb18fd)

**Comment by Alkarex** [comment] 2023-09-07 10:34
> But,` FROM alex_entry e` ?
> Will that work?

Hehe no, wrong copy/paste edit, trying to adapt to your DB. I just fixed the request

**Comment by Alkarex** [comment] 2023-09-10 14:00
https://github.com/FreshRSS/FreshRSS/pull/5648

**Comment by Alkarex** [comment] 2023-09-10 15:19
More locks removed in https://github.com/FreshRSS/FreshRSS/pull/5649
Tests welcome

**Comment by Emporea** [comment] 2023-09-10 15:55
Hey. Thanks for the work and the ping.
Now that I have 11000 unread articles, I ran the queries on 1.21.1-dev.

See for yourself, its pretty clear.

```
MariaDB [freshrss]> UPDATE `freshrss_empo_feed` f LEFT OUTER JOIN (
    -> SELECT e.id_feed, COUNT(*) AS nbUnreads
    -> FROM `freshrss_empo_entry` e
    -> WHERE e.is_read = 0
    -> GROUP BY e.id_feed
    -> ) x ON x.id_feed = f.id
    -> SET f.`cache_nbUnreads` = COALESCE(x.nbUnreads, 0);
Query OK, 0 rows affected (0.237 sec)
Rows matched: 36  Changed: 0  Warnings: 0
```

```
MariaDB [freshrss]> UPDATE freshrss_empo_feed
    -> SET `cache_nbUnreads`=(
    -> SELECT COUNT(*) AS nbUnreads FROM freshrss_empo_entry e
    -> WHERE e.id_feed=freshrss_empo_feed.id AND e.is_read=0);
Query OK, 0 rows affected (2 min 11.998 sec)
Rows matched: 36  Changed: 0  Warnings: 0
```

Ran it a second time. Got 0.244 sec for the first one and 2 min 13.592 sec, so pretty consistently bad. ( no logs produces by this )

**Comment by Emporea** [comment] 2023-09-10 16:10
Your mariadb tests seem to be way faster. Especially since the PR favors the one that takes 2 minutes for me these are a not good news. Strange. What could it be?

**Comment by widowild1** [comment] 2023-09-10 16:29
I've updated the version of freshrss (edge)
I have 15000 articles and 2000 feeds (94 439 articles (372.19 MiB)).
and I got this type of message after a database optimization via freshrss. 
https://privatebin.net/?7759ce01a6d8c138#3acJWxXu5zEfNWn6fzJ8Ku2q719CXgZpdxWtFXo5ARup

EDIT: I just purged again via freshrss, the number of items has increased to: 85 841 articles (363.04 MiB) and I also launched an optimization immediately, but I no longer get this type of error message.

I'll give you a call in the next few days if the message appears.

**Comment by Alkarex** [comment] 2023-09-10 17:03
> Your mariadb tests seem to be way faster. Especially since the PR favors the one that takes 2 minutes for me these are a not good news. Strange. What could it be?

@Emporea When you test, please make sure that you break the cache, by manually marking as read some articles from a few different feeds.
2 minutes is a sign of some kind of database sub-optimal configuration. Please check the `EXPLAIN` commands in https://github.com/FreshRSS/FreshRSS/pull/5648 and compare with what you get on your side. Let's continue the discussion in https://github.com/FreshRSS/FreshRSS/pull/5648 for the performance of that specific query. For sure when you have a request that takes that long, you will observe some locks for some other parallel requests

**Closed as completed** 2023-09-12 08:43 UTC
Labels: Bug (unconfirmed), Support
