### ISSUE TITLE
Sharing by print gives a blank page with only the text "undefined" on it

### ISSUE THREAD

**Issue by sbrl** [FreshRSS/FreshRSS#2130] opened 2018-11-16 23:52 UTC
Hey! I've recently set up _FreshRSS_ as an alternative to _Miniflux 1_ (v2 uses PostgreSQL exclusively, and I don't want a PostgreSQL database server!), and been generally happy with with actually.

I've encountered a bug though in the sharing system. I 'print' things often to a virtual PDF printer I've got setup. If I go to share -> print in FreshRSS, I get the text "undefined" on a white page. I'm including an image and a copy of the resulting PDF at the bottom of this report. 

![selection_092](https://user-images.githubusercontent.com/9929737/48652868-ab028e00-e9f9-11e8-94b9-721705b50d47.png)

Here's the PDF when I print:
[mozilla.pdf](https://github.com/FreshRSS/FreshRSS/files/2591264/mozilla.pdf)

**Comment by Alkarex** [comment] 2018-11-17 19:13
Hello @sbrl and welcome :-)
I cannot reproduce the problem.
Tested with Firefox on Ubuntu 18.04, Firefox + Chrome + Edge on Windows.
Do you have any information in your browser console?
Could you please try with another browser?

**Comment by sbrl** [comment] 2018-11-17 21:41
Ah, yeah I do get something in the console:

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
FreshRSS waiting for Sticky-kit… main.js:521:4
FreshRSS init done. main.js:1550:3
Content Security Policy: The page's settings blocked the loading of a resource at inline ("default-src"). i:1:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! i
Content Security Policy: The page's settings blocked the loading of a resource at inline ("default-src").
i:1:1
Content Security Policy: The page's settings blocked the loading of a resource at inline ("default-src").
```

**Comment by sbrl** [comment] 2018-11-17 21:43
Tried Chrome, and can still reproduce - though nothing of interest in the console. I'm using the dark theme, if that helps.

**Comment by Alkarex** [comment] 2018-11-17 22:06
Would you mind making a test account for me in your FreshRSS instance? So I can see if it is something due to your instance, or due to your client. If not, I will make you a test instance.

**Comment by Alkarex** [comment] 2018-11-17 22:08
I am guessing from your screenshot that you are using Ubuntu, aren't you? Which version?

**Comment by Alkarex** [comment] 2018-11-17 22:12
Screenshot using Firefox in Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/1008324/48666246-3e04fc00-eabe-11e8-9e50-9a61427a6a5f.png)

**Comment by sbrl** [comment] 2018-11-18 17:38
Yep, it's Ubuntu - v18.04 with the latest version of Firefox.

I've created an account for you at my server. Is there a private way I can give you the login details, @Alkarex?

**Comment by Alkarex** [comment] 2018-11-18 18:49
@sbrl Please find [my e-mail address here](https://alexandre.alapetite.fr/cv/).

**Comment by sbrl** [comment] 2018-11-18 20:49
Send & encrypted with GPG.

**Comment by Alkarex** [comment] 2018-11-19 23:16
@sbrl Well received. Tested from your instance with Firefox 63 (64 bits) on Ubuntu 18.04, as well as Firefox 63 (64 bits) on Windows 10, both without problem. So it seems to be client-related. Could you please try with the exact same account than the one you just sent me?

![image](https://user-images.githubusercontent.com/1008324/48740880-72f98600-ec59-11e8-9315-635f19a04d8a.png)

**Comment by Alkarex** [comment] 2018-11-20 21:31
@sbrl I cannot really think of what could be different between the two accounts. Did you observe the problem on some specific feeds, or all feeds?
What database do you use? (not that it makes a difference for this bug, just to know what could be done to export the data)

**Comment by Alkarex** [comment] 2018-11-20 21:32
Hum, maybe some settings could be different between your two accounts, one of which could interfere... E.g. shortcuts, extensions, mark-as-read options...

**Comment by sbrl** [comment] 2018-11-20 22:42
I've observed it on 2-3 different feeds now, so I think it's safe to say it's practically all feeds, though the they are all imported from Miniflux.

I use an SQLite3 database. Shall I send you a copy of the database for inspection?

**Comment by Alkarex** [comment] 2018-11-20 22:44
Yes @sbrl , if not too confidential, please send me your SQLite database, so I can maybe reproduce the problem. Same channel as above.

**Comment by sbrl** [comment] 2018-11-20 23:02
@Alkarex Sent. The _Firefox Send_ link expires after 1 download or 24 hours, so if you need me to send it again, just ask :-)

**Comment by Alkarex** [comment] 2018-11-21 09:11
@sbrl Received :-) Will test tonight

**Comment by Alkarex** [comment] 2018-11-24 13:13
@sbrl Thanks, I can reproduce the problem with the "Show articles unfolded by default" option. Will fix!

https://github.com/FreshRSS/FreshRSS/blob/01c4cd83186d3c13744b7fa97893ce83e40976f5/p/scripts/main.js#L1303-L1322

**Comment by sbrl** [comment] 2018-11-24 14:57
Ah, awesome! Glad I've been able to help in tracking down a bug. I await a fix :D

**Comment by Alkarex** [comment] 2018-11-24 21:40
Fixed in https://github.com/FreshRSS/FreshRSS/pull/2148 
Tests welcome!

**Closed as completed** 2018-12-16 13:48 UTC

**Comment by sbrl** [comment] 2018-12-16 17:14
Thanks so much :D
