### ISSUE TITLE
[Feature] Update information about native apps

### ISSUE THREAD

**Issue by dumprop** [FreshRSS/FreshRSS#3530] opened 2021-03-15 21:00 UTC
https://github.com/jangernert/FeedReader/
"This project is no longer activily maintained!

I am for quite some time already working on a spiritual successor called NewsFlash."

Also cross-platform [RSS guard](https://github.com/martinrotter/rssguard/releases) have a good stability/functionality (it crashed only on first run), but it have slow syncing (tested w/ freshrss)

**Comment by Alkarex** [comment] 2021-03-15 22:19
Thanks for the info 👍🏻 

Would you please send a PR to update the info in our tables?

https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps
https://github.com/FreshRSS/FreshRSS/blob/edge/README.fr.md#apis-et-applications-natives

And let us know about your progress :-)

**Comment by martinrotter** [comment] 2021-05-18 06:11
Hello, author of RSS Guard here.

https://github.com/FreshRSS/FreshRSS/pull/3627

Also I will check the sync speed to make RSS Guard work faster with FreshRSS.

**Comment by martinrotter** [comment] 2021-05-18 06:36
Follow-up: Just tested local FreshRSS instance (docker/linux) and imported 150 feeds. I added it to RSS Guard, observations:
- fetching of list of FEEDS is slow, because RSS Guard downloads icon of each feed (will fix this up), but this is normally not a problem because use sync list of FEEDS not that often (only after you add/delete some feed) **EDIT: This is now fixed in [master] branch.**
- fetching of MESSAGES is quite fast in my opinion - i now fetched 2400 messages for 150 feeds in 30 seconds (initial message syncing)

Let me know if you find any problems or suggest ways of speeding it up.

**Comment by aledeg** [comment] 2021-05-18 11:19
I've just merged #3627. Does it covers what is needed to close that issue?

**Comment by dumprop** [comment] 2021-05-19 10:32
> I've just merged #3627. Does it covers what is needed to close that issue?

No, there no information that fluent reader have ios version too
Probably I will add that

**Comment by martinrotter** [comment] 2021-05-20 05:23
> it crashed only on first run

Is this reproducible for you? Could you file a bug ticket?

**Comment by dumprop** [comment] 2021-05-20 15:56
> > it crashed only on first run
> 
> Is this reproducible for you? Could you file a bug ticket?

Currently, no (also not tested before), but currently it doesn't work well without restart ([created issue there](https://github.com/martinrotter/rssguard/issues/413))

**Comment by math-GH** [comment] 2022-08-28 11:56
Any updates here @martinrotter @dumprop ? Or could we close this ticket?

**Comment by dumprop** [comment] 2022-08-28 15:14
> Any updates here @martinrotter @dumprop ? Or could we close this ticket?

Yes, thanks @martinrotter !

**Closed as completed** 2022-08-28 15:14 UTC
Labels: Documentation :books:, API :handshake:, Vote to close
