### ISSUE TITLE
Article list  displayed with flicker

### ISSUE THREAD

**Issue by Cantello** [FreshRSS/FreshRSS#2701] opened 2019-12-03 20:21 UTC
I recently instlaled FreshRSS via docker on my home server and reading via a mobile app (Reeder4 on iOS in this case) works fine, but when reading via the web interface, there is some nasty flickering and/or overlay issues going on. I tried with Firefox, Chrome & Vivaldi and with the Chrome-based browsers, there is heavy flickering, whereas with Firefox there are overly issues for the article list - each time while hovering the mouse over the article list.

FreshRSS version is 1.15.3, running via linuxserver/freshrss docker on Ubuntu 18.04. Browsers were the respective latest version on Windows-10. The theme was changed with no effects.

![image](https://user-images.githubusercontent.com/594700/70085434-82ebca00-1610-11ea-9ab6-179123412b33.png)

![freshrss_flicker](https://user-images.githubusercontent.com/594700/70086388-9861f380-1612-11ea-9b67-138ee3541cae.gif)

**Comment by Frenzie** [comment] 2019-12-03 20:38
Presumably caused by #2487.

Edit: can't confirm with author display + Ansum.

**Comment by Cantello** [comment] 2019-12-03 20:40
> Presumably caused by #2487.

You were totally right. I was searching for keywords like _flicker_ or _display error_ but I did change that option before and did not think about it.

Should I leave this open or can it be closed? I do not see any mention of display errors with regards to author display.

**Comment by Frenzie** [comment] 2019-12-03 20:42
@Cantello If it's caused by that option it's still a bug! I was just trying to pinpoint the cause so it can be fixed. ;-)

Could you please post the precise settings (whether in a screenshot or words) that cause the problem?

**Comment by Cantello** [comment] 2019-12-03 20:43
Displaying the author does not work without the mentioned errors but my issue is solved.

**Comment by Cantello** [comment] 2019-12-03 20:45
Simply enabling the author display on the top line creates this behaviour. If nothing else is changed, the display is now flicker-free.

![image](https://user-images.githubusercontent.com/594700/70088221-1d024100-1616-11ea-9c0c-e9a209af2c61.png)

**Comment by Frenzie** [comment] 2019-12-03 20:47
This is with the Ansum theme? Like I said, I can't reproduce it.

**Comment by Alkarex** [comment] 2019-12-03 21:07
I have just tried this option and it is also broken for me (Firefox):
![image](https://user-images.githubusercontent.com/1008324/70089781-2b9e2780-1619-11ea-8d40-5767b3d8c9a2.png)
I thought I had tested it before merge, so maybe there has been an additional change since

**Comment by Frenzie** [comment] 2019-12-03 22:18
I just realized I tested it on my personal instance where I apply the multiline CSS I wrote. I didn't test it on a Docker dev instance (because I was on Windows). That probably explains it. In which case as an alternative workaround you should be able to use https://github.com/FreshRSS/Extensions/tree/master/xExtension-TitleWrap

**Comment by triatic** [comment] 2019-12-27 22:20
The extension suggested by @Frenzie works well for me in curing the issue. Is it worth rolling the TitleWrap extension into core as a fix?

**Comment by Frenzie** [comment] 2019-12-28 07:53
We (or at least I) want roughly that as part of the core, but as a fix for this issue it'd be a bit like a sledgehammer.

**Comment by triatic** [comment] 2019-12-28 15:23
I had a quick look at the CSS and it doesn't seem to be a :hover issue. It's something in Javascript then?

**Comment by Frenzie** [comment] 2019-12-29 15:46
If you disable the position:absolute in `.flux:not(.current):hover .item.title` (in template.css) that seems to resolve the issue. Note that browsers are oddly sneaky about `:hover` and the like and you have to explicitly enable display of those pseudo-classes.

**Comment by triatic** [comment] 2019-12-29 17:08
Yes that does seem to fix it. It still looks ugly without TitleWrap though, due to 40px line-height being applied to both the title and author.

**Comment by marienfressinaud** [comment] 2020-01-07 16:45
Maybe we can change the behaviour to always display the full title on multilines. This is what I chose for [my own theme](https://github.com/flusio/xTheme-Flus) and I think it's ok. I can't remember why we chose to wrap the lines. It would save us a lot of headaches!

![Capture d’écran - 2020-01-07 à 17 43 54](https://user-images.githubusercontent.com/1436309/71912175-4cf0b700-3175-11ea-9b65-0e51fb601ee2.png)

**Comment by Frenzie** [comment] 2020-01-07 16:52
@marienfressinaud Presumably because of IE8/9, or something to that effect?

I've been using my own modification (as available in that extension) to great satisfaction for quite a while now, but the alignment is ever so slightly off. I think the way it looks on your screenshot is worse still, even if it's technically better aligned. ;-) And as I said in the relevant issue, my modification is a hack on top of the current CSS, which should be rewritten for a proper PR. I haven't gotten around to actually fixing it up properly though, neither in rewriting the CSS nor in figuring out the cause of the slight misalignment.

![Screenshot_2020-01-07_17-47-21](https://user-images.githubusercontent.com/202757/71912481-ddc79280-3175-11ea-967b-62f6c048af4c.png)

On the flipside, just including the CSS I wrote in the main repo would probably motivate me or someone else better to actually take fix it up properly. :-P It's not actually buggy or anything, just slightly suboptimal.

**Comment by aledeg** [comment] 2020-01-07 17:00
Seeing the screen preview made me realize that there is a lot of wasted space around all the buttons on top. This might need some work to better use it.

**Comment by Frenzie** [comment] 2020-01-07 17:04
@aledeg I don't think that's much of an issue. If you tap on a title it scrolls there, and it's rather useful to be able to easily use this functionality. Hiding just about every action behind some `…` like many interfaces do would not be an improvement to me.

That being said… everything could basically move up a line, and it may be possible to reduce it by a further line by doing that expanding search bar thing (although once again, I'm not the biggest fan of that principle).

**Comment by marienfressinaud** [comment] 2020-01-07 17:22
Well, it's really more a matter of taste and both alignments are ok to me ;)

I wouldn't try to rework this part of the interface too much without the insights of a UX designer. It would be easy to spend a lot of time in development and discussions for a result just slightly better (and maybe worse in some contexts). I mean if this "menu" is raising so many questions and problems, maybe it's not the best interface choice?

**Comment by Frenzie** [comment] 2020-01-07 21:02
There are actually two things wrong with the vertically centered layout.

1. Unpredictability in the UI is not a good thing: it causes users to pause. The vertically centered icons are predictable only in an abstract sense, while icons at the top gives you a dependable location. You can already see three (!) distinct icon locations in the screenshot above, so you never know where to expect them.
2. It's not very good simply because they're not at the top. We scan roughly from top to bottom, left to right. This means users see the text before they see the icon, while the favicon is a vital identifier.

It's basically like [this](https://uxmovement.com/buttons/where-to-place-icons-next-to-button-labels/):
![icon-placement-buttons](https://user-images.githubusercontent.com/202757/71929158-525ff880-3199-11ea-9b2e-fb0944708f89.png)

**Comment by marienfressinaud** [comment] 2020-01-08 10:25
Ah, my bad, you're right! My message was contradictory and I only considered how it looks and not the UX aspect (while pointing that UX is important in the next paragraph :upside_down_face: ) I'll patch my theme then :)

**Closed as completed** 2020-01-17 07:11 UTC
Labels: UI :art:, help wanted

**Comment by marienfressinaud** [comment] 2020-01-17 07:13
I fixed this issue with a quick patch, let's continue the discussion about multi-lines in https://github.com/FreshRSS/FreshRSS/issues/2344 :)
