### ISSUE TITLE
How to get HTML 5 Notifications to work?

### ISSUE THREAD

**Issue by cdemi** [FreshRSS/FreshRSS#2733] opened 2019-12-24 13:28 UTC
I have recently installed FreshRSS in docker and am very impressed. I have managed to setup everything but I cannot seem to get HTML 5 notifications to work. 

I have accepted the browser popup for Notifications and the site is running under HTTPS behind traefik
![image](https://user-images.githubusercontent.com/8025435/71414924-81368480-2659-11ea-86f5-dde800996fd5.png)

However if new feeds come in (either via WebSub or because the actuator detects new feeds, I never get an HTML 5 notification.

Am I missing something?

**Comment by elmicha** [comment] 2019-12-31 21:05
Are you using [Firefox 72](https://hacks.mozilla.org/2019/11/upcoming-notification-permission-changes-in-firefox-72/) perhaps?

I think FreshRSS needs to get a button that requests the notification permission.

I get "Requesting Notification permission outside a short running user-generated event handler is deprecated and will not be supported in the future." in the console of Firefox 71, and Firefox 72 seems to be when that will stop working.

**Comment by cdemi** [comment] 2019-12-31 21:09
I am using latest Chrome version. I don't have the version at hand
________________________________

**Comment by cdemi** [comment] 2020-01-02 14:35
Chrome version is **79.0.3945.88 (Official Build) (32-bit)**

**Comment by elmicha** [comment] 2020-01-03 17:21
I tested it with the same Chrome version using an nginx reverse proxy for HTTPS, and it works here.

**Comment by cdemi** [comment] 2020-01-03 17:23
I am using Traefik as a reverse proxy for HTTPS. Can you point me in the right direction to help me debug this out?

**Comment by elmicha** [comment] 2020-01-03 17:58
I'm only a user like you, I just thought that I had a good idea when I stumbled on your issue. But I'll try.

Can you try with [a new profile](https://developer.chrome.com/devtools/docs/clean-testing-environment)? [Apparently](https://developer.chrome.com/devtools/docs/clean-testing-environment) you can't get notifications in Incognito mode.

If you open the Web console with F12, you can select the Console tab and enter `notifs_html5_show(27)` - that should show the notification (it does here).

**Comment by marienfressinaud** [comment] 2020-01-07 16:31
Hello @cdemi ! As suggested by @elmicha you might want to try with a fresh new profile, without any Chrome plugins enabled. You can also try with another browser, preferably with Firefox.

The problem is more probably related to some restrictions on your desktop than to your proxy setup. I disable all kind of notifications at a level system myself, so I never see the notifications ^^

As pointed by @elmicha, we should reconsider the workflow to ask notification permissions to the user anyway because Firefox is deprecating the current one.

**Comment by ParadingLunatic** [comment] 2020-06-08 20:19
I have a somewhat similar issue.  When I first signed in using Chrome it prompted me about notifications, so I said yes.  But I never got notifications.  The only time I notice I get notifications is if I go through all but one of my unread articles.  If I leave one article unread, the next time I receive new articles, I get a notification.  The same thing happened in Firefox.

**Comment by math-GH** [comment] 2022-08-28 19:30
Is it still relevant or can we close it?

**Comment by ParadingLunatic** [comment] 2022-08-28 19:33
I don't seem to be having notification issues anymore.  Seems to consistently work now.

**Closed as completed** 2022-08-28 19:34 UTC
Labels: Vote to close, Docker 🐋, Support
