### ISSUE TITLE
[BUG] Bookmarklet / API add feed with & signes

### ISSUE THREAD

**Issue by fatuuse** [FreshRSS/FreshRSS#4767] opened 2022-10-23 20:57 UTC
**Describe the bug**
I use the API to add a new feed link to FreahRSS (with a button on rss-bridge)
i/?c=feed&a=add&url_rss=%s
But that one will not support an link with additional & signes. So I have to code them in php with urlencode, but they are not coded back to just &, but keep coded as &amp; and not working. 

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0
- Database version: mariadb
- PHP version: 8.0

**Comment by aledeg** [comment] 2022-10-23 21:51
Could you post the exact URL you're trying to add? Thank you!

**Comment by fatuuse** [comment] 2022-10-24 14:14
https://feeds.test.com/i/?c=feed&a=add&url_rss=https%3A%2F%2Frss-bridge.test.com%2Faction%3Ddisplay%26amp%3Bbridge%3DDuckDuckGo%26amp%3Bu%3Dtest%26amp%3Bsort%3D%252Bsort%253Adate%26amp%3B_cache_timeout%3D21600%26amp%3Bformat%3DAtom
in Fresh form:
https://rss-bridge.test.com/action=display&amp;bridge=DuckDuckGo&amp;u=test&amp;sort=%2Bsort%3Adate&amp;_cache_timeout=21600&amp;format=Atom

or

https://feeds.test.com/i/?c=feed&a=add&url_rss=https://rss-bridge.test.com/action=display&bridge=DuckDuckGo&u=test2&sort=%2Bsort%3Adate&_cache_timeout=21600&format=Atom
in Fresh form:
https://rss-bridge.test.com/action=display

**Comment by math-GH** [comment] 2022-10-31 17:58
I cannot reproduce it.
Which error message do you get? Could you please support us with a screen shot?

**Comment by fatuuse** [comment] 2022-10-31 19:26
No error message. 

If I click on this link:
https://feeds.test.com/i/?c=feed&a=add&url_rss=https://rss-bridge.test.com?action=display&bridge=DuckDuckGo&u=test2&sort=%2Bsort%3Adate&_cache_timeout=21600&format=Atom

It will cut the link in the add input form at the next & sign. 
That's not the whole url for the atom feed. 

If i convert the url in rss-bridge with som urlencode the & are converted to &amp; and fresh rss won't convert them back to a simple & sign and it will fail.

![Screenshot_20221031-202451](https://user-images.githubusercontent.com/26528052/199092791-ba18c88e-d3e9-4db0-8d4e-e8e3dae2a7f9.png)

**Comment by math-GH** [comment] 2022-10-31 19:30
Please check the URL:

`...&url_rss=https://rss-bridge.test.com/action=display&bridge.....`

there is one `=` too much (between `action` and `display`)

**Comment by fatuuse** [comment] 2022-10-31 20:59
> Please check the URL:
> 
> `...&url_rss=https://rss-bridge.test.com/action=display&bridge.....`
> 
> there is one `=` too much (between `action` and `display`)

That's right. The link should be https://feeds.test.com/i/?c=feed&a=add&url_rss=https://rss-bridge.test.com?action=display&bridge=DuckDuckGo&u=test2&sort=%2Bsort%3Adate&_cache_timeout=21600&format=Atom

But this will still cut the link with API /i/?c=feed&a=add&url_rss=%s 
Before the first & in a RSS feed with query strings.

**Comment by math-GH** [comment] 2022-10-31 21:10
> https://feeds.test.com/i/?c=feed&a=add&url_rss=https%3A%2F%2Frss-bridge.test.com%2Faction%3Ddisplay%26amp%3Bbridge%3DDuckDuckGo%26amp%3Bu%3Dtest%26amp%3Bsort%3D%252Bsort%253Adate%26amp%3B_cache_timeout%3D21600%26amp%3Bformat%3DAtom 

It works for me:
![grafik](https://user-images.githubusercontent.com/1645099/199111025-dd286aaa-4dcf-44a3-8d20-50990d5a4fe0.png)

![grafik](https://user-images.githubusercontent.com/1645099/199111442-5e9b3dbb-9c51-484f-82c1-dc632a96eee6.png)

**Comment by fatuuse** [comment] 2022-11-01 08:31
> ![grafik](https://user-images.githubusercontent.com/1645099/199111442-5e9b3dbb-9c51-484f-82c1-dc632a96eee6.png)

That's right. It work in the way that the full url will show up in the input form. But won't work in FreshRSS because &amp; are not translated to &. I have to manually remove amp; from &. 
It not a big issue, but just some extra work.  


Each parameter between each & are used in rss bridge to create the right atom feed.

**Comment by Alkarex** [comment] 2022-11-02 22:19
The `url_rss` parameter must be URL-encoded.

Example of raw URL: `https://alexandre.alapetite.fr/tag/socialRSS?a=1&b=2`

Must become: `https://freshrss.example.net/i/?c=feed&a=add&url_rss=https%3A%2F%2Falexandre.alapetite.fr%2Ftag%2FsocialRSS%3Fa%3D1%26b%3D2`

Please try with that link (adapted to your server name) and report.

---

@fatuuse You write:

> https://feeds.example.net/i/?c=feed&a=add&url_rss=https%3A%2F%2Frss-bridge.example.net%2Faction%3Ddisplay%26amp%3Bbridge%3DDuckDuckGo%26amp%3Bu%3Dtest%26amp%3Bsort%3D%252Bsort%253Adate%26amp%3B_cache_timeout%3D21600%26amp%3Bformat%3DAtom

This link is wrong because it already contains the `&amp;`. If you try to URL-decode it, that becomes the same as what you see in your FreshRSS interface:
`https://rss-bridge.example.net/action=display&amp;bridge=DuckDuckGo&amp;u=test&amp;sort=%2Bsort%3Adate&amp;_cache_timeout=21600&amp;format=Atom`

Conclusion: it looks like the bug is in the button generating the link.

Closing for now, but feel free to post more info and we can re-open if we can confirm any bug.

---

P.S. When writing fake addresses, please stick to `example.net`, `example.com`, `something.example` or other domains reserved for this usage so we do not risk hitting third-party Web sites. See https://en.wikipedia.org/wiki/Example.com

**Closed as completed by Alkarex** 2022-11-02 22:19 UTC
Labels: Bug (unconfirmed)

**Comment by fatuuse** [comment] 2022-11-03 11:50
Thx for the help. I thought it was a bug in FreshRSS, but I hade som error at my side in rss-bridge.

**Comment by Alkarex** [comment] 2022-11-03 15:54
If this RSS-Bridge button is a feature you have developed, maybe you could provide link to it, as it might interest others

**Comment by fatuuse** [comment] 2022-11-03 16:04
Of course! Maybe it suits best in rss-bridge Gihub.

**Comment by Alkarex** [comment] 2022-11-03 20:24
Yes, but we could have a reference from here as well

**Comment by fatuuse** [comment] 2022-11-08 21:37
https://github.com/RSS-Bridge/rss-bridge/issues/3137
