### ISSUE TITLE
Operate feeds in batch (like remove all the feeds with errors)

### ISSUE THREAD

**Issue by yinguohang** [FreshRSS/FreshRSS#4362] opened 2022-05-12 01:02 UTC
Does FreshRSS currently support this feature? Thanks!

**Comment by Alkarex** [comment] 2022-05-12 09:00
Not at the moment. Duplicate of https://github.com/FreshRSS/FreshRSS/issues/3008

**Closed as completed by Alkarex** 2022-05-12 09:00 UTC
