### ISSUE TITLE
[BUG] Setting the filter action breaks the feed source settings

### ISSUE THREAD

**Issue by hkcomori** [FreshRSS/FreshRSS#6236] opened 2024-03-26 02:49 UTC
**Describe the bug**
Setting a filter to mark as read unnecessary articles will break the feed source settings.

**To Reproduce**
1. Add feed https://www.hoxsin.co.jp/news/:
    - feed source type: HTML + XPATH
    - item: `//ul[@class="article-list"]/li`
    - item title: `descendant::a`
    - item contents: `.`
    - item link: `descendant::a/@href`
    - item datetime: `descendant::time`
    - custom date/time format: `Y/m/d`
    - item unique id: `descendant::a/@href`
2. At this point, the feed can be fetched right.
3. Set and save filter action:
    - `intitle:'委託者証拠金'`
4. At this point, the feed can no longer be fetched and the feed source settings are broken.

**Expected behavior**
Feed settings are remained, unnecessary articles are filtered and marked as read, and unfiltered articles can be fetched in an unread state.

**Screenshots**

**Environment information (please complete the following information):**
- OS: Windows 10 Version 22H2 (Build 19045.4046)
- Browser: Vivaldi 6.5.3206.63
- Server OS: Ubuntu 22.04
- FreshRSS version: 1.23.1
- Database version: SQLite
- PHP version: PHP 8.2.7
- Installation type: Docker

**Additional context**

**Comment by math-GH** [comment] 2024-03-28 22:11
tested on edge 1.23.2-dev: Only 1 article is fetched with this parameters, before I set the filter

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/006cb71e-26ce-4598-a182-8c54230702e0)


Could you please check the parameters?

**Comment by hkcomori** [comment] 2024-03-29 08:15
Sorry, my parameter was wrong.

```diff
-//ul[@class="article-list"]
+//ul[@class="article-list"]/li
```

But even with the correct parameters and `freshrss/freshrss:edge`, this issue was reproduced.

**Comment by math-GH** [comment] 2024-03-29 16:42
Thank you for the corrected config. Now it works for me too.
 Could you please explain what you mean with "Set and save filter action: intitle:'委託者証拠金'"? Where do you save it?

**Comment by hkcomori** [comment] 2024-03-30 04:56
Under "Filter actions", enter `intitle:'委託者証拠金'` into "Mark an article as read..." and "Submit".

![image](https://github.com/FreshRSS/FreshRSS/assets/11016036/47bbc2d2-06be-430a-8e9f-89eeac6ce189)

**Comment by math-GH** [comment] 2024-03-30 19:39
I can confirm.

How the error looks like:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/906507d4-fb80-4bfe-8962-9d636b52f392)

Log:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/f9467108-b66c-4f43-95c9-32775c9a9fd7)

**Comment by math-GH** [comment] 2024-03-30 19:43
Strange:
The settings are lost:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/bb4bd83e-1360-463f-bf89-bfb4dd5d35ab)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/e9f64892-d5eb-4281-bd27-7f320a064b5c)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/d9133b1b-fe8d-47f8-a2d7-de2523f8538d)

**Comment by Alkarex** [comment] 2024-03-30 23:19
For some reason, the regex `\R` (new line) does not seem to work with this multi-byte string
https://php.net/regexp.reference.escape

```php
// Does not work
print_r(preg_split('/\R/', '委託者証拠金'));

// Works
print_r(preg_split('/[\n\r]+/', '委託者証拠金'));

// Works
print_r(mb_split('/\R/', '委託者証拠金'));

// Works
print_r(preg_split('/\R/u', '委託者証拠金'));
```

https://php.net/reference.pcre.pattern.modifiers

Fixed in https://github.com/FreshRSS/FreshRSS/pull/6247
Tests welcome

We might have other similar bugs where we use `preg_` functions. Help to test welcome

**Comment by hkcomori** [comment] 2024-03-31 12:24
Thank you.
I have confirmed with #6247 that it works as expected with the following parameters:

**compose.yaml**

```yaml
services:
  freshrss:
    image: freshrss/freshrss:pr6247
    build:
      context: https://github.com/Alkarex/FreshRSS.git#unicode-preg_split
      dockerfile: Docker/Dockerfile-Alpine
```

**parameters**

```
intitle:'委託者証拠金'
!intitle:'臨時見直し'
```

This is the only parameter I might use for the moment, but if you have other testing needs, please let me know.

**Closed as completed** 2024-03-31 16:39 UTC
Labels: Bug (confirmed) 🐞
