### ISSUE TITLE
CLI install bug with SQLite

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1443] opened 2017-02-27 22:29 UTC
I'm trying to use FreshRSS cli in order to install FreshRSS from A to Z.

I'm first trying to install Fresh using the first cli step:

```bash
>./cli/do-install.php --default_user admin --api_enabled --db-type sqlite
FreshRSS install…
FreshRSS install failed requirements:
• pdo-mysql
• pdo-pgsql
• data
• cache
• users
• favicons
```

It is the simplest install options possible. But I don't understand what does this return means?

I was thinking about a permission issue, but when I try to install FreshRSS via the web interface, I get no error nor warning. Permissions are already set and writable by the server, and mandatory php modules are also already installed.

Am I missing something?

**Comment by Alkarex** [comment] 2017-02-28 07:55
Thanks for the feedback @oupala 
There is indeed a bug when using sqlite (attempts to write in the user directory before it is created). I will fix that.

Currently, it can be done manually by:
```sh
mkdir data/users/admin
```

However, I cannot reproduce your other requirement problems. The tests come from https://github.com/FreshRSS/FreshRSS/blob/dev/lib/lib_install.php#L8

Could you please show the outputs of:

```sh
ls -alh
ls -alh data
```

I need to filter out `pdo-mysql and pdo-pgsql` from the error outputs when `pdo_sqlite` is used, but they are not the cause of the failure.

**Comment by Alkarex** [comment] 2017-02-28 08:03
Ah, you need to remember that your local user running the CLI commands and the user running the Web server are not the same. You can change user for your commands with e.g. `sudo -u www-data ...` or do everything as the local user and apply the rights for www-data afterwards.

**Comment by Alkarex** [comment] 2017-02-28 08:06
https://github.com/FreshRSS/FreshRSS/tree/dev#example-of-full-installation-on-linux-debianubuntu

**Comment by Alkarex** [comment] 2017-02-28 20:15
@oupala The SQLite problem should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1444 together with some better requirements checks. Could you please give it a try?

**Comment by oupala** [comment] 2017-02-28 23:09
You're right. The bug I've found was related to the fact that I was using my standard user instead of www-data user. I will update my ansible playbook to use www-data user.

But this made you found another bug concerning sqlite.

I tried to install FreshRSS from your `cli-install-sqlite` branch, using the `www-data` user. Here is the console output:

```bash
>sudo -u www-data ./cli/do-install.php --default_user admin --api_enabled --db-type sqlite
FreshRSS install…
• Remember to create the default user: admin
	./cli/create-user.php --user admin --password 'password' --more-options
• Remember to re-apply the appropriate access rights, such as:
	sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
Result: success
```

I think it is the excpected result. Right?

**Comment by Alkarex** [comment] 2017-03-01 07:47
Indeed, looks good 👍

**Closed as completed by Alkarex** 2017-03-01 07:47 UTC
Labels: Important :fire:
