### ISSUE TITLE
Auto tag For the new entry

### ISSUE THREAD

**Issue by nova2018** [FreshRSS/FreshRSS#2380] opened 2019-04-20 15:09 UTC
I want to give new entry some user tags by the keyword for the entry. 
I want the tag list showed in the page.
Have any good way ?

**Comment by math-GH** [comment] 2021-12-25 16:15
@i365star Is it still actual? Could you give some examples to understand this Feature Request better?

**Comment by Alkarex** [comment] 2021-12-28 12:06
I will try to prioritise this feature. I believe we have other issues about automatic actions, which we should link.

**Comment by math-GH** [comment] 2022-09-03 09:55
with #4101 (version 1.20) the tags can be displayed above/below the article

**Comment by math-GH** [comment] 2022-09-03 09:56
auto tagging is asked here too: #2420

**Comment by aledeg** [comment] 2022-11-13 11:05
Is this a duplicate of #3279?

**Comment by Alkarex** [comment] 2023-12-31 20:50
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954

**Closed as completed** 2024-01-03 10:23 UTC
Labels: Article filter
