### ISSUE TITLE
Category posts are not sorted by date

### ISSUE THREAD

**Issue by AlexKalopsia** [FreshRSS/FreshRSS#2950] opened 2020-05-03 17:42 UTC
Hi, 

I think this might be by design, but when I click on a category, all the blog posts are sorted by Website first and by date second. So, to give an example, this is how they currently show up:

Website A - 20/06/2018
Website A - 18/06/2018
Website A - 01/02/2017
Website B - 03/04/2018

I would like to only order by date, so

Website A - 20/06/2018
Website A - 18/06/2018
Website B - 03/04/2018
Website A - 01/02/2017

I am wondering if this is a bug or if I am just missing something in the options.

Thanks

**Comment by Alkarex** [comment] 2020-05-03 17:50
Hello,
Yes, it is indeed by design: the order is based on when articles are received, not on the declared date - just like what is done by e.g. e-mail clients. The behaviour you observe is especially visible when you add new feeds one at a time (as opposed to importing several via OPML). In any case, after you start regularly refreshing feeds, articles will be in a more chronological order.

**Closed as completed** 2020-05-03 17:56 UTC

**Comment by AlexKalopsia** [comment] 2020-05-03 18:02
Ok cool, good to know! But wouldn't adding more feeds make the issue even more evident as different entries would be buried deeper down? (especially if you have a website that posts daily, and another that posts bi-weekly?

Thanks for the help

**Comment by Alkarex** [comment] 2020-05-03 18:06
No, the articles are not sorted by feed, they are simply sorted by when individual articles were received, so the article from your rarely publishing feed will not be less visible than any other.

**Comment by AlexKalopsia** [comment] 2020-05-03 18:08
Ooooooh ok perfect, gotcha! Now it makes a lot more sense, thank you :)

**Comment by Alkarex** [comment] 2020-05-03 18:12
No worries, you are not the first one asking. It is actually the most common way to sort in such software, and you can find more detailed explanation by searching in our old issues.
Imagine an article with a very old publication date: it would get buried and you would not see it (quite common for e.g. academic publications, which date can be several months old).
Another example is an article with a date in the future (quite common for some events), which would stay at the top of your newsfeed all the time.
