### ISSUE TITLE
[Bug] Navigation shortcuts with ALT stopped working

### ISSUE THREAD

**Issue by docron13** [FreshRSS/FreshRSS#6747] opened 2024-08-29 14:03 UTC
### Describe the bug

In the new/current version navigating folders with the `ALT+J` or `ALT+K` keyboard shortcuts suddenly stopped working for me. (Normal keyboard shortcuts and also the `SHIFT+J` etc. are still working as usual.)

### To Reproduce

1. Go to the main stream or just any other folder.
2. Press `ALT+J` (provided you do not changed the shortcuts to something else)
3. No change in the folder view.

### Expected behavior

Jump to the next (unread) folder (as it did in the previous versions).

### FreshRSS version

1.24.2

### Environment information

- Database version: Ver 15.1 Distrib 10.5.25-MariaDB, for debian-linux-gnu (x86_64)
- PHP version: 8.3.8-nmm1
- Installation type: Managed hosting
-Web server type: Apache
- Device: PC
- OS: Win11
- Browser: Chrome 128.0.6613.85

**Comment by math-GH** [comment] 2024-08-29 14:54
Duplicate of #6737 that is already fixed on `edge`

**Comment by Alkarex** [comment] 2024-08-29 15:01
@docron13 Could you please try our edge branch?

**Comment by docron13** [comment] 2024-08-29 15:48
Yes, the edge version is working again! 👍

Sorry for the double post, btw. Thanks for the good work!

**Closed as completed** 2024-08-29 16:27 UTC
Labels: Shortcuts ⌨, Duplicate ‼, Bug (confirmed) 🐞
