### ISSUE TITLE
[BUG] Docker cron not working

### ISSUE THREAD

**Issue by meminens** [FreshRSS/FreshRSS#5894] opened 2023-11-19 17:30 UTC
**Describe the bug**
FreshRSS does not auto update the feed with CRON_MIN variable set.

**To Reproduce**
Wait at least half an hour for feed auto-refresh. Nothing happens. I know this for sure because when I click the refresh button on the web interface, all of my feeds are updated and the number of unread articles increases.

**Expected behavior**
Auto update feed every 30 minutes.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: Mini PC Server, Intel N100
- OS: Debian 12
- Browser: Firefox 119
- FreshRSS version: 1.22.1
- Database version: SQlite
- PHP version: I don't know
- Installation type: Docker

**Additional context**
See docker compose below. I've tried both `2,32` and `'2,32'`. Same result.

```
version: "3.8"
services:
  freshrss:
    network_mode: bridge
    environment:
      - TZ=America/New_York
      - CRON_MIN=2,32
    image: freshrss/freshrss:latest
    container_name: freshrss
    ports:
      - 8080:80
    restart: always
    volumes:
      - /home/lab/.freshrss/data:/var/www/FreshRSS/data
      - /home/lab/.freshrss/extensions:/var/www/FreshRSS/extensions

```

**Comment by math-GH** [comment] 2023-11-19 18:07
I hope, that you are using 1.22.1 and not 1.11.1 ;)
Which Docker repository do you use?

**Comment by meminens** [comment] 2023-11-19 20:29
@math-GH yes, typo. sorry :) now corrected.

**Comment by viviicat** [comment] 2023-11-20 16:54
I may be seeing this as well. My feeds mysteriously seemed to stop updating.

**Comment by JanKnipp** [comment] 2023-11-21 06:57
Seeing the same issue. Manual update works fine but cron does not update the feeds anymore.

**Comment by sdelafond** [comment] 2023-11-21 07:03
Manual update works fine but no cron'ed auto-updates seem to take place. I'm using the official image. The same exact docker-compose setup updated fine through cron in 1.21.0.

**Comment by Alkarex** [comment] 2023-11-21 09:38
Could some of you try the following commands:

```sh
docker exec freshrss cat /etc/issue
docker exec freshrss sh -c 'echo $CRON_MIN'
docker exec freshrss cat /tmp/FreshRSS.log
docker exec freshrss cat /etc/crontab.freshrss.default
docker exec freshrss crontab -l
docker exec freshrss cat /var/www/FreshRSS/Docker/env.txt
```

And could you try with our edge branch?
For some of you, it might be a duplicate of https://github.com/FreshRSS/FreshRSS/issues/5792 , which is already fixed https://github.com/FreshRSS/FreshRSS/pull/5795

**Comment by sdelafond** [comment] 2023-11-21 10:43
```
host # docker compose exec freshrss bash
root@freshrss:~# cat /etc/issue
Debian GNU/Linux 12 \n \l

root@freshrss:~# echo $CRON_MIN
3,33
root@freshrss:~# cat /tmp/FreshRSS.log
cat: /tmp/FreshRSS.log: No such file or directory
root@freshrss:~# cat /etc/crontab.freshrss.default
7,37 * * * * . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'             2>> /proc/1/fd/2 > /tmp/FreshRSS.log
root@freshrss:~# crontab -l
3,33 * * * * . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'             2>> /proc/1/fd/2 > /tmp/FreshRSS.log
root@freshrss:~# cat /var/www/FreshRSS/Docker/env.txt
export --base_url <redacted>
export --db-base freshrss
export --db-host freshrss-db
export --db-password <redacted>
export --db-type pgsql
export --db-user freshrss
export --default_user admin
export --email <redacted>
export --language en
export --password <redacted>
export --user admin
export COPY_LOG_TO_SYSLOG=On
export COPY_SYSLOG_TO_STDERR=On
export CRON_MIN=3,33
export DATA_PATH=
export FRESHRSS_ENV=
export FRESHRSS_INSTALL=--api_enabled
export FRESHRSS_USER=--api_password <redacted>
export HOSTNAME=freshrss
export LISTEN=0.0.0.0:80
export OIDC_ENABLED=
export TRUSTED_PROXY=
export TZ=Europe/Paris
```

I don't use the `TRUSTED_PROXY` env variable.

I'll give `freshrss/freshrss:pr5795` a spin when I find some spare time.

**Comment by Alkarex** [comment] 2023-11-21 11:13
Please try `freshrss/freshrss:edge` (`freshrss/freshrss:pr5795` does not exist anymore - the PR has been merged 3 weeks ago).

**Comment by sdelafond** [comment] 2023-11-21 13:52
`freshrss/fressh:edge` does fix the issue, with feeds correctly updates every 30 minutes.

**Comment by Alkarex** [comment] 2023-11-21 16:21
I have just merged another related improvement in the edge branch https://github.com/FreshRSS/FreshRSS/pull/5898

**Closed as completed** 2023-11-21 19:52 UTC
Labels: Docker 🐋, Bug (unconfirmed)
