### ISSUE TITLE
[BUG] old article appears again, which were already marked as read

### ISSUE THREAD

**Issue by update-freak** [FreshRSS/FreshRSS#5210] opened 2023-03-18 10:42 UTC
Hi,

I have the same issue as mentioned here
https://github.com/FreshRSS/FreshRSS/issues/4401

As you can see from the screenshots (see the date) there came up older content, which is already marked as read.

Feed-URLs from the screenshots.
https://mediathekviewweb.de/feed?query=!WDR%20%23Wundersch%C3%B6n!
https://mediathekviewweb.de/feed?query=heute-show
https://mediathekviewweb.de/feed?query=leschs%20kosmos
https://mediathekviewweb.de/feed?query=MaiThink%20X

I use the current version of FreshRSS on Docker on Synology NAS.
![2](https://user-images.githubusercontent.com/40196995/226100621-4b992def-d7c0-4903-8c0a-54c4c18471e7.png)
![1](https://user-images.githubusercontent.com/40196995/226100624-3a30f3d4-7597-437d-876f-bcb1d759c71d.png)
![3](https://user-images.githubusercontent.com/40196995/226100625-362d90da-e8ea-4fbc-a975-6e55f8236fbf.png)
![4](https://user-images.githubusercontent.com/40196995/226100626-30cd4143-006c-4e50-b97b-64c4d4bc1f1a.png)

**Comment by math-GH** [comment] 2023-03-18 11:17
Is this checkbox checked or unchecked in config "Reading"?

![grafik](https://user-images.githubusercontent.com/1645099/226102016-17b0f09e-a25c-40b4-8fc2-2f7e37fc4e17.png)

**Comment by update-freak** [comment] 2023-03-18 11:27
No this item is not checked:
![freshrss](https://user-images.githubusercontent.com/40196995/226102397-9d027578-24b2-4135-809d-ba7218b9c0ee.png)

**Comment by math-GH** [comment] 2023-03-19 20:56
I will subscribe to this feeds to try to reproduce it. I guess it will need some weeks

**Comment by math-GH** [comment] 2023-03-26 19:24
I can reproduce it in general.

I guess that the GUID changes regulary. I will have a look in the next step
![grafik](https://user-images.githubusercontent.com/1645099/227799511-be912039-310e-4394-b1e9-86bad588f283.png)

**Comment by math-GH** [comment] 2023-03-26 19:28
It looks like that this behavior will not be fixed by the mediathekvieweb
see: https://github.com/mediathekview/mediathekviewweb/issues/258

**Comment by math-GH** [comment] 2023-03-27 15:45
The GUID of (1) has changed. (2) did not change.

![grafik](https://user-images.githubusercontent.com/1645099/227992164-3440c855-8ba1-4edf-8d2f-8d10081d7d6c.png)

@Alkarex How could FreshRSS handle this situations? Would it make sense to have an feed option that the article link is used as GUID replacement? In this case here, it would be stable.

**Comment by Frenzie** [comment] 2023-03-27 17:13
As an option, possibly, but by default I think the current behavior is 100% correct.

**Comment by Alkarex** [comment] 2023-03-27 18:13
Yes, we should offer an option to manually override the type of unicity, giving the option to use the URL instead.
Slightly related to https://github.com/FreshRSS/FreshRSS/pull/4487 , which is not merged yet, because I have an idea of storing the unicity in the articles' attributes to better handle changes of unicity types.

**Closed as completed** 2024-10-14 07:34 UTC
Labels: Feed problem :newspaper_roll:
