### ISSUE TITLE
[BUG] Docker container on raspberry pi: having an issue to sync system date/time

### ISSUE THREAD

**Issue by st406** [FreshRSS/FreshRSS#4225] opened 2022-02-17 19:03 UTC
**Describe the bug**
Docker container on raspberry pi (freshrss/freshrss:arm) having an issue to sync system date/time

**Environment information (please complete the following information):**
- Docker version 18.09.1, build 4c52b90
- OS: Raspbian GNU/Linux 10 (buster)
- FreshRSS version: [e.g. 1.19.2]

**Comment by Alkarex** [comment] 2022-02-18 11:27
Hello,
Maybe a duplicate of https://github.com/FreshRSS/FreshRSS/issues/4198
Easiest solution: update your Raspbian / kernel to current version

**Comment by math-GH** [comment] 2022-07-30 12:53
@st406 Is it still an issue with 1.19.2 or 1.20.0-dev?

**Closed as completed** 2023-01-28 19:02 UTC
Labels: Docker 🐋, Bug (unconfirmed)
