### ISSUE TITLE
[BUG] item link with ctrl characters will be edited in XPath

### ISSUE THREAD

**Issue by HernandoR** [FreshRSS/FreshRSS#5911] opened 2023-11-30 06:19 UTC
**Describe the bug**
given an example of item link :
`http://mp.weixin.qq.com/ss?__biz=MzU5ODk2MDAxOA==&mid=2247513518&idx=1&sn=b5bb7c2d412172ad53208c08713b95ba&chksm=febec753c9c94e45c1bf3d1f83f20a7d96922da57adf5fc10f2a9d35a670e45f5d45296155e2##rd`

the '&' will be erased in the link of retrieved title, meaning that, the link in the titile will be `http://mp.weixin.qq.com/ss?__biz=MzU5ODk2MDAxOA==mid=2247513518&idx=1&sn=b5bb7c2d412172ad53208c08713b95bachksm=febec753c9c94e45c1bf3d1f83f20a7d96922da57adf5fc10f2a9d35a670e45f5d45296155e2##rd`

**To Reproduce**
1. create a new feed with html and xpath

in my case:
source link: `https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzU5ODk2MDAxOA==&action=getalbum&album_id=1631131263468126211&scene=173&from_msgid=2247513477&from_itemidx=1&count=3&nolastread=1#wechat_redirect`
xpath locate:`//li[@class='album__list-item js_album_item js_wx_tap_highlight wx_tap_cell']`
item title: `./@data-title`
item link: `./@data-link`

2. submit
3. you will notice the correct title while wrong link: without '&'

**Expected behavior**
correct title while correct link: with '&'

**Screenshots**
link we get
![image](https://github.com/FreshRSS/FreshRSS/assets/45709656/001df3d3-6c76-437c-89f3-ae4ebe03e9f6)
correct datalink
<img width="658" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/45709656/f873cfaa-0d23-411c-a2aa-607a055231cf">

**Environment information (please complete the following information):**
freshrss web interface at rss.cheredeprince.net

**Additional context**

**Comment by Alkarex** [comment] 2023-11-30 08:39
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/5430
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/5912

**Closed as completed** 2023-11-30 08:46 UTC
Labels: Bug (confirmed) 🐞
