### ISSUE TITLE
[Bug] SQL error  "HY000",5,"database is locked"

### ISSUE THREAD

**Issue by pax0707** [FreshRSS/FreshRSS#6686] opened 2024-08-02 12:21 UTC
### Describe the bug

Randomly during usage web UI becomes unresponsive.  
3d party clients will not properly mark articles at read.

### To Reproduce

Use the browser, till it locks up.

### FreshRSS version

1.24.2-dev

### Environment information

- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: 8.2.20
- Installation type: Docker - freshrss/freshrss:edge
-Web server type: nginx
- Device: PC
- OS: Windows
- Browser: Chrome 128

### Additional context

Not sure if edge issue or just the database getting too big.

87 271 articles (792.41 MiB)

Looks like SimplePie running locks it.

```
FreshRSS[43]: [pax] [Fri, 02 Aug 2024 14:01:03 +0200] [error] --- SQL error FreshRSS_EntryDAOSQLite::markRead A ["HY000",5,"database is locked"]
FreshRSS[88]: [pax] [Fri, 02 Aug 2024 14:01:08 +0200] [error] --- SQL error countUnreadReadFavorites|updateUsingRequest|normalAction|launchAction ["HY000",5,"database is locked"]
xxxxx - - [02/Aug/2024:14:01:09 +0200] "GET / HTTP/1.0" 302 - "-" "Uptime-Kuma/1.23.13"
xxxxx- - [02/Aug/2024:14:01:09 +0200] "GET /i/?rid=xxxxHTTP/1.0" 200 2354 "-" "Uptime-Kuma/1.23.13"
FreshRSS[40]: [pax] [Fri, 02 Aug 2024 14:01:09 +0200] [error] --- SQL error FreshRSS_EntryDAOSQLite::markRead A ["HY000",5,"database is locked"]
```

**Comment by Alkarex** [comment] 2024-08-02 13:40
What database are you using?

**Comment by pax0707** [comment] 2024-08-02 13:58
Whatever is the default for freshrss/freshrss:edge.
Not home to check.

**Comment by Alkarex** [comment] 2024-08-02 14:24
Ok, that is SQLite.

**Comment by Alkarex** [comment] 2024-08-02 14:26
Might be the same than https://github.com/FreshRSS/FreshRSS/issues/6592

**Comment by pax0707** [comment] 2024-08-08 16:38
> Might be the same than #6592

I see that bug is closed.
I'm still experiencing this behavior.
Latest 1.24.2-dev docker image.
While feeds are updating (from docker logs) webui is unresponsive. Well, if not logged in I can get to the login screen but anything after is a permanent spinner, until the feeds refresh.

**Comment by Alkarex** [comment] 2024-08-08 19:23
https://github.com/FreshRSS/FreshRSS/issues/6592 was not relevant for you after all as it was not affecting SQLite

**Comment by Alkarex** [comment] 2024-08-08 19:24
Can you check your logs just before the error, to get an idea of what might be locking the database?

**Comment by Alkarex** [comment] 2024-08-08 19:25
This only happens when the feeds are getting updated by the cron?

**Comment by pax0707** [comment] 2024-08-14 14:04
> Can you check your logs just before the error, to get an idea of what might be locking the database?

I sent you an email with logs a few days ago.
Not sure now if it was the right mail.

**Comment by Alkarex** [comment] 2024-08-15 13:38
I have not received your email, but I believe I can reproduce a problem. I will try to come up with an improvement

**Comment by Alkarex** [comment] 2024-08-15 14:30
Would you be able to try https://github.com/FreshRSS/FreshRSS/pull/6713 ?

**Comment by pax0707** [comment] 2024-08-15 16:56
Pulled it.

Will observe.

**Comment by Alkarex** [comment] 2024-08-15 19:40
Merged in `edge`. Additional testing much welcome

**Closed as completed** 2024-08-15 19:39 UTC
Labels: Bug (confirmed) 🐞

**Comment by pax0707** [comment] 2024-08-16 23:12
I found only one locked event since updating.
That is way fewer than before.

```
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-getThirdPartyUrl: START                                                                                                                                           |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-getConfigValueByKeyAsStr: START                                                                                                                                   |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: START                                                                                                                                            |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: key=3rd_party_url                                                                                                                                |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: user_conf available                                                                                                                              |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: YouTubeChannel2RssFeed available                                                                                                                 |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: YouTubeChannel2RssFeed is a array                                                                                                                |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: key in array found                                                                                                                               |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-configKeyExists: END result=found                                                                                                                                 |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-getConfigValueByKeyAsStr: value=''                                                                                                                                |
[Fri, 16 Aug 2024 03:33:12 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 03:33:21 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 03:33:21 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 03:33:21 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 03:33:21 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 03:33:25 +0200] [error] --- SQL error FreshRSS_CategoryDAO::listCategories["HY000",5,"database is locked"]                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - START                                                                                                                                         |
[Fri, 16 Aug 2024 05:00:07 +0200] [debug] --- YouTubeChannel2RssFeed-EntryBeforeInsert - END                                                                                                                                           |
 Files :: Text Filters ::                                                                                                                                                                                             Press TAB to edit
 L75         1%   1 hits for “locked”                                                                                                                                                                           ?:View Help
                                                                                                                                                                              Press '>' or '<' to scroll horizontally to a search result```

**Comment by Alkarex** [comment] 2024-08-17 07:03
Excellent. ~~The remaining one seems to be related to the YouTubeChannel2RssFeed extension~~
Edit: no, not clear what the last one is - would require a bit more logging / debugging

**Comment by widowild1** [comment] 2024-08-20 05:44
good morning,
I tested freshss en edge with sqlite on a new installation. I also get this error message after importing an RSS feed and updating it.
`<html>
<body>

2024/08/20 07:35:05 | stderr | FreshRSS[635]: [widowild] [Tue, 20 Aug 2024 07:35:05 +0200] [warning] --- Feed has valid GUIDs again: http://atlasflux.saynete.net/entree_rss.xml
-- | -- | --
2024/08/20 07:35:05 | stderr | FreshRSS[635]: SimplePie GET 200 http://atlasflux.saynete.net/entree_rss.xml
2024/08/20 07:35:05 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:35:01 +0200] "GET /i/?rid=66c42b056190b HTTP/1.1" 200 61174 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:35:01 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:35:01 +0200] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:30:29 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:28:17 +0200] "GET /i/?a=normal HTTP/1.1" 200 37679 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:29:17 | stderr | FreshRSS[66]: [widowild] [Tue, 20 Aug 2024 07:29:17 +0200] [error] --- SQL error countUnreadReadFavorites\|updateUsingRequest\|normalAction\|launchAction ["HY000",5,"database is locked"]
2024/08/20 07:28:04 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:27:42 +0200] "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1" 200 968 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:53 | stdout | 127.0.0.1 - - [20/Aug/2024:07:26:52 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.61 (Debian) (internal dummy connection)"
2024/08/20 07:26:52 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:51 +0200] "GET /f.php?1bed0d37 HTTP/1.1" 200 41600 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:52 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:49 +0200] "GET /f.php?0f2510c1 HTTP/1.1" 200 41600 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:52 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:51 +0200] "GET /f.php?6178c468 HTTP/1.1" 200 1150 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:51 | stderr | FreshRSS[53]: FreshRSS Favicon GET https://demo.shaarli.org/tpl/default/img/favicon.png
2024/08/20 07:26:51 | stderr | FreshRSS[47]: FreshRSS Favicon GET https://jvalleroy.me/favicon.ico
2024/08/20 07:26:51 | stderr | FreshRSS[47]: FreshRSS Favicon GET https://jvalleroy.me/
2024/08/20 07:26:51 | stderr | FreshRSS[53]: FreshRSS Favicon GET https://demo.shaarli.org/
2024/08/20 07:26:51 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:50 +0200] "GET /f.php?b6dc51e8 HTTP/1.1" 200 7407 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:51 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:49 +0200] "GET /f.php?1bfb33b2 HTTP/1.1" 200 1437 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:51 | stdout | xxx.xxx.xxx.xxx - - [20/Aug/2024:07:26:50 +0200] "GET /f.php?60fadf79 HTTP/1.1" 200 1866 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"
2024/08/20 07:26:51 | stderr | FreshRSS[47]: FreshRSS Favicon GET https://jvalleroy.me/shaarli/
2024/08/20 07:26:51 | stderr | FreshRSS[67]: FreshRSS Favicon GET https://sajous.net/yunohost/sso/assets/icons/favicon.ico
2024/08/20 07:26:51 | stderr | FreshRSS[59]: FreshRSS Favicon GET http://redbeard.free.fr/favicon.ico
2024/08/20 07:26:51 | stderr | FreshRSS[53]: FreshRSS Favicon GET https://demo.shaarli.org/feed/atom
2


</body>
</html>`

**Comment by Alkarex** [comment] 2024-08-20 07:19
@widowild1 Please make sure you pull the latest `edge` version of FreshRSS. Is that with Docker? Your logs are strange, because I cannot see the lines related to your feed import, and there is no other request near the time of the lock (07:29:17). Additional tests welcome, if you can find a pattern.

**Comment by widowild1** [comment] 2024-08-20 07:56
![IMG_20240820_094427](https://github.com/user-attachments/assets/2358ec2b-ad3d-4339-a894-69b179fa1937)
[freshrss-app.csv](https://github.com/user-attachments/files/16671141/freshrss-app.csv)
Normalement c'est le log depuis le début de l'installation, j'utilise un synology sous docker et dès que freshrss mouline, j'ai une page d'erreur qui me retourne comme une erreur 404.
Désolé de ne pas le traduire je suis sur mobile.

**Comment by Alkarex** [comment] 2024-08-20 08:16
Le hash `94e08...` semble indiquer que cette image est vieille (plus qu'un mois). Veuillez refaire un `pull` avant d'essayer à nouveau

**Comment by widowild1** [comment] 2024-08-20 09:35
Je sais pas si ça vient du synology mais watchtower ne voit pas la mise à jour,
idem avec cette commande: 
`docker images | awk '(NR>1) && ($2!~/none/) {print $1":"$2}' | xargs -L1 docker pull`
qui me sort:
`edge: Pulling from freshrss/freshrss
Digest: sha256:a4a95c8b2e00f813800ad03b1bfc9d2daad02bd75c6db8971bd40df70a941cc4
Status: Image is up to date for freshrss/freshrss:edge
docker.io/freshrss/freshrss:edge`

même en effaçant l'image, supprimant le projet freshrss, il me retélécharge avec le hash 94e08, j'ai d'autres images comme calibre, miniflux, postgres et autre ça me télécharge les dernières versions, mais là je ne vois pas.

**Comment by widowild1** [comment] 2024-08-20 09:39
j'ai effacé mon précédent commentaire, c'est un bug sur synology semble-t-il, a-t-on la possibilité sur freshrss de voir la dernière version (git commit)? dans l'application pour être sûr que l'on utilise bien la dernière version.
avec docker pull et watchtower me dise que j'ai bien la dernière version mais dans la fenêtre de container manager non. désolé pour le dérangement.

EDIT:
`edge: Pulling from freshrss/freshrss
Digest: sha256:a4a95c8b2e00f813800ad03b1bfc9d2daad02bd75c6db8971bd40df70a941cc4
Status: Image is up to date for freshrss/freshrss:edge
docker.io/freshrss/freshrss:edge`

EDIT2 via freshrss après une **actualisation** de flux RSS:
[code]Niveau de sévérité	Horodatage	Message de journal
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 113
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 112
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 107
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::addEntry["HY000",5,"database is locked"] while adding entry in feed 318 with title: Self-Hosting - Initial Charge
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 111
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 110
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 108
❌	2024-08-20 12:20:42	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 109
❌	2024-08-20 12:20:42	SQL error FreshRSS_FeedDAO::updateFeed["HY000",5,"database is locked"] for feed 121
❌	2024-08-20 12:20:39	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:20:27	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:20:25	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:20:21	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:20:08	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:19:39	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:19:39	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:19:39	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:19:39	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	2024-08-20 12:18:39	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 121
❌	2024-08-20 12:18:39	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 118
❌	2024-08-20 12:18:39	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 127
❌	2024-08-20 12:18:39	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 126
❌	2024-08-20 12:18:39	SQL error FreshRSS_EntryDAO::listHashForFeedGuids["HY000",5,"database is locked"] while querying feed 117
❌	2024-08-20 12:18:30	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:18:27	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
❌	2024-08-20 12:18:25	SQL error searchById|actualizeFeeds|actualizeAction|launchAction ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:16:55	cURL error 60: SSL: no alternative certificate subject name matches target host name 'casami.fr' [https://casami.fr/?do=rss]
❌	2024-08-20 12:16:44	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 130
❌	2024-08-20 12:16:41	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 131
❌	2024-08-20 12:16:41	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 133
❌	2024-08-20 12:16:22	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 137
❌	2024-08-20 12:16:13	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 138
❌	2024-08-20 12:15:15	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 145
❌	2024-08-20 12:14:49	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 149
❌	2024-08-20 12:14:11	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 151
❌	2024-08-20 12:13:56	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 152
⚠️	2024-08-20 12:13:50	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
⚠️	2024-08-20 12:13:34	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	2024-08-20 12:13:23	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 155
❌	2024-08-20 12:13:23	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 159
❌	2024-08-20 12:12:50	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 160
❌	2024-08-20 12:12:34	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 161
❌	2024-08-20 12:12:34	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 163
❌	2024-08-20 12:12:06	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 165
❌	2024-08-20 12:11:57	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 164
❌	2024-08-20 12:09:55	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 184
❌	2024-08-20 12:09:55	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 186
⚠️	2024-08-20 12:08:48	cURL error 60: SSL: no alternative certificate subject name matches target host name 'qosgof.fr' [https://qosgof.fr/fosteb?do=rss]
⚠️	2024-08-20 12:06:48	FreshRSS_FeedDAO::updateLastUpdate error: UPDATE `_feed` SET `lastUpdate`=?, error=? WHERE id=? : ["HY000",5,"database is locked"]
❌	2024-08-20 12:06:08	SQL error FreshRSS_EntryDAO::updateLastSeen["HY000",5,"database is locked"] while updating feed 223[/code]

**Comment by Alkarex** [comment] 2024-08-21 15:18
L'image Docker semble bien à jour maintenant. Cela ressemble être un rafraîchissement manuel par l'interface Web et pas un cron en arrière plan. Pourriez vous essayer d'éditer votre `./data/config.php` et réduire la valeur `nb_parallel_refresh` (qui est par défaut à 10) pour une valeur plus faible comme 2 ?
Je vais essayer de faire quelques tests de plus. Aide bienvenue

**Comment by widowild1** [comment] 2024-08-21 16:47
lancement du container freshrss (33000 articles pour 145mb), purger -> optimiser -> effacer les logs de freshrss dans freshrss.
modification de la valeur 10 par 2 pour `nb_parallel_refresh`,  redémarrage du container.
"Marquer comme lu"; actualisation manuel; cycle d'actualisation flux par flux; augmentation de taille du db.sqlite (212mb), pour l'instant que des erreurs de `cURL error 6: Could not resolve host` pas de message bloquant pour sqlite.
Je poursuis mes tests, Je vous tiens au courant.
EDIT: 12 nouveaux articles de différents flux, puis message d'erreur de `database lock`, le db.sqlite n'augmente pas de taille.
