### ISSUE TITLE
"purge" button in the archiving setting does not delete all articles are supposed to

### ISSUE THREAD

**Issue by giorgiobeggiora** [FreshRSS/FreshRSS#1628] opened 2017-09-07 15:55 UTC
I tried to set 1 month (please add 0 as valid value) but some old articles remains (scraped with the cron that was using the unsupported php version #1604 ).

@Alkarex you already have my hosting credentials so you can check by yourself.

Thanks a lot.

**Comment by Alkarex** [comment] 2017-09-08 18:55
Yes, what you observe is the current expected behaviour.
I am preparing a custom DB fix for you. In other similar cases I would suggest exporting the OPML list of articles, deleting and re-creating the user, and re-importing the OPML list. We could add a command-line function to clear all articles, but I would rather not have that in the Web interface.

**Comment by Alkarex** [comment] 2017-09-08 19:04
So, it should be fixed for your server.

I have run that on your DB:

```sh
sqlite3 db.sqlite
```

```sql
DELETE FROM entry;
VACUUM;
```

And then a DB optimization and a feed refresh from the FreshRSS Web UI.

If you want, there is a copy of the old DB `db0.sqlite` in the same folder. You can delete it when it is not needed anymore.

**Comment by giorgiobeggiora** [comment] 2017-09-08 19:55
Thank you a lot, I was sharing to help and I was helped XD

**Closed as completed** 2017-09-09 09:07 UTC

**Comment by rezad1393** [comment] 2020-12-11 03:28
is this still default behavior? because I have the same problem.

**Comment by rezad1393** [comment] 2020-12-11 03:28
> Yes, what you observe is the current expected behaviour.
> I am preparing a custom DB fix for you. In other similar cases I would suggest exporting the OPML list of articles, deleting and re-creating the user, and re-importing the OPML list. We could add a command-line function to clear all articles, but I would rather not have that in the Web interface.

is this still default behavior? because I have the same problem.

**Comment by Alkarex** [comment] 2020-12-22 15:52
@rezad1393 Please open a new issue instead and explain your precise problem
