### ISSUE TITLE
Extension : from a youtube.com feed to a hooktube.com feed

### ISSUE THREAD

**Issue by Korbak** [FreshRSS/FreshRSS#1737] opened 2017-12-18 17:55 UTC
Hello,

I've forked the FreshRSS-Youtube extension, which allows a YouTube RSS Feed's entry to be displayed in an embeded video. My fork displays a hooktube embeded video instead.

I would like to edit every link displayed (title - clickable icons) in this entry from *.youtube.* to *.hooktube.*.

Is it possible to do that, and overall : how ? I tried to edit the value of $entry->link(), but it didn't seem to work.

I looked up other extensions to try understanding, but I deadly can't.

Thanks for your help <3
(And pardon my french)

**Comment by Alkarex** [comment] 2017-12-18 18:14
Hello,
If you have a link to your code, please put it here, so we can have a look.

**Comment by kevinpapst** [comment] 2017-12-18 18:31
From what i see, I would say the problem is simply a typo: there is no function `$entry->__link($ht_url);`, remove one underscore and make it `$entry->_link($ht_url);`

**Comment by Korbak** [comment] 2017-12-18 18:38
...
I can't believe that *definitely* was a typo.
My. God.
Thanks (and thanks for your work, glad to see you be my saviour a second time ;)) !

**Comment by kevinpapst** [comment] 2017-12-18 18:44
LOL, no problem :)

Once you are happy with your extension, please submit it here: https://github.com/FreshRSS/Extensions
You can add a link to the README and an entry in the extensions.json file.

**Comment by Korbak** [comment] 2017-12-18 18:49
It would be my honor !
I am not sure to get how, but I'm just gonna do what you told ;).

**Comment by Frenzie** [comment] 2017-12-19 20:02
I suppose we can close this with https://github.com/FreshRSS/Extensions/pull/25 merged?

**Comment by kevinpapst** [comment] 2017-12-19 20:34
Yes, I guess we keep on talking in #1713

**Closed as completed** 2017-12-19 21:35 UTC
Labels: Extension :electric_plug:
