### ISSUE TITLE
OPML import: Categories not getting imported

### ISSUE THREAD

**Issue by rb2k** [FreshRSS/FreshRSS#3284] opened 2020-12-25 16:16 UTC
This is on Version 1.17.0
I exported this opml from feedbin (the hosted service).
When importing, they all show up as uncegetorized.

It seems like there's a few uncategorized <outline [...] /> entries and then the categories start with <outline text title> [outlines with links] </outline>

Here's a version with the superfluous entries removed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
  <head>
    <title>RSS subscriptions for email@tld.com</title>
    <dateCreated>Fri, 25 Dec 2020 04:50:59 +0000</dateCreated>
    <ownerEmail>email@tld.com</ownerEmail>
  </head>
  <body>
<outline text="Debuggable.com - Blog" title="Debuggable.com - Blog" type="rss" xmlUrl="http://feeds.feedburner.com/debuggable" htmlUrl="http://www.debuggable.com/"/>
<outline text="Google Mobile Blog" title="Google Mobile Blog" type="rss" xmlUrl="http://feeds.feedburner.com/OfficialGoogleMobileBlog" htmlUrl="http://googlemobile.blogspot.com/"/>
    <outline text="comedy" title="comedy">
<outline text="Animals Being Dicks" title="Animals Being Dicks" type="rss" xmlUrl="http://animalsbeingdicks.com/rss?c0564a80?63c2cf08" htmlUrl="http://animalsbeingdicks.com/"/>
<outline text="xkcd" title="xkcd" type="rss" xmlUrl="http://blag.xkcd.com/feed/" htmlUrl="https://blog.xkcd.com"/>
<outline text="Satire from the Borowitz Report" title="Satire from the Borowitz Report" type="rss" xmlUrl="http://www.newyorker.com/online/blogs/borowitzreport/rss.xml" htmlUrl="https://www.newyorker.com/humor/borowitz-report"/>
    </outline>
    <outline text="money" title="money">
<outline text="Big Habitat" title="Big Habitat" type="rss" xmlUrl="http://saverocity.com/bighabitat/feed/" htmlUrl="https://saverocity.com/bighabitat"/>
<outline text="Financial Product Reviews" title="Financial Product Reviews" type="rss" xmlUrl="http://saverocity.com/products/feed/" htmlUrl="http://saverocity.com/products"/>
<outline text="Doctor Of Credit" title="Doctor Of Credit" type="rss" xmlUrl="http://feeds.feedburner.com/DoctorOfCredit" htmlUrl="https://www.doctorofcredit.com"/>
    </outline>
    <outline text="nosql" title="nosql">
<outline text="Luca Garulli - The Zion City" title="Luca Garulli - The Zion City" type="rss" xmlUrl="http://zion-city.blogspot.com/feeds/posts/default" htmlUrl="https://zion-city.blogspot.com/"/>
<outline text="The NOSQL Tapes" title="The NOSQL Tapes" type="rss" xmlUrl="http://feeds.feedburner.com/nosqltapes" htmlUrl="http://nosqltapes.com/"/>
<outline text="myNoSQL" title="myNoSQL" type="rss" xmlUrl="http://feeds.feedburner.com/nosql" htmlUrl="https://nosql.mypopescu.com/"/>
<outline text="antirez weblog" title="antirez weblog" type="rss" xmlUrl="http://feeds.feedburner.com/antirez" htmlUrl="http://antirez.com"/>
<outline text="MySQL Performance Blog" title="MySQL Performance Blog" type="rss" xmlUrl="http://www.mysqlperformanceblog.com/feed/" htmlUrl="https://www.percona.com/blog"/>
    </outline>
    <outline text="python" title="python">
<outline text="PyMOTW – Doug Hellmann" title="PyMOTW – Doug Hellmann" type="rss" xmlUrl="http://feeds.doughellmann.com/PyMOTW" htmlUrl="https://doughellmann.com/blog"/>
    </outline>
    <outline text="ruby" title="ruby">
<outline text="chris moos's blog" title="chris moos's blog" type="rss" xmlUrl="http://www.chrismoos.com/atom.xml" htmlUrl="http://www.chrismoos.com"/>
    </outline>
  </body>
</opml>
```

**Comment by Alkarex** [comment] 2020-12-25 18:13
Hello @rb2k 
I cannot seem to reproduce the problem with FreshRSS 1.17.1-dev:

![image](https://user-images.githubusercontent.com/1008324/103140295-1a70fe80-46e5-11eb-96c7-be8fc438e381.png)

I will try with 1.17.0 a bit later

**Comment by Alkarex** [comment] 2020-12-25 18:47
Seems to work just as well with 1.17.0 (tested using our official Docker image).
Please try again, an tell your system details: OS, database, PHP version, etc.
Remember to check your Web server logs for any related message.

**Comment by rb2k** [comment] 2020-12-25 20:27
Thanks a lot for trying to reproduce so quickly!
I'm using a docker container (https://hub.docker.com/r/linuxserver/freshrss) on suse tumbleweed.

The original import was a lot bigger and I cut out some of the superfluous stuff. Maybe that was the issue.
The full opml is: [subscriptions.xml.zip](https://github.com/FreshRSS/FreshRSS/files/5742369/subscriptions.xml.zip)

Let me do some due diligence on my part and check the log files.

So far all I see in the php error log is:

```
[24-Dec-2020 20:49:48] NOTICE: fpm is running, pid 321
[24-Dec-2020 20:49:48] NOTICE: ready to handle connections
[24-Dec-2020 20:51:13] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
[24-Dec-2020 20:55:20] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
[25-Dec-2020 08:05:47] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```

**Comment by rb2k** [comment] 2020-12-25 20:38
Huh, confirmed. The 'minimal' example I posted up to actually imports fine with categories for me too.
The full one (attached as subscriptions.xml.zip) still does not. All of them end up as uncategorized.

**Comment by rb2k** [comment] 2020-12-25 20:44
raising pm.max_children didn't help

<img width="394" alt="Screen Shot 2020-12-25 at 12 44 30 PM" src="https://user-images.githubusercontent.com/9519/103141831-f85c8980-46ae-11eb-90ab-4c5140a9ac1d.png">

**Comment by Alkarex** [comment] 2020-12-26 11:38
Ok, this is due to feeds being listed more than once in the OPML.
Fixed with https://github.com/FreshRSS/FreshRSS/pull/3286 Could you give a try to this patch? @rb2k ?
It gives the priority to the declaration of the feeds in a category.
Related to https://github.com/FreshRSS/FreshRSS/issues/1989#issuecomment-748493000

**Closed as completed by Alkarex** 2020-12-26 11:38 UTC

**Comment by rb2k** [comment] 2020-12-26 15:46
Oh wow. Yeah, I've been importing and exporting this set of feeds over the last 15 years or so. I guess the clutter collected :)
I applied the patch locally and it does indeed fix the issue \o/

**Comment by Alkarex** [comment] 2020-12-26 16:22
@rb2k Thanks for the feedback :-)
