### ISSUE TITLE
[Feature] Please support PHP 8

### ISSUE THREAD

**Issue by qu5** [FreshRSS/FreshRSS#3498] opened 2021-03-06 12:46 UTC
FreshRSS is my favorite rss-reader, But it still cannot run on php8
> HTTP ERROR 500

I hope FreshRSS can run on php8.

**Comment by aledeg** [comment] 2021-03-06 12:53
It might be related to something else than PHP8.
Our docker environment use that version PHP flawlessly.
Do you have other errors to share? logs? etc...

**Comment by Alkarex** [comment] 2021-03-06 13:32
@qu5 Which FreshRSS version are you running, how did you install it, and on which platform?
Our current master version supports PHP8, and will be released as FreshRSS 1.18.0 shortly.

**Comment by Alkarex** [comment] 2021-03-06 13:33
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/3082 , solved

**Comment by Frenzie** [comment] 2021-03-06 14:45
Closing as a duplicate. Please use master or wait for 1.18. :-)

**Closed by Frenzie** 2021-03-06 14:45 UTC
Labels: Duplicate ‼, Vote to close

**Comment by qu5** [comment] 2021-03-06 17:15
> It might be related to something else than PHP8.
> Our docker environment use that version PHP flawlessly.
> Do you have other errors to share? logs? etc...

caddy 2
php 8.03
Open URL prompt：

> ERR_TOO_MANY_REDIRECTS

URL will have a lot of `/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/`

**Comment by qu5** [comment] 2021-03-06 17:21
> It might be related to something else than PHP8.
> Our docker environment use that version PHP flawlessly.
> Do you have other errors to share? logs? etc...

alpine 3.13.2
caddy 2
php 8.03
master version 

Open URL prompt：

> ERR_TOO_MANY_REDIRECTS

URL will have a lot of `/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/`

Extended reference
https://github.com/FreshRSS/FreshRSS/blob/master/Docker/Dockerfile-Alpine

**Comment by Alkarex** [comment] 2021-03-06 20:57
Can you share your docker-compose or similar, @qu5 ?
This looks like a bad server configuration. You are not supposed to expose `/p/` in the public URL. The root is inside this `/p/` folder.

**Comment by Alkarex** [comment] 2021-03-06 20:58
P.S. We have an official FreshRSS Docker image, which might help: https://hub.docker.com/r/freshrss/freshrss/

**Comment by qu5** [comment] 2021-03-07 03:59
> Can you share your docker-compose or similar, @qu5 ?
> This looks like a bad server configuration. You are not supposed to expose `/p/` in the public URL. The root is inside this `/p/` folder.


Thank you very much for your help
But it still doesn't respond. Clicking "next" doesn't respond

see my website
https://lesi.xyz

**php config**
https://lesi.xyz/x.php
**phpinfo**
https://lesi.xyz/x.php?action=phpInfoDetail

**Comment by qu5** [comment] 2021-03-07 10:58
> Can you share your docker-compose or similar, @qu5 ?
> This looks like a bad server configuration. You are not supposed to expose `/p/` in the public URL. The root is inside this `/p/` folder.

php 8 changelog for session_start
**https://www.php.net/manual/en/function.session-save-path.php**

Some Warning:
> Warning: session_start(): open(/tmp/sess_i0d0tkdhmbmgmp2e30k1ff10p9, O_RDWR) failed: Permission denied (13) in /var/www/lib/Minz/Session.php on line 50
> 
> Warning: session_start(): Failed to read session data: files (path: ) in /var/www/lib/Minz/Session.php on line 50
> 
> Warning: session_start(): open(/tmp/sess_8ad0o0ia22of9ca2tnlv6etq9m, O_RDWR) failed: Permission denied (13) in /var/www/lib/Minz/Session.php on line 74
> 
> Warning: session_start(): Failed to read session data: files (path: ) in /var/www/lib/Minz/Session.php on line 74
> 
> Warning: session_start(): open(/tmp/sess_12rna3j2umneis4mqsk35l709t, O_RDWR) failed: Permission denied (13) in /var/www/lib/Minz/Session.php on line 74
> 
> Warning: session_start(): Failed to read session data: files (path: ) in /var/www/lib/Minz/Session.php on line 74
> 
> Warning: session_start(): open(/tmp/sess_qq57p4egogpgtp2npu3vjdva7f, O_RDWR) failed: Permission denied (13) in /var/www/lib/Minz/Session.php on line 74
> 
> Warning: session_start(): Failed to read session data: files (path: ) in /var/www/lib/Minz/Session.php on line 74

**Comment by Alkarex** [comment] 2021-03-07 11:53
Your `/tmp/` directory is probably not writeable by your Web server.
You need to tell us more about your configuration. How did you deploy FreshRSS? Are you using Docker? You say you use Caddy - which configuration?

**Comment by qu5** [comment] 2021-03-07 12:25
Permission Issue.
I changed PHP nobody to www user. It works
