### ISSUE TITLE
Add Time zone options for each user

### ISSUE THREAD

**Issue by Hill-98** [FreshRSS/FreshRSS#2754] opened 2020-01-06 10:25 UTC
Currently, only time zone settings in php.ini can be used, which is very bad, and you should be able to set the global time zone at config.php, as well as each user setting the time zone separately.

**Comment by Alkarex** [comment] 2020-01-06 14:54
Yes indeed. More or less duplicate of https://github.com/FreshRSS/FreshRSS/issues/853

**Comment by HunterZ** [comment] 2021-07-08 01:07
Just started trying FreshRSS, and found it very confusing that an article was dated an hour in the future. Turns out that it's using my hosting provider's timezone (UTC-6) rather than my own (UTC-7).

Going to be pretty annoying living with this if there's no way to address it... Even a global configuration option would be better than nothing.

**Comment by Alkarex** [comment] 2022-11-28 22:29
Implemented in https://github.com/FreshRSS/FreshRSS/pull/4906
Tests welcome

**Closed as completed** 2022-11-29 14:27 UTC
Labels: Feature Request
