### ISSUE TITLE
[PHP 7] Share buttons not working properly

### ISSUE THREAD

**Issue by angristan** [FreshRSS/FreshRSS#1072] opened 2016-02-07 19:01 UTC
Hello,

What is the procedure to configure the share button to a Diaspora\* Pod ? I don't see anything related in the docs.

**Comment by Alkarex** [comment] 2016-02-07 19:07
Hello,
See an example on https://github.com/danc/FreshRSS/commit/1efdf7914d2c42c99dc28088e847f1f5e8f186a9
https://github.com/FreshRSS/FreshRSS/pull/1054

**Comment by royalterra** [comment] 2016-02-07 19:08
Is the seam question I have for hubzilla this software no promote any federation network only centralized networks

**Comment by angristan** [comment] 2016-02-07 19:10
Journal du Hacker and Diaspora\* are not the same things :c

**Comment by angristan** [comment] 2016-02-07 19:14
I think that `https://framasphere.org/bookmarklet?title=~TITLE~&url=~LINK~&jump=doclose` could work, but when I add this line and validate, it disappear.

![screenshot_07-02-2016_7b7omptp](https://cloud.githubusercontent.com/assets/11699655/12874624/5b88657a-cdd7-11e5-9aa4-5ee389ac3440.png)
![screenshot_07-02-2016_mhjjrd5b](https://cloud.githubusercontent.com/assets/11699655/12874625/5e2ba81e-cdd7-11e5-84cf-f3fc51a42222.png)

**Comment by marienfressinaud** [comment] 2016-02-07 19:49
You just have to give your pod URL: https://framasphere.org

The fact it disappears is strange though…

**Comment by angristan** [comment] 2016-02-07 19:58
With the pod URL it disappears too. And the URL of the share button is now :
`https://[freshrssURL]/bookmarklet?url=&title=`

**Comment by angristan** [comment] 2016-02-09 17:14
The twitter share button does not work either, its URL is `https://twitter.com/share?url=&text=`

I am running the latest stable version of FreshRSS with Nginx 1.9.9 and PHP 7.0.3

**Comment by Alwaysin** [comment] 2016-02-09 19:26
Both (Diaspora\* & Twitter) work fine for me - Apache 2.2.22 & PHP 5.4.45.

Others have reported errors with PHP 7.0 if I recall correctly, this may be the issue.

**Comment by marienfressinaud** [comment] 2016-02-09 19:37
It seems to be related to PHP7 [indeed](https://twitter.com/Seboss666/status/697126594528342017). @Angristan do you have some interesting logs? :)

**Comment by angristan** [comment] 2016-02-09 19:52
Yep, Nginx error log : 

```
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
PHP message: PHP Notice:  Array to string conversion in /srv/freshrss/app/Models/Share.php on line 126
```

**Comment by seboss666** [comment] 2016-02-09 20:38
Hi,
Same here, so it may be related to PHP 7. I suggest to rename the issue :)

**Comment by Alkarex** [comment] 2016-02-16 23:40
https://github.com/FreshRSS/FreshRSS/blob/b8fd3caf8306e8616fcb2f2c0add95b74c2ec024/app/Models/Share.php#L126
Could you maybe have a look, @aledeg ? :-)

**Comment by Cyrixo** [comment] 2016-02-26 11:31
Hi,
Same here, PHP-7 and Apache-2.4.18 :

`PHP Notice:  Array to string conversion in /srv/http/rss/app/Models/Share.php on line 126`

**Comment by Alkarex** [comment] 2016-02-26 12:11
Could you please try to replace this line 126 of Share.php by

``` php
$this->{$available_options[$key]} = $value;
```

**Comment by Cyrixo** [comment] 2016-02-27 08:47
After the replacement of the line 126, there is not error anymore which appears in log.
I configure a share with Shaarli, it's ok.
But when I want to share a link, a tab opens, but the link does not seem sent correctly.

**Comment by Alkarex** [comment] 2016-02-27 15:48
@Cyrixo Could you please paste here the URL you are directed to when clicking on your share button?

**Comment by Cyrixo** [comment] 2016-02-27 16:05
I try sharing this URL to Shaarli : http://standblog.org/blog/post/2016/02/27/Apple-contre-FBI
When i click on the share button, the URL of the new tab is :
`https://liens.cyrillinux.website/?do=addlink?post=http%3A%2F%2Fstandblog.org%2Fblog%2Fpost%2F2016%2F02%2F27%2FApple-contre-FBI&title=Apple%20contre%20FBI%20%C2%B7%20Standblog&source=FreshRSS`

**Comment by Alkarex** [comment] 2016-02-27 21:06
@Cyrixo Please try with `https://liens.cyrillinux.website/` for your Shaarli address (i.e. without the `?do=addlink`)

**Comment by Cyrixo** [comment] 2016-02-27 21:09
It's OK. Thank you very much

**Comment by Alkarex** [comment] 2016-02-27 21:11
Perfect. I have merged the fix in the /dev branch. Would be nice if you could give a try to the /dev branch.

**Closed as completed by Alkarex** 2016-02-27 21:11 UTC

**Comment by Cyrixo** [comment] 2016-02-27 21:18
You want that I test the /dev branch on my server ?

**Comment by Alkarex** [comment] 2016-02-27 21:30
Yes, if you can, or on a test machine (remembering that /dev is less stable than /beta).

**Comment by Cyrixo** [comment] 2016-02-27 21:40
Why not on a test machine. You need testers ?

**Comment by Alkarex** [comment] 2016-02-27 22:38
Yes, ~~I~~ we need testers, to test several uses / platforms / conditions etc. I do test on my side, but that is not enough. I also try to get at least one other person to confirm that a patch is working as intended.

**Comment by Cyrixo** [comment] 2016-02-28 20:44
I test the /dev branch with apache-2.4.18 PHP-7.0.3 and MariaDB-10.1.11.
The sharing to Shaarli works well.
See you soon.

**Comment by Alkarex** [comment] 2016-02-28 21:16
Thanks @Cyrixo :+1: The next version 1.3.1-beta of FreshRSS is soon ready.
