### ISSUE TITLE
Feed title sorting in categories shoudn't be case sensitive

### ISSUE THREAD

**Issue by mourdrim** [FreshRSS/FreshRSS#3144] opened 2020-08-15 18:12 UTC
![TitleSort](https://user-images.githubusercontent.com/69729502/90318747-fae0f280-df08-11ea-85ad-21965b8b1904.jpg)

Feed title sorting in categories shouldn't be case sensitive.
As you can see all uppercase feeds are sorted before the lowercase ones. It would be best to keep them all sorted as case insensitive, respecting alphabetical order.

FreshRSS 1.16.2.

**Comment by aledeg** [comment] 2020-08-16 15:36
Duplicate of #3128 
Fixed by #3131

**Closed as completed by aledeg** 2020-08-16 15:36 UTC
