### ISSUE TITLE
Configuration error: system namespace does not exist

### ISSUE THREAD

**Issue by cdemi** [FreshRSS/FreshRSS#3323] opened 2021-01-03 08:30 UTC
After repulling the `freshrss/freshrss:latest` Docker tag, today, FreshRSS won't start. I am getting:

```
### Application problem ###
Configuration error: system namespace does not exist
```

`FreshRSS[27]: [_] [Sun, 03 Jan 2021 09:25:53 +0100] [error] --- Configuration error: system namespace does not exist
`

Could this be related to #3070?

**Comment by paulmorabito** [comment] 2021-01-03 08:32
Same problem for me as well.

**Comment by notarobot63** [comment] 2021-01-03 09:01
Same this morning with same Docker tag.

Edit: workaround by using tag freshrss:1.17.0 to rollback from 1.17.1 is working

**Comment by anihm136** [comment] 2021-01-03 09:08
Oh I was setting up for the first time last night, and thought it was a setup issue on my end. So I have the same issue as well

**Comment by cdemi** [comment] 2021-01-03 09:12
> Oh I was setting up for the first time last night, and thought it was a setup issue on my end. So I have the same issue as well

In the meantime you can set it up using `freshrss/freshrss:1.17.0`, then once this is fixed you can just switch to latest

**Comment by anihm136** [comment] 2021-01-03 09:21
Okay, will try that out thanks
Edit: Working fine with 1.17.0. From #3324 I understand that latest is actually the master branch, so I'll stick to the stable release for now

**Comment by Alkarex** [comment] 2021-01-03 10:24
Thanks all for the bug report. I am trying to reproduce the error, without success so far (all is fine on my side). Working on it!
What database are you using? On which architecture?
Could you please also confirm your Docker image version with the following command:

```sh
docker inspect --format='{{.Name}} {{.Image}} {{index .Config.Labels "org.opencontainers.image.revision"}}' freshrss
```

**Comment by slecorvec** [comment] 2021-01-03 10:37
Hello ! 
Same problem here. Rollback to 1.17.0 workaround is ok for me.

On debian 10 (4.19.0-11-amd64)  
Database : postgres:12

freshrss/freshrss:latest updated via watchtower : 

```
time="2021-01-03T01:59:34+01:00" level=info msg="Found new freshrss/freshrss:latest image (sha256:109a769b62c86e377650c0920f19fd908b185c1d9790292dfccb89ca069c77fd)"
time="2021-01-03T01:59:53+01:00" level=info msg="Stopping /freshrss (5bdfcd121f200e38039c4317d08ad46cb04c9b491d9e64de319e2213d6e7c36a) with SIGTERM"
time="2021-01-03T01:59:58+01:00" level=info msg="Creating /freshrss"
time="2021-01-03T01:59:59+01:00" level=info msg="Removing image sha256:87417f91f2df6782c8eadcf7fffbec97bb8e90b06c6478cecb226c8d9a4a1b0e"
```

docker inspect : 

> /freshrss sha256:109a769b62c86e377650c0920f19fd908b185c1d9790292dfccb89ca069c77fd master.31cb07ac1acf7bad8c1bf6bbef45a17f4e0edbf3

**Comment by paulmorabito** [comment] 2021-01-03 10:48
@Alkarex 

```
paul@downloader:~$ docker inspect --format='{{.Name}} {{.Image}} {{index .Config.Labels "org.opencontainers.image.revision"}}' freshrss
/freshrss sha256:109a769b62c86e377650c0920f19fd908b185c1d9790292dfccb89ca069c77fd master.31cb07ac1acf7bad8c1bf6bbef45a17f4e0edbf3
```

Database is also Postgres 12.

Rolling back to 1.17 also fixed it for me.

**Comment by Alkarex** [comment] 2021-01-03 10:50
I cannot reproduce the problem on my side (also tested with PostgreSQL), so additional info would be nice.
Can any of you try to run a new fresh instance from scratch?
Do you happen to have any extension enabled? If so, could you try disabling them all?
Are you using the Web form login method? Any special settings you can think of?
Can you share your more precise docker run or docker-compose setup?

**Comment by notarobot63** [comment] 2021-01-03 10:51
I'm on SQLite with docker image under Debian 10.7 x64

**Comment by paulmorabito** [comment] 2021-01-03 10:56
This is my docker compose:

```
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss
    restart: unless-stopped
    ports:
      - "8556:80"
    depends_on:
      - postgres
      - authelia
    volumes:
      - /freshrss/data:/var/www/FreshRSS/data
      - /freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/20
      - TZ=
```
(minus Traefik related details)

Extensions: Google Groups and Tumblr-GDPR only (these are enabled by default?)
Login is web form and with API access enabled.

It's late in the evening but I can try a fresh install tomorrow.

**Comment by typhoe** [comment] 2021-01-03 10:57
Hi, Using a non docker install, simply rooling back to commit 7bc2cc5825547f5b5cf15005fda937e06065b45d resolved the problem for me.
LXC container debian buster with postgresql database

**Comment by Alkarex** [comment] 2021-01-03 11:13
@aledeg @Frenzie Are you able to reproduce the issue?

**Comment by Frenzie** [comment] 2021-01-03 11:23
Not with
https://github.com/FreshRSS/FreshRSS/blob/31cb07ac1acf7bad8c1bf6bbef45a17f4e0edbf3/Makefile#L40-L49

**Comment by Alkarex** [comment] 2021-01-03 11:39
Problem found, thanks to a helpful user: it only happens when NOT using `FRESHRSS_ENV=development`
Fix coming

**Comment by Alkarex** [comment] 2021-01-03 11:58
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/3328
I will tell when the new Docker Hub image is ready

**Closed as completed** 2021-01-03 11:57 UTC
Labels: Critical :skull_and_crossbones:

**Comment by typhoe** [comment] 2021-01-03 12:10
Thank you very much.
Correction works for my non-docker install

**Comment by Alkarex** [comment] 2021-01-03 12:31
Docker Hub images are up to date

**Comment by notarobot63** [comment] 2021-01-03 13:05
Thanks for the quick fix on a Sunday !

**Comment by cdemi** [comment] 2021-01-03 14:18
Agreed, thanks for the quick fix on a Sunday. I confirm that the `latest` Docker tag works correctly as well

**Comment by paulmorabito** [comment] 2021-01-04 01:01
@Alkarex Thanks for the very fast response. Everything is working again now!
