### ISSUE TITLE
[Bug] Feed title option not to be shown is not applied.

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#6756] opened 2024-09-01 03:29 UTC
### Describe the bug

in "Reading" option section in subsection "Articles: header/footer" there is an option to hide feed title or move its place.
when I set it to hide and save setting, the page gets refreshed and setting it set to "above title/tags" instead.

### To Reproduce

in "Reading" option section in subsection "Articles: header/footer" there is an option to hide feed title or move its place.
when I set it to hide and save setting, the page gets refreshed and setting it set to "above title/tags" instead.

### Expected behavior

it should be hidden

### FreshRSS version

 1.24.2 

### Environment information

- Database version: [s SQLite]   sqlite 3.46.1
- PHP version: [e.g. PHP 8.1] php 8.3.11
- Installation type: [e.g. Docker, Docker image source, git, Yunohost] zip release and updates
-Web server type: [e.g. Apache, nginx] nginx
- Device: [e.g. iPhone13] laptop
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14] archlinux
- Browser: [e.g. Firefox 124] firefox 124

**Comment by math-GH** [comment] 2024-09-01 11:19
@Alkarex : Please take a look here. 
I think the issue is somewhere here:
https://github.com/FreshRSS/FreshRSS/blob/1d4443b39979a127f6104b3ebb5ea3f98e07e93b/app/Controllers/configureController.php#L125C1-L126C102
The value `'0'` will be taken as empty so it will take the default `'t'`.

Similar with `show_author_date`, but the bug is not visible here, because the default value is '0'. If you set here `'0'` => `'h'`, the bug will be there too.

I guess that `Minz_Request::paramString` is buggy in case of value `'0'` (it would be a regression from #5946)

**Comment by Alkarex** [comment] 2024-09-03 21:51
Please try https://github.com/FreshRSS/FreshRSS/pull/6771

**Comment by Alkarex** [comment] 2024-09-04 19:13
Merged in rolling release `edge`. Tests welcome

**Closed as completed** 2024-09-04 19:12 UTC
Labels: Bug (confirmed) 🐞

**Comment by math-GH** [comment] 2024-09-07 20:43
Tested. Works fine. Thanks!
