### ISSUE TITLE
Need help creating a public feed

### ISSUE THREAD

**Issue by hanan-cohen** [FreshRSS/FreshRSS#2066] opened 2018-10-22 05:14 UTC
Hello,

I would like to create a public feed, like the FreshRSS demo site.

Didn't find a way to do that.

Any help will be appreciated.

Thanks.

**Comment by Alkarex** [comment] 2018-10-22 06:39
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/2065

**Closed as completed by Alkarex** 2018-10-22 06:39 UTC
